### ISSUE TITLE
training fails when using bfloat16

### ISSUE THREAD

**Issue by nicolabertoldi** [tensorflow/tensor2tensor#1003]
### Description
I cannot train a transformer_base model using bfloat   type for both activation and weights using GPU  (GTX 1080Ti).

From the error I got
```
ValueError: Tensor conversion requested dtype bfloat16 for Tensor with dtype float32: 'Tensor("transformer/parallel_0_5/transformer/symbol_modality_8374_512/shared/ExpandDims:0", shape=(?, ?, 1, 1), dtype=float32, device=/device:GPU:0)'
```
It seems that in some part there is (at least) one wrong/missing cast.
Commands for replicability and full log are below.

Is this a bug in Tensor2Tensor? or in TensorFlow?
Is it actually impossible to use bfloat16 on gpu?
Or is there any error I am making?

### Environment information

```
OS: Ubuntu 16.04

$ pip freeze | grep tensor
tensor2tensor==1.6.3
tensorboard==1.8.0
tensorflow-gpu==1.8.0


$ python -V
Python 2.7.12
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
t2t-datagen --data_dir t2t_data/datagen --tmp_dir ./t2t_data/tmp --problem translate_enfr_wmt_small8k --hparams activation_dtype=bfloat16,weight_dtype=bfloat16

t2t-trainer --data_dir t2t_data/datagen --tmp_dir ./t2t_data/tmp --problem translate_enfr_wmt_small8k --model transformer --hparams_set transformer_base --output_dir ./t2t_data/model --local_eval_frequency=500 --train_steps=1000 --worker_gpu=1 --hparams batch_size=3072,activation_dtype=bfloat16,weight_dtype=bfloat16
```
nothing change if I do not use "--hparams activation_dtype=bfloat16,weight_dtype=bfloat16"   in data generation.

```
# Error logs:
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Overriding hparams in transformer_base with batch_size=3072,activation_dtype=bfloat16,weight_dtype=bfloat16,optimizer=Adafactor
WARNING:tensorflow:From /home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py:151: __init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
INFO:tensorflow:sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 20, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f76c00c0990>, '_keep_checkpoint_every_n_hours': 10000, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': None, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_train_distribute': None, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 500, '_environment': 'local', '_master': '', '_model_dir': './neural_model', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f76c9da2d10>, '_save_summary_steps': 100}
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f76c003d938>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:ValidationMonitor only works with --schedule=train_and_evaluate
WARNING:tensorflow:From /home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py:338: __init__ (from tensorflow.contrib.learn.python.learn.experiment) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.estimator.train_and_evaluate. You will also have to convert to a tf.estimator.Estimator.
WARNING:tensorflow:continuous_train_and_eval (from tensorflow.contrib.learn.python.learn.experiment) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:Training model for 500 steps
INFO:tensorflow:Reading data files from t2t_data/datagen/translate_enfr_wmt_small8k-train*
INFO:tensorflow:partition: 0 num_data_files: 100
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Setting T2TModel mode to 'train'
INFO:tensorflow:Using variable initializer: uniform_unit_scaling
INFO:tensorflow:Transforming feature 'inputs' with symbol_modality_8374_512.bottom
Traceback (most recent call last):
  File "/home/nicola/.local/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/nicola/.local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 353, in main
    execute_schedule(exp)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 302, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/framework/experimental.py", line 64, in new_func
    return func(*args, **kwargs)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 773, in continuous_train_and_eval
    saving_listeners=self._saving_listeners)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 876, in _call_train
    saving_listeners=saving_listeners)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 922, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 972, in estimator_model_fn
    logits, losses_dict = model(features)  # pylint: disable=not-callable
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 154, in call
    sharded_logits, losses = self.model_fn_sharded(sharded_features)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 209, in model_fn_sharded
    sharded_logits, sharded_losses = dp(self.model_fn, datashard_to_features)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/expert_utils.py", line 230, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 233, in model_fn
    transformed_features = self.bottom(features)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 275, in bottom
    transformed_features[key] = input_modality.bottom(features[key])
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/layers/modalities.py", line 121, in bottom
    return self.bottom_simple(x, "shared", reuse=None)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensor2tensor/layers/modalities.py", line 115, in bottom_simple
    ret *= tf.expand_dims(tf.to_float(tf.not_equal(x, 0)), -1)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 970, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1014, in convert_to_tensor
    as_ref=False)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/nicola/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 947, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype bfloat16 for Tensor with dtype float32: 'Tensor("transformer/parallel_0_5/transformer/symbol_modality_8374_512/shared/ExpandDims:0", shape=(?, ?, 1, 1), dtype=float32, device=/device:GPU:0)'
```

**Comment by cbockman** [comment]
bfloat16 is only TPU, not GPU.

**Comment by nicolabertoldi** [comment]
Is there any reason why 'bfloat16' is not available for GPU?

Is there any other way to use half_precision with GPU?
