### ISSUE TITLE
Error in running translate_ende_wmt32k by universal transformer

### ISSUE THREAD

**Issue by lipond** [tensorflow/tensor2tensor#1042]
### Description
My command is as below:

```
HOME_DIR=$HOME/workdir
PROBLEM=translate_ende_wmt32k
MODEL=universal_transformer
HPARAMS=universal_transformer_base
NUM_GPU=2
DATA_DIR=$HOME_DIR/t2t_data/$PROBLEM
TRAIN_DIR=$HOME_DIR/t2t_train/$PROBLEM/$MODEL-$HPARAMS
mkdir -p $TRAIN_DIR

t2t-trainer \
    --data_dir=$DATA_DIR \
    --problem=$PROBLEM \
    --model=$MODEL \
    --hparams_set=$HPARAMS \
    --output_dir=$TRAIN_DIR \
    --worker_gpu=$NUM_GPU
```

### Environment information
TF=1.8
T2T=1.9 (But I installed it from master in order to avoid a data generation bug of translate_ende_wmt32k)

OS: RHEL 7.0

```
$ pip freeze | grep tensor
-e git+https://github.com/tensorflow/tensor2tensor@54510673d1ded46575c68091d2aaf791f9007a34#egg=tensor2tensor
tensorboard==1.8.0
tensorflow==0.10.0
tensorflow-gpu==1.8.0
tensorflow-tensorboard==1.5.1
```

```
$ python -V
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)
```

# Error logs:
```
WARNING:tensorflow:From /gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/trainer_lib.py:198: __init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=2
INFO:tensorflow:sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0', 'gpu:1']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0', 'gpu:1']
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 20, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f0747cec310>, '_keep_checkpoint_every_n_hours': 10000, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': None, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_train_distribute': None, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 1000, '_environment': 'local', '_master': '', '_model_dir': '/home/sanjie.lp/workdir/t2t_train/translate_ende_wmt32k/universal_transformer-universal_transformer_base', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f0747cec350>, '_save_summary_steps': 100}
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f074748caa0>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:ValidationMonitor only works with --schedule=train_and_evaluate
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after 600 secs (eval_spec.throttle_secs) or training is finished.
INFO:tensorflow:Reading data files from /home/sanjie.lp/workdir/t2t_data/translate_ende_wmt32k/translate_ende_wmt32k-train*
INFO:tensorflow:partition: 0 num_data_files: 100
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Setting T2TModel mode to 'train'
INFO:tensorflow:Using variable initializer: uniform_unit_scaling
INFO:tensorflow:Transforming feature 'inputs' with symbol_modality_33288_1024.bottom
INFO:tensorflow:Transforming 'targets' with symbol_modality_33288_1024.targets_bottom
INFO:tensorflow:Building model body
Traceback (most recent call last):
  File "/home/sanjie.lp/workdir/softwares/anaconda2/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/sanjie.lp/workdir/softwares/anaconda2/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/bin/t2t_trainer.py", line 355, in main
    execute_schedule(exp)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/bin/t2t_trainer.py", line 321, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/trainer_lib.py", line 331, in continuous_train_and_eval
    self._eval_spec)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 650, in run_local
    hooks=train_hooks)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 1225, in wrapping_model_fn
    decode_hparams=decode_hparams)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 1277, in estimator_model_fn
    logits, losses_dict = model(features)  # pylint: disable=not-callable
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 213, in call
    sharded_logits, losses = self.model_fn_sharded(sharded_features)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 268, in model_fn_sharded
    sharded_logits, sharded_losses = dp(self.model_fn, datashard_to_features)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/expert_utils.py", line 230, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 304, in model_fn
    body_out = self.body(transformed_features)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/models/research/universal_transformer.py", line 172, in body
    inputs, target_space, hparams, features=features)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/models/research/universal_transformer.py", line 85, in encode
    save_weights_to=self.attention_weights))
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/models/research/universal_transformer_util.py", line 125, in universal_transformer_encoder
    x, hparams, ffn_unit, attention_unit, pad_remover=pad_remover)
  File "/gruntdata/sanjie.lp/projects/tensor2tensor/tensor2tensor/models/research/universal_transformer_util.py", line 251, in universal_transformer_layer
    ut_function, tf.range(hparams.num_rec_steps), initializer=initializer)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 132, in foldl
    swap_memory=swap_memory)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2915, in _BuildLoop
    nest.assert_same_structure(list(packed_vars_for_body), list(body_result))
  File "/home/sanjie.lp/workdir/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 183, in assert_same_structure
    _pywrap_tensorflow.AssertSameStructure(nest1, nest2, check_types)
ValueError: The two structures don't have the same nested structure.

First structure: type=list str=[<tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/Identity:0' shape=() dtype=int32>, <tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/Identity_1:0' shape=(3, ?, ?, 1024) dtype=float32>]

Second structure: type=list str=[<tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/add_2:0' shape=() dtype=int32>, (<tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/ffn/layer_postprocess/add:0' shape=(?, ?, 1024) dtype=float32>, <tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/unstack:1' shape=(?, ?, 1024) dtype=float32>, <tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/unstack:2' shape=(?, ?, 1024) dtype=float32>)]

More specifically: Substructure "type=tuple str=(<tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/ffn/layer_postprocess/add:0' shape=(?, ?, 1024) dtype=float32>, <tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/unstack:1' shape=(?, ?, 1024) dtype=float32>, <tf.Tensor 'universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/unstack:2' shape=(?, ?, 1024) dtype=float32>)" is a sequence, while substructure "type=Tensor str=Tensor("universal_transformer/parallel_0_5/universal_transformer/universal_transformer/body/encoder/universal_transformer_basic/foldl/while/Identity_1:0", shape=(3, ?, ?, 1024), dtype=float32, device=/device:GPU:0)" is not
```

**Comment by lukaszkaiser** [comment]
Please update TF to 1.10 or at least 1.9 (we do not support 1.8 any more).

**Comment by lipond** [comment]
I updated TF to 1.9, which solved the problem.
