### ISSUE TITLE
INFO:tensorflow:Found unparsed command-line arguments. Checking if any start with --hp_ and interpreting those as hparams settings

### ISSUE THREAD

**Issue by strongcc** [tensorflow/tensor2tensor#1073]
### Description
####cmd
```
t2t-trainer --registry_help

#export CUDA_VISIBLE_DEVICES=""
PROBLEM=translate_enzh_wmt32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu
HOME=`pwd`
DATA_DIR=$HOME/t2t_data
TMP_DIR=$DATA_DIR
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
#t2t-datagen \
#  --data_dir=$DATA_DIR \
#  --tmp_dir=$TMP_DIR \
#  --problem=$PROBLEM

# Train
# *  If you run out of memory, add --hparams='batch_size=2048' or even 1024.
#t2t-trainer   --generate_data   --problem=image_mnist   --data_dir=~/t2t_data   --tmp_dir=~/t2t_data/tmp
#  --model=shake_shake   --hparams_set=shake_shake_quick   --output_dir=~/t2t_train/mnist1   --train_steps=1000   --eval_steps=100

#--t2t_usr_dir=/data1/home/tracytian/bin/anaconda2/lib/python2.7 \
# --hparams_set=$HPARAMS \
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR
```

####but error ERROR LOGS
```
INFO:tensorflow:Found unparsed command-line arguments. Checking if any start with --hp_ and interpreting those as hparams settings.
WARNING:tensorflow:Found unknown flag: --problems=translate_enzh_wmt32k
WARNING:tensorflow:From /data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py:198: __init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
INFO:tensorflow:sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
None
Traceback (most recent call last):
  File "/data1/home/tracytian/bin/anaconda2/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/data1/home/tracytian/bin/anaconda2/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 352, in main
    exp = exp_fn(create_run_config(hparams), hparams)
  File "/data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 583, in experiment_fn
    return create_experiment(run_config, hparams, *args, **kwargs)
  File "/data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 469, in create_experiment
    add_problem_hparams(hparams, problem_name)
  File "/data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 590, in add_problem_hparams
    problem = registry.problem(problem_name)
  File "/data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/registry.py", line 273, in problem
    base_name, was_reversed, was_copy = parse_problem_name(name)
  File "/data1/home/tracytian/bin/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/registry.py", line 264, in parse_problem_name
    if problem_name.endswith("_rev"):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

why?

**Comment by martinpopel** [comment]
Use --problem instead of --problems.

**Comment by strongcc** [comment]
thank you very much. it could run !

**Comment by afrozenator** [comment]
Thanks @martinpopel . Closing this issue.
