### ISSUE TITLE
Multimodel Problem - Refusing to perform an overparameterized separable convolution

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#109]
Information:
PROBLEM=wmt_ende_tokens_32k
MODEL=multi_model
HPARAMS=multimodel_base

The transformer model run normally with this problem. However, the multi_model model doesn't want to run.

`
WARNING:tensorflow:It is strongly recommended to specify --output_dir. Using default output_dir=/tmp/tensor2tensor.
INFO:tensorflow:Creating experiment, storing model files in /tmp/tensor2tensor
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tensor2tensor', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f151df1d650>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_session_config': allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
}
INFO:tensorflow:Performing local training.
WARNING:tensorflow:From /home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:268: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
Traceback (most recent call last):
  File "t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 246, in run
    run_locally(exp_fn(output_dir))
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 536, in run_locally
    exp.train_and_evaluate()
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 955, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1162, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 431, in model_fn
    len(hparams.problems) - 1)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 750, in _cond_on_index
    return fn(cur_idx)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 412, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 415, in model_fn
    transformed_features)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/multimodel.py", line 104, in model_fn_body_sharded
    inputs_mask, i)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/multimodel.py", line 64, in conv_experts
    conv_out = dp(conv_res_step, xs, hparams, padding, mask)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/expert_utils.py", line 294, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/multimodel.py", line 46, in conv_res_step
    padding=padding, mask=mask, separabilities=0, name="residual2")
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/common_layers.py", line 533, in subseparable_conv_block
    dilation_rates_and_kernel_sizes, **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/common_layers.py", line 510, in conv_block_internal
    **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/common_layers.py", line 383, in subseparable_conv
    return conv_internal(conv_fn, inputs, filters, kernel_size, **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/common_layers.py", line 331, in conv_internal
    return conv2d_kernel(kernel_size, "single")
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/common_layers.py", line 324, in conv2d_kernel
    result = conv_fn(inputs, filters, kernel_size_arg, name=name, **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensor2tensor/models/common_layers.py", line 378, in conv_fn
    **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 1019, in separable_conv2d
    return layer.apply(inputs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 883, in call
    rate=self.dilation_rate)
  File "/home/agemagician/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 486, in separable_conv2d
    channel_multiplier * in_channels, out_channels))
ValueError: Refusing to perform an overparameterized separable convolution: channel_multiplier * in_channels = 1 * 2048 = 2048 > 512 = out_channels
`

**Comment by lukaszkaiser** [comment]
The bad new is that it's a problem of TensorFlow kernels, must be corrected there, not in tensor2tensor. The good news is that it's already corrected there :). I just checked and it should run fine with the latest TensorFlow nightly, and it'll be part of the 1.3 release of TensorFlow.
