### ISSUE TITLE
cannot import name inplace_ops

### ISSUE THREAD

**Issue by nadavb** [tensorflow/tensor2tensor#1116]
### Description
I have just upgraded my t2t (took the last ~500 commits), and got:
 ```
Skipped importing 62 data_generators modules.
Traceback (most recent call last):
From module tensor2tensor.data_generators.algorithmic
 File ".../tensor2tensor/problems.py", line 33, in <module>
    all_problems.import_modules(all_problems.ALL_MODULES)
  File ".../tensor2tensor/data_generators/all_problems.py", line 123, in import_modules
    _handle_errors(errors)
  File ".../tensor2tensor/data_generators/all_problems.py", line 111, in _handle_errors
    raise err
ImportError: cannot import name inplace_ops
```

### Environment information

```
$ pip freeze | grep tensor
tensorflow==1.5.0
tensorflow-serving-api==1.5.0
tensorflow-tensorboard==1.5.0

$ python -V
Python 2.7.12
```

It feels like the t2t is not fully backward compatible. Was the tensorflow version changed? Any new package should be installed? It would be nice to add some try/catch to print meaningful errors when an import failed, etc.

**Comment by nadavb** [comment]
Okay, solved the problem by:
1. Upgrading from TF 1.5 to 1.10 -> `sudo pip install ‘tensorflow==1.10'`
2. Had to change my model data dir vocabulary file name from `vocab.ende.32768` to `vocab.translate_ende_wmt32k.32768.subwords`

A general recommendation:
I think it would be wise to make the t2t code a bit more defensive, meaning that if it requires TF >1.10, so the t2t can simply check the TF version and throw error if version is to low (would you like me to create a PR for that?)
And when the vocab filename is changed, so keep the old filename and do some fallback that if the filename does not exist, search for the old one and add some deprecation warning. This will allow people to migrate more easily, if the code is not backward compatible...
