### ISSUE TITLE
checkpoint_path AttributeError during exporting

### ISSUE THREAD

**Issue by KayShenClarivate** [tensorflow/tensor2tensor#1193]
### Description

I am trying to use t2t-exporter to export a specific checkpoint. I set checkpoint_path, but when i ran t2t-exporter, it complains AttributeError.

```
t2t-exporter \
  --data_dir=$DATA_DIR \
  --checkpoint_path=$TRAIN_DIR\/model.ckpt-251001 \
  --problem=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --t2t_usr_dir=$USR_DIR
```

INFO:tensorflow:Importing user module train_mat_adv from path /models
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/bin/t2t-exporter", line 16, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/tensorflow/bin/t2t-exporter", line 12, in main
    export.main(argv)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/serving/export.py", line 59, in main
    run_config = t2t_trainer.create_run_config(hparams)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 189, in create_run_config
    assert FLAGS.output_dir or FLAGS.checkpoint_path
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: checkpoint_path

**Comment by KayShenClarivate** [comment]
the "--export_dir" option also does not work.

**Comment by lkluo** [comment]
The value of checkpoint_path input was inappropriate. Try `$TRAIN_DIR\model.ckpt-251001` instead.

**Comment by KayShenClarivate** [comment]
> The value of checkpoint_path input was inappropriate. Try `$TRAIN_DIR/model.ckpt-251001` instead.

Tried and not worked.

**Comment by lkluo** [comment]
Just noted that you was using `t2t-exporter` command, in which `--checkpoint_path` shall not work. I suggest you use `--output_d=$TRAIN_DIR` instead (the checkpoint 251001 should be in the first line of you `checkpoint` file). This should fix your problem.

**Comment by lkluo** [comment]
`--export_dir` does not function either, see also #1082. I don't know if the latest t2t has fixed this. You may try it.

**Comment by KayShenClarivate** [comment]
> `--export_dir` does not function either, see also #1082. I don't know if the latest t2t has fixed this. You may try it.

i see. Thanks!
