### ISSUE TITLE
Using Separate vocabulary

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#1244]
### Description
I am trying to follow "translate_enzh" to generate a separate vocabulary for inputs and outputs.
Data generation generate the data successfully but the trainer gives error.
It tries to locate a shared vocabulary not the separate vocabulary files.
Any idea how we can solve it ?

### Environment information
OS:  Ubunut

$ pip freeze | grep tensor
mesh-tensorflow==0.0.4
tensor2tensor==1.11.0
tensorboard==1.12.0
tensorflow==1.12.0
tensorflow-metadata==0.9.0
tensorflow-probability==0.5.0

$ python -V
Python 2.7.15 :: Anaconda, Inc.

### For bugs: reproduction and error logs
```
Traceback (most recent call last):
  File "/home/agemagician/anaconda3/envs/t2tp2/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/agemagician/anaconda3/envs/t2tp2/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 389, in main
    exp = exp_fn(create_run_config(hparams), hparams)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 772, in experiment_fn
    return create_experiment(run_config, hparams, *args, **kwargs)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 666, in create_experiment
    add_problem_hparams(hparams, problem_name)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 783, in add_problem_hparams
    p_hparams = problem.get_hparams(hparams)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 499, in get_hparams
    self.get_feature_encoders(data_dir)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 486, in get_feature_encoders
    self._encoders = self.feature_encoders(data_dir)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_problems.py", line 198, in feature_encoders
    encoder = self.get_or_create_vocab(data_dir, None, force_get=True)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_problems.py", line 239, in get_or_create_vocab
    replace_oov=self.oov_token)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 311, in __init__
    self._init_vocab_from_file(vocab_filename)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 347, in _init_vocab_from_file
    tokens = [token.strip() for token in f.readlines()]
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 188, in readlines
    self._preread_check()
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /media/agemagician/ssd1/t2t/p2/t2t_data/vocab.translate_amino_protin_tokens.tokens; No such file or directory
```

# Steps to reproduce:

```
@registry.register_problem
class TranslateAminoProtinTokens(translate.TranslateProblem):
  """Problem spec for WMT En-De translation."""

  @property
  def approx_vocab_size(self):
    return 2**13  # 8192

  @property
  def vocab_type(self):
    return text_problems.VocabType.TOKEN

  @property
  def source_vocab_name(self):
    return "%s.amino" % self.vocab_filename

  @property
  def target_vocab_name(self):
    return "%s.protin" % self.vocab_filename

  @property
  def is_generate_per_split(self):
    # generate_data will shard the data into TRAIN and EVAL for us.
    return False

  @property
  def dataset_splits(self):
    """Splits of data to produce and number of output shards for each."""
    # 10% evaluation data
    return [{
        "split": problem.DatasetSplit.TRAIN,
        "shards": 9,
    }, {
        "split": problem.DatasetSplit.EVAL,
        "shards": 1,
    }]
  
  def text2text_panda_iterator(self, datasetdf):
    for index, row in datasetdf.iterrows():
      yield {
      "inputs": row['input'],
      "targets": row['output'],
      }

  def generate_encoded_samples(self, data_dir, tmp_dir, dataset_split):
    datasetdf = pd.read_csv(tmp_dir + '/complete_train_dataset_seperated.csv')
    source_vocab = generator_utils.get_or_generate_vocab_inner(data_dir, self.source_vocab_name, self.approx_vocab_size,
                                     datasetdf['input'])
    target_vocab = generator_utils.get_or_generate_vocab_inner(data_dir, self.target_vocab_name, self.approx_vocab_size,
                                     datasetdf['output'])
    return text_problems.text2text_generate_encoded(
        self.text2text_panda_iterator(datasetdf),
        source_vocab, target_vocab)
```
# Error logs:
...
```

**Comment by agemagician** [comment]
I have commented the "vocab_type", but now the data generator doesn't want to produce the data:

```
INFO:tensorflow:Generating problems:
    translate:
      * translate_amino_protin_tokens_shared_vocab
INFO:tensorflow:Generating data for translate_amino_protin_tokens_shared_vocab.
Traceback (most recent call last):
  File "/home/agemagician/anaconda3/envs/t2tp2/bin/t2t-datagen", line 28, in <module>
    tf.app.run()
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/agemagician/anaconda3/envs/t2tp2/bin/t2t-datagen", line 23, in main
    t2t_datagen.main(argv)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_datagen.py", line 198, in main
    generate_data_for_registered_problem(problem)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_datagen.py", line 260, in generate_data_for_registered_problem
    problem.generate_data(data_dir, tmp_dir, task_id)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_problems.py", line 311, in generate_data
    data_dir, tmp_dir, problem.DatasetSplit.TRAIN)), all_paths)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_problems.py", line 263, in generate_encoded_samples
    encoder = self.get_or_create_vocab(data_dir, tmp_dir)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_problems.py", line 232, in get_or_create_vocab
    self.generate_text_for_vocab(data_dir, tmp_dir),
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/translate.py", line 64, in generate_text_for_vocab
    self.vocab_data_files())
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/translate.py", line 52, in vocab_data_files
    return self.source_data_files(problem.DatasetSplit.TRAIN)
  File "/home/agemagician/anaconda3/envs/t2tp2/lib/python2.7/site-packages/tensor2tensor/data_generators/translate.py", line 48, in source_data_files
    raise NotImplementedError()
NotImplementedError
```

```
@registry.register_problem
class TranslateAminoProtinTokensSeperateVocab(translate.TranslateProblem):
  """Problem spec for WMT En-De translation."""

  @property
  def approx_vocab_size(self):
    return 2**13  # 8192

  #@property
  #def vocab_type(self):
  #  return text_problems.VocabType.TOKEN

  @property
  def source_vocab_name(self):
    return "%s.amino" % self.vocab_filename

  @property
  def target_vocab_name(self):
    return "%s.protin" % self.vocab_filename

  @property
  def is_generate_per_split(self):
    # generate_data will shard the data into TRAIN and EVAL for us.
    return False

  @property
  def dataset_splits(self):
    """Splits of data to produce and number of output shards for each."""
    # 10% evaluation data
    return [{
        "split": problem.DatasetSplit.TRAIN,
        "shards": 9,
    }, {
        "split": problem.DatasetSplit.EVAL,
        "shards": 1,
    }]
  
  def text2text_panda_iterator(self, datasetdf):
    for index, row in datasetdf.iterrows():
      yield {
      "inputs": row['input'],
      "targets": row['output'],
      }

  def generate_encoded_samples(self, data_dir, tmp_dir, dataset_split):
    datasetdf = pd.read_csv(tmp_dir + '/complete_train_dataset_seperated.csv')
    source_vocab = generator_utils.get_or_generate_vocab_inner(data_dir, self.source_vocab_name, self.approx_vocab_size,
                                     datasetdf['input'])
    target_vocab = generator_utils.get_or_generate_vocab_inner(data_dir, self.target_vocab_name, self.approx_vocab_size,
                                     datasetdf['output'])
    return text_problems.text2text_generate_encoded(
        self.text2text_panda_iterator(datasetdf),
        source_vocab, target_vocab)
```
