### ISSUE TITLE
module 'tensorflow.contrib' has no attribute 'linalg'

### ISSUE THREAD

**Issue by hogowl** [tensorflow/tensor2tensor#1286]
### Description
When import 
from tensor2tensor.models.transformer import Transformer
get AttributeError: module 'tensorflow.contrib' has no attribute 'linalg'

### Environment information

```
OS: <MacOS 10.13.6>

$ pip freeze | grep tensor
```
mesh-tensorflow==0.0.4
tensor2tensor==1.11.0
tensorboard==1.12.0
tensorflow==1.12.0
tensorflow-metadata==0.9.0
tensorflow-probability==0.2.0
```
$ python -V
Python 3.6.6 :: Anaconda, Inc.

### For bugs: reproduction and error logs

```
# Steps to reproduce:
```
from tensor2tensor.models.transformer import Transformer
```
# Error logs:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-af77d4c1a477> in <module>()
----> 1 from tensor2tensor.models.transformer import Transformer

~/miniconda3/envs/prob/lib/python3.6/site-packages/tensor2tensor/models/__init__.py in <module>()
     20 # pylint: disable=unused-import
     21
---> 22 from tensor2tensor.layers import modalities  # pylint: disable=g-import-not-at-top
     23 from tensor2tensor.models import basic
     24 from tensor2tensor.models import bytenet

~/miniconda3/envs/prob/lib/python3.6/site-packages/tensor2tensor/layers/modalities.py in <module>()
     20 from six.moves import range  # pylint: disable=redefined-builtin
     21
---> 22 from tensor2tensor.layers import common_attention
     23 from tensor2tensor.layers import common_audio
     24 from tensor2tensor.layers import common_layers

~/miniconda3/envs/prob/lib/python3.6/site-packages/tensor2tensor/layers/common_attention.py in <module>()
     29 from six.moves import zip  # pylint: disable=redefined-builtin
     30
---> 31 from tensor2tensor.layers import common_layers
     32 from tensor2tensor.utils import expert_utils
     33

~/miniconda3/envs/prob/lib/python3.6/site-packages/tensor2tensor/layers/common_layers.py in <module>()
     30
     31 import tensorflow as tf
---> 32 import tensorflow_probability as tfp
     33
     34 from tensorflow.python.framework import function

~/.local/lib/python3.6/site-packages/tensorflow_probability/__init__.py in <module>()
     19
     20 # from tensorflow_probability.google import staging  # DisableOnExport
---> 21 from tensorflow_probability.python import *  # pylint: disable=wildcard-import

~/.local/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py in <module>()
     20
     21 from tensorflow_probability.python import bijectors
---> 22 from tensorflow_probability.python import distributions
     23 from tensorflow_probability.python import edward2
     24 from tensorflow_probability.python import glm

~/.local/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py in <module>()
     39 from tensorflow_probability.python.distributions.inverse_gamma import InverseGammaWithSoftplusConcentrationRate
     40 from tensorflow_probability.python.distributions.kumaraswamy import Kumaraswamy
---> 41 from tensorflow_probability.python.distributions.linear_gaussian_ssm import LinearGaussianStateSpaceModel
     42 from tensorflow_probability.python.distributions.logistic import Logistic
     43 from tensorflow_probability.python.distributions.lognormal import LogNormal

~/.local/lib/python3.6/site-packages/tensorflow_probability/python/distributions/linear_gaussian_ssm.py in <module>()
     32 from tensorflow.python.ops.linalg import linear_operator_util
     33
---> 34 tfl = tf.contrib.linalg
     35
     36 # The built-in tf.matmul doesn't broadcast batch dimensions, so we

~/miniconda3/envs/prob/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py in __getattr__(self, item)
     52   def __getattr__(self, item):
     53     module = self._load()
---> 54     return getattr(module, item)
     55
     56   def __dir__(self):

AttributeError: module 'tensorflow.contrib' has no attribute 'linalg'
```

**Comment by hogowl** [comment]
When import
from tensor2tensor.models.transformer import Transformer
get AttributeError: module 'tensorflow.contrib' has no attribute 'linalg'

**Comment by lgeiger** [comment]
Upgrading `tensorflow-probability` using `pip install tensorflow-probability -U` should fix your problem.

**Comment by tedivm** [comment]
Which versions of tensorflow-probably should work? I either get the error above, or this one-

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/uvicorn/workers.py", line 47, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/main.py", line 5, in <module>
    from callisto_t2t import serving_wrappers
  File "/usr/local/lib/python3.6/site-packages/callisto_t2t/__init__.py", line 3, in <module>
    from . import rad_hparams
  File "/usr/local/lib/python3.6/site-packages/callisto_t2t/rad_hparams.py", line 6, in <module>
    from tensor2tensor.models import transformer
  File "/usr/local/lib/python3.6/site-packages/tensor2tensor/models/__init__.py", line 54, in <module>
    from tensor2tensor.models.research import glow
  File "/usr/local/lib/python3.6/site-packages/tensor2tensor/models/research/glow.py", line 26, in <module>
    from tensor2tensor.models.research import glow_ops
  File "/usr/local/lib/python3.6/site-packages/tensor2tensor/models/research/glow_ops.py", line 100, in <module>
    class TemperedNormal(tfp.distributions.Normal):
AttributeError: module 'tensorflow_probability' has no attribute 'distributions'
```

**Comment by tijsmaas** [comment]
I ran into similar problems with another package, also depending on tensorflow_probability. Versions are not backwards compatible, it is needed to match the version exactly to the version of tensorflow. To find out which version you need, see https://github.com/tensorflow/probability/releases

Using another version than the newest can be done like so (for tensorflow==0.12.0):
`$  pip install tensorflow_probability==0.5.0`

**Comment by hogowl** [comment]
Now it works with nightly.
