### ISSUE TITLE
Token not found error

### ISSUE THREAD

**Issue by jamespinkerton** [tensorflow/tensor2tensor#135]
Hello. I'm trying to get the package to work, but having trouble.

**I ran the following commands:**

```
pip install tensor2tensor
conda install cudnn

PROBLEM=wmt_enfr_tokens_32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu

DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR
# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --num_shards=100 \
  --problem=$PROBLEM
```

**I got the following error:**

Traceback (most recent call last):
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/utils/trainer_utils.py", line 247, in run
    run_locally(exp_fn(output_dir))
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/utils/trainer_utils.py", line 132, in experiment_fn
    eval_steps=eval_steps)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/utils/trainer_utils.py", line 139, in create_experiment
    hparams = create_hparams(FLAGS.hparams_set, data_dir)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/utils/trainer_utils.py", line 216, in create_hparams
    for problem in FLAGS.problems.split("-")
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/utils/trainer_utils.py", line 216, in <listcomp>
    for problem in FLAGS.problems.split("-")
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/data_generators/problem_hparams.py", line 47, in problem_hparams
    p = _lookup_problem_hparams_fn(base_name)(model_hparams)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/data_generators/problem_hparams.py", line 712, in <lambda>
    "wmt_enfr_tokens_32k": lambda p: wmt_enfr_tokens(p, 2**15),
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/data_generators/problem_hparams.py", line 405, in wmt_enfr_tokens
    subtokenizer = text_encoder.SubwordTextEncoder(vocab_filename)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/data_generators/text_encoder.py", line 210, in __init__
    self._load_from_file(filename)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor/data_generators/text_encoder.py", line 454, in _load_from_file
    for line in f:
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 213, in __next__
    return self.next()
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 207, in next
    retval = self.readline()
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 176, in readline
    self._preread_check()
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/data/tokens.vocab.32768

**Comment by lukaszkaiser** [comment]
`File "/home/jamespinkerton/local/miniconda3/envs/tensor2tensor/bin/t2t-trainer", line 83`

Looks like you're running `t2t_trainer` instead of `t2t_datagen` here.

**Comment by jamespinkerton** [comment]
Thank you!
