### ISSUE TITLE
Universal_transformer._beam_decode lost 1 parameter

### ISSUE THREAD

**Issue by bigzt** [tensorflow/tensor2tensor#1353]
### Description

Hi, there. The universal_transformer._beam_decode lost 1 parameter: use_tpu. When using T2T-decoder, it will cause TypeError: _beam_decode() takes 6 positional arguments but 7 were given.

### For bugs: reproduction and error logs

```
# Steps to reproduce:
Use T2T-decoder to predict a universal transformer model.
```

```
# Error logs:
INFO:tensorflow:Setting hparams.dropout to 0.0
INFO:tensorflow:Setting hparams.label_smoothing to 0.0
INFO:tensorflow:Setting hparams.layer_prepostprocess_dropout to 0.0
INFO:tensorflow:Setting hparams.symbol_dropout to 0.0
INFO:tensorflow:Setting hparams.attention_dropout to 0.0
INFO:tensorflow:Setting hparams.relu_dropout to 0.0
INFO:tensorflow:Beam Decoding with beam size 4
Traceback (most recent call last):
  File "F:/tensorflow/project/huiming/t2t_decode.py", line 203, in <module>
    tf.app.run()
  File "F:\tensorflow\tf_env\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "F:/tensorflow/project/huiming/t2t_decode.py", line 198, in main
    decode(estimator, hp, decode_hp)
  File "F:/tensorflow/project/huiming/t2t_decode.py", line 98, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "F:\tensorflow\tf_env\lib\site-packages\tensor2tensor\utils\decoding.py", line 393, in decode_from_file
    for elapsed_time, result in timer(result_iter):
  File "F:\tensorflow\tf_env\lib\site-packages\tensor2tensor\utils\decoding.py", line 387, in timer
    item = next(gen)
  File "F:\tensorflow\tf_env\lib\site-packages\tensorflow\python\estimator\estimator.py", line 577, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "F:\tensorflow\tf_env\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "F:\tensorflow\tf_env\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 1264, in wrapping_model_fn
    use_tpu=use_tpu)
  File "F:\tensorflow\tf_env\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 1319, in estimator_model_fn
    return model.estimator_spec_predict(features, use_tpu=use_tpu)
  File "F:\tensorflow\tf_env\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 1521, in estimator_spec_predict
    use_tpu=use_tpu)
  File "F:\tensorflow\tf_env\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 691, in infer
    top_beams, alpha, use_tpu)
TypeError: _beam_decode() takes 6 positional arguments but 7 were given
```

**Comment by artitw** [comment]
Are you using the latest? This should have been fixed from https://github.com/tensorflow/tensor2tensor/pull/1290/commits/53be90565ab57040d7bacd240efcc2968116d529

**Comment by bigzt** [comment]
tensor2tensor 1.11.0 from pip.
I'll update it from the github.
