### ISSUE TITLE
Getting out of hbm memory error on TPU

### ISSUE THREAD

**Issue by ranjeethks** [tensorflow/tensor2tensor#1382]
### Description

Trying to train a language model - 

t2t-trainer --model=lstm_seq2seq --hparams_set=lstm_seq2seq --problem=languagemodel_lm1b8k_packed --train_steps=250000 --eval_steps=8 --data_dir=$DATA_DIR --output_dir=$OUT_DIR --use_tpu=True --cloud_tpu_name=$TPU_NAME --hparams='optimizer=Adafactor, weight_dtype=bfloat16, hidden_size=1024, batch_size=1024'

Getting the following error (copied imp stuffs only)
I tried to change the batch number. But no success. This is relatively a smaller model, 2 layer LSTM, 1024 hidden, 8k vocab (arguments take on 64 MB). But program takes more than 8 GB. Why is it so? Is there anyway I can use more than 1 TPU?

```

INFO:tensorflow:Error recorded from training_loop: Compilation failure: Ran out of memory in memory space hbm. Used 8.83G of 8.00G hbm. Exceeded hbm capacity by 848.88M.

Total hbm usage >= 8.83G:
    reserved        528.00M
    program           8.25G
    arguments        64.32M (99.9% utilization)

Output size 64.32M (99.9% utilization); shares 64.25M with arguments.

Program hbm requirement 8.25G:
    reserved           4.0K
    global            65.0K
    HLO temp          8.25G (100.0% utilization, 0.0% fragmentation (1.01M))

  Largest program allocations in hbm:

  1. Size: 4.00G
     Operator: op_name="XLA_Args"
     Shape: bf16[256,2048,4096]{2,1,0}
     Unpadded size: 4.00G
     XLA label: %arg_tuple.1996.1402 = (s32[], s32[], f32[], f32[4,1024]{1,0}, bf16[4,1024]{1,0}, f32[4,1024]{1,0}, bf16[4,1024]{1,0}, s32[4]{0}, s32[], s32[], f32[4,1024]{1,0}, f32[], bf16[], bf16[], s32[], bf16[2048,4096]{1,0}, bf16[4096]{0}, bf16[2048,4096]{1,0}, bf16[...
     Allocation type: HLO temp
     ==========================

  2. Size: 4.00G
     Shape: bf16[256,2048,4096]{2,1,0}
     Unpadded size: 4.00G
     XLA label: %arg_tuple.3500.0 = (s32[], f32[2048,4096]{1,0}, f32[4096]{0}, f32[2048,4096]{1,0}, f32[4096]{0}, s32[], f32[4,1024]{1,0}, f32[4,1024]{1,0}, f32[4,1024]{1,0}, f32[4,1024]{1,0}, bf16[], bf16[], bf16[], bf16[], (pred[256,4]{1,0}, s32[]), (bf16[256,4,1024]{2,...
     Allocation type: HLO temp
     ==========================

  3. Size: 32.06M
     Operator: op_type="Reshape" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/padded_cross_entropy/smoothing_cross_entropy/softmax_cross_entropy_with_logits/Reshape_1"
     Shape: f32[1024,8201]{0,1}
     Unpadded size: 32.04M
     Extra memory due to padding: 28.0K (1.0x expansion)
     XLA label: %reshape.101.remat4 = f32[1024,8201]{0,1} reshape(f32[4,256,1,1,8201]{1,0,4,2,3} %fusion.250.remat4), sharding={maximal device=0}, metadata={op_type="Reshape" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/padded_cross_entropy/smoothing_cross...
     Allocation type: HLO temp
     ==========================

  4. Size: 32.06M
     Operator: op_type="SoftmaxCrossEntropyWithLogits" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/padded_cross_entropy/smoothing_cross_entropy/softmax_cross_entropy_with_logits"
     Shape: f32[1024,8201]{0,1}
     Unpadded size: 32.04M
     Extra memory due to padding: 28.0K (1.0x expansion)
     XLA label: %fusion.247 = (f32[1024]{0}, f32[1024,8201]{0,1}) fusion(f32[1024]{0} %log.remat2, f32[1024,8201]{0,1} %reshape.101.remat4, f32[1024]{0} %reduce.5, bf16[1024,1024]{1,0} %bitcast.45, bf16[8201,1024]{1,0} %get-tuple-element.1637), kind=kOutput, calls=%fused_...
Allocation type: HLO temp
     ==========================

  5. Size: 32.06M
     Operator: op_type="MatMul" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/symbol_modality_8201_1024_1/softmax/MatMul"
     Shape: f32[1024,8201]{0,1}
     Unpadded size: 32.04M
     Extra memory due to padding: 28.0K (1.0x expansion)
     XLA label: %fusion.213.remat4.1.remat3 = f32[1024,8201]{0,1} fusion(bf16[1024,1024]{1,0} %bitcast.45, bf16[8201,1024]{1,0} %get-tuple-element.1637), kind=kOutput, calls=%fused_computation.200.clone.clone.clone.clone.1.clone.clone.clone, sharding={maximal device=0}, m...
     Allocation type: HLO temp
     ==========================


        TPU compilation failed
         [[{{node tpu_compile_succeeded_assert/_4879872842451564100/_21}} = TPUCompileSucceededAssert[_device="/job:worker/replica:0/task:0/device:CPU:0"](TPUReplicate/_compile/_14987246518586785693/_20)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node tpu_compile_succeeded_assert/_4879872842451564100/_21_G306}} = _Recv[client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:TPU:7", send_device="/job:worker/replica:0/task:0/device:CPU:0", send_device_incarnation=-5499342681075470468, tensor_name="edge_226_tpu_compile_succeeded_assert/_4879872842451564100/_21", tensor_type=DT_FLOAT, _device="/job:worker/replica:0/task:0/device:TPU:7"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
File "/usr/local/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 393, in main
    execute_schedule(exp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 349, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 438, in continuous_train_and_eval
    self._eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 637, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 647, in run_worker
    return self._start_distributed_training()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 788, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2409, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Compilation failure: Ran out of memory in memory space hbm. Used 8.83G of 8.00G hbm. Exceeded hbm capacity by 848.88M.

Total hbm usage >= 8.83G:
    reserved        528.00M
    program           8.25G
    arguments        64.32M (99.9% utilization)

Output size 64.32M (99.9% utilization); shares 64.25M with arguments.

Program hbm requirement 8.25G:
    reserved           4.0K
    global            65.0K
    HLO temp          8.25G (100.0% utilization, 0.0% fragmentation (1.01M))

  Largest program allocations in hbm:

  1. Size: 4.00G
     Operator: op_name="XLA_Args"
     Shape: bf16[256,2048,4096]{2,1,0}
     Unpadded size: 4.00G
     XLA label: %arg_tuple.1996.1402 = (s32[], s32[], f32[], f32[4,1024]{1,0}, bf16[4,1024]{1,0}, f32[4,1024]{1,0}, bf16[4,1024]{1,0}, s32[4]{0}, s32[], s32[], f32[4,1024]{1,0}, f32[], bf16[], bf16[], s32[], bf16[2048,4096]{1,0}, bf16[4096]{0}, bf16[2048,4096]{1,0}, bf16[...
     Allocation type: HLO temp
     ==========================

  2. Size: 4.00G
     Shape: bf16[256,2048,4096]{2,1,0}
     Unpadded size: 4.00G
     XLA label: %arg_tuple.3500.0 = (s32[], f32[2048,4096]{1,0}, f32[4096]{0}, f32[2048,4096]{1,0}, f32[4096]{0}, s32[], f32[4,1024]{1,0}, f32[4,1024]{1,0}, f32[4,1024]{1,0}, f32[4,1024]{1,0}, bf16[], bf16[], bf16[], bf16[], (pred[256,4]{1,0}, s32[]), (bf16[256,4,1024]{2,...
     Allocation type: HLO temp
     ==========================

  3. Size: 32.06M
     Operator: op_type="Reshape" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/padded_cross_entropy/smoothing_cross_entropy/softmax_cross_entropy_with_logits/Reshape_1"
     Shape: f32[1024,8201]{0,1}
     Unpadded size: 32.04M
     Extra memory due to padding: 28.0K (1.0x expansion)
     XLA label: %reshape.101.remat4 = f32[1024,8201]{0,1} reshape(f32[4,256,1,1,8201]{1,0,4,2,3} %fusion.250.remat4), sharding={maximal device=0}, metadata={op_type="Reshape" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/padded_cross_entropy/smoothing_cross...
     Allocation type: HLO temp
 ==========================

  4. Size: 32.06M
     Operator: op_type="SoftmaxCrossEntropyWithLogits" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/padded_cross_entropy/smoothing_cross_entropy/softmax_cross_entropy_with_logits"
     Shape: f32[1024,8201]{0,1}
     Unpadded size: 32.04M
     Extra memory due to padding: 28.0K (1.0x expansion)
     XLA label: %fusion.247 = (f32[1024]{0}, f32[1024,8201]{0,1}) fusion(f32[1024]{0} %log.remat2, f32[1024,8201]{0,1} %reshape.101.remat4, f32[1024]{0} %reduce.5, bf16[1024,1024]{1,0} %bitcast.45, bf16[8201,1024]{1,0} %get-tuple-element.1637), kind=kOutput, calls=%fused_...
     Allocation type: HLO temp
     ==========================

  5. Size: 32.06M
     Operator: op_type="MatMul" op_name="lstm_seq2seq/parallel_0_6/lstm_seq2seq/lstm_seq2seq/symbol_modality_8201_1024_1/softmax/MatMul"
     Shape: f32[1024,8201]{0,1}
     Unpadded size: 32.04M
     Extra memory due to padding: 28.0K (1.0x expansion)
     XLA label: %fusion.213.remat4.1.remat3 = f32[1024,8201]{0,1} fusion(bf16[1024,1024]{1,0} %bitcast.45, bf16[8201,1024]{1,0} %get-tuple-element.1637), kind=kOutput, calls=%fused_computation.200.clone.clone.clone.clone.1.clone.clone.clone, sharding={maximal device=0}, m...
     Allocation type: HLO temp
     ==========================


        TPU compilation failed
         [[{{node tpu_compile_succeeded_assert/_4879872842451564100/_21}} = TPUCompileSucceededAssert[_device="/job:worker/replica:0/task:0/device:CPU:0"](TPUReplicate/_compile/_14987246518586785693/_20)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node tpu_compile_succeeded_assert/_4879872842451564100/_21_G306}} = _Recv[client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:TPU:7", send_device="/job:worker/replica:0/task:0/device:CPU:0", send_device_incarnation=-5499342681075470468, tensor_name="edge_226_tpu_compile_succeeded_assert/_4879872842451564100/_21", tensor_type=DT_FLOAT, _device="/job:worker/replica:0/task:0/device:TPU:7"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```
### Environment information

```
OS: <Linux version 4.9.0-8-amd64 running on gcloud>

$ pip freeze | grep tensor
# mesh-tensorflow==0.0.5
tensor2tensor==1.12.0
tensorboard==1.12.0
tensorflow==1.12.0
tensorflow-metadata==0.9.0
tensorflow-probability==0.5.0

$ python -V
# Python 2.7.13
```

**Comment by ranjeethks** [comment]
Further to the above issue, if I reduce the hidden size to 512, it gets compiled and run successfully until step 3000, and then the following error gets displayed. Can you please help. Thanks. 
```
t2t-trainer --model=lstm_seq2seq --hparams_set=lstm_seq2seq --problem=languagemodel_lm1b8k_packed --train_steps=250000 --eval_steps=8 --data_dir=$DATA_DIR --output_dir=$OUT_DIR --use_tpu=True --cloud_tpu_name=$TPU_NAME --hparams='optimizer=Adafactor, weight_dtype=bfloat16, hidden_size=512, batch_size=1024'

```

```
INFO:tensorflow:Enqueue next (100) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (100) batch(es) of data from outfeed.
INFO:tensorflow:Saving checkpoints for 3000 into gs://quickstart-test2/training/8k/test/model.ckpt.
INFO:tensorflow:loss = 5.7068067, step = 3000 (17.763 sec)
INFO:tensorflow:global_step/sec: 5.62966
INFO:tensorflow:examples/sec: 180.149
INFO:tensorflow:Enqueue next (100) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (100) batch(es) of data from outfeed.
INFO:tensorflow:Error recorded from training_loop: Gradient for lstm_seq2seq/body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_0/lstm_cell/bias:0 is NaN : Tensor had NaN values
         [[node CheckNumerics_2 (defined at /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py:186)  = CheckNumerics[T=DT_BFLOAT16, message="Gradient f...s:0 is NaN", _device="/job:worker/replica:0/task:0/device:CPU:0"](Read_2/ReadVariableOp)]]

Caused by op u'CheckNumerics_2', defined at:
  File "/usr/local/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 393, in main
    execute_schedule(exp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 349, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 438, in continuous_train_and_eval
    self._eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 637, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 647, in run_worker
    return self._start_distributed_training()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 788, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn
    features, labels, mode, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2573, in _model_fn
    update_ops = _sync_variables_ops()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 186, in _sync_variables_ops
    for v in variables.trainable_variables()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 817, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Gradient for lstm_seq2seq/body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_0/lstm_cell/bias:0 is NaN : Tensor had NaN values
         [[node CheckNumerics_2 (defined at /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py:186)  = CheckNumerics[T=DT_BFLOAT16, message="Gradient f...s:0 is NaN", _device="/job:worker/replica:0/task:0/device:CPU:0"](Read_2/ReadVariableOp)]]

INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 393, in main
    execute_schedule(exp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 349, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 438, in continuous_train_and_eval
    self._eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 637, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 647, in run_worker
    return self._start_distributed_training()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 788, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2409, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Gradient for lstm_seq2seq/body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_0/lstm_cell/bias:0 is NaN : Tensor had NaN values
         [[node CheckNumerics_2 (defined at /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py:186)  = CheckNumerics[T=DT_BFLOAT16, message="Gradient f...s:0 is NaN", _device="/job:worker/replica:0/task:0/device:CPU:0"](Read_2/ReadVariableOp)]]

Caused by op u'CheckNumerics_2', defined at:
  File "/usr/local/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 393, in main
    execute_schedule(exp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 349, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 438, in continuous_train_and_eval
    self._eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 637, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 647, in run_worker
    return self._start_distributed_training()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 788, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn
    features, labels, mode, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2573, in _model_fn
update_ops = _sync_variables_ops()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 186, in _sync_variables_ops
    for v in variables.trainable_variables()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 817, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()
InvalidArgumentError (see above for traceback): Gradient for lstm_seq2seq/body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_0/lstm_cell/bias:0 is NaN : Tensor had NaN values
         [[node CheckNumerics_2 (defined at /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py:186)  = CheckNumerics[T=DT_BFLOAT16, message="Gradient f...s:0 is NaN", _device="/job:worker/replica:0/task:0/
device:CPU:0"](Read_2/ReadVariableOp)]]
```

**Comment by maggieezzat** [comment]
did you find any solution?

**Comment by ranjeethks** [comment]
Yes, all I had to do was to use v3-8 TPU. It offers 16 GB memory to hold the model and intermediate results.

**Comment by maggieezzat** [comment]
well you didn't find a way to use more than 1 tpu? Or any other way to solve the problem? I can't use v3-8 TPUs (only v2-8 are available to me)

**Comment by ranjeethks** [comment]
We need to used multiple cores, like v2-32, v2-64 etc. But they do not come with free credit $300. Need to upgrade the account to use multiple TPUs.

**Comment by andravin** [comment]
```
t2t-trainer --model=lstm_seq2seq\
 --hparams_set=lstm_seq2seq\
 --problem=languagemodel_lm1b8k_packed\
 --train_steps=250000 --eval_steps=8\
 --data_dir=$DATA_DIR --output_dir=$OUT_DIR --use_tpu=True\
 --cloud_tpu_name=$TPU_NAME\
 --hparams='optimizer=Adafactor, weight_dtype=bfloat16, hidden_size=1024, batch_size=1024'
```

@ranjeethks @maggieezzat what about using a smaller batch size? For example, try `batch_size=512` ?

**Comment by SR14** [comment]
v2-8 TPU has 64 GB, with 8 cores (i.e. shards)

You have to explicitly set the number of TPU cores (i.e. shards) to 8. 
Otherwise, it defaults to 1; which is why you only got 8 GB of memory.

**Comment by shizhediao** [comment]
> v2-8 TPU has 64 GB, with 8 cores (i.e. shards)
> 
> You have to explicitly set the number of TPU cores (i.e. shards) to 8.
> Otherwise, it defaults to 1; which is why you only got 8 GB of memory.

Hi, I was wondering how to set the number of TPU cores?
Thanks!

**Comment by wppply** [comment]
> > v2-8 TPU has 64 GB, with 8 cores (i.e. shards)
> > You have to explicitly set the number of TPU cores (i.e. shards) to 8.
> > Otherwise, it defaults to 1; which is why you only got 8 GB of memory.
> 
> Hi, I was wondering how to set the number of TPU cores?
> Thanks!

Do you figure it out? I am also trying to use the full memory but failed. it seems use only one (8GB) at all

**Comment by mrm8488** [comment]
Did you find any solution @wppply?

**Comment by wppply** [comment]
> Did you find any solution @wppply?

yes, the TPU is using 8 cores automatically. T2T has 8* batch size within code. And the 8GB is actually showing only the usage of single TPU. There is meaningless to show 8 of them, because they are always split into 8 evenly.
