### ISSUE TITLE
Failureon evaluation for small batch sizes.

### ISSUE THREAD

**Issue by EndingCredits** [tensorflow/tensor2tensor#140]
To replicate: `t2t-trainer --data_dir=t2t_data/ --problems=wmt_ende_tokens_32k --model=transformer --hparams_set=transformer_base --output_dir=train_dump/ --hparams='batch_size=64'`

Training starts fine, but when it comes to evaluation.
```
INFO:tensorflow:Starting evaluation at 2017-07-12-09:03:32
INFO:tensorflow:Restoring parameters from train_dump/model.ckpt-1564
2017-07-12 10:03:33.878706: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: TypeError: object of type 'numpy.int32' has no len()
2017-07-12 10:03:33.879347: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: TypeError: object of type 'numpy.int32' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib64/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: object of type 'numpy.int32' has no len()
	 [[Node: PyFunc = PyFunc[Tin=[DT_INT32, DT_INT32], Tout=[DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_1, Squeeze)]]

During handling of the above exception, another exception occurred:
```
Traceback is long, and not very illuminating, so I've omitted it, but let me know and I can share the whole thing.

Works fine for a batch-size of 256.

**Comment by lukaszkaiser** [comment]
Note that our `hparams.batch_size` (not `--decode_batch_size` though) is always divided by length! So if you set `batch_size=64` then you cannot decode sentences with more than `64` tokens and it fails. Should certainly give a better message though, we'd welcome a PR for that!
