### ISSUE TITLE
Issue when running lmptb_10k: Variable symbol_modality_10000_512/shared/weights_0 does not exist

### ISSUE THREAD

**Issue by lapolonio** [tensorflow/tensor2tensor#144]
When running lmptb_10k using the following config:
```
PROBLEM=lmptb_10k
MODEL=transformer
HPARAMS=transformer_base

DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --num_shards=100 \
  --problem=$PROBLEM

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR
```
The following error occurs:
```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/projects/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 240, in run
    run_locally(exp_fn(output_dir))
  File "/projects/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 532, in run_locally
    exp.train()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 955, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1162, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/projects/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 424, in model_fn
    len(hparams.problems) - 1)
  File "/projects/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 751, in _cond_on_index
    return fn(cur_idx)
  File "/projects/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 406, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "/projects/git/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 400, in model_fn
    sharded_features["targets"], dp)
  File "/projects/git/tensor2tensor/tensor2tensor/utils/modality.py", line 115, in targets_bottom_sharded
    return data_parallelism(self.targets_bottom, xs)
  File "/projects/git/tensor2tensor/tensor2tensor/utils/expert_utils.py", line 294, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/projects/git/tensor2tensor/tensor2tensor/models/modalities.py", line 94, in targets_bottom
    return self.bottom_simple(x, "shared", reuse=True)
  File "/projects/git/tensor2tensor/tensor2tensor/models/modalities.py", line 79, in bottom_simple
    var = self._get_weights()
  File "/projects/git/tensor2tensor/tensor2tensor/models/modalities.py", line 67, in _get_weights
    0.0, self._body_input_depth**-0.5)))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/projects/git/tensor2tensor/tensor2tensor/utils/expert_utils.py", line 260, in DaisyChainGetter
    var = getter(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable symbol_modality_10000_512/shared/weights_0 does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

**Comment by lukaszkaiser** [comment]
In `transformer_base` we share embeddings and softmax weights, which is not possible on PTB. Can you try `MODEL=attention_lm HPARAMS=attention_lm_small` instead?
