### ISSUE TITLE
Issue when running lmptb_10k: Tried to convert 'input' to a tensor and failed. Error: None values not supported.

### ISSUE THREAD

**Issue by lapolonio** [tensorflow/tensor2tensor#145]
When running lmptb_10k using the following config:

```
PROBLEM=lmptb_10k
MODEL=transformer
HPARAMS=basic_1

DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
NUM_SHARDS=3
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS-numshards$NUM_SHARDS

t2t-datagen \
--data_dir=$DATA_DIR \
--tmp_dir=$TMP_DIR \
--num_shards=$NUM_SHARDS \
--problem=$PROBLEM

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR
```

The following error occurs:
```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 240, in run
    run_locally(exp_fn(output_dir))
  File "/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 532, in run_locally
    exp.train()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 955, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1162, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 424, in model_fn
    len(hparams.problems) - 1)
  File "/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 751, in _cond_on_index
    return fn(cur_idx)
  File "/git/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 406, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "/git/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 408, in model_fn
    transformed_features)
  File "/git/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 457, in model_fn_body_sharded
    datashard_to_features)
  File "/git/tensor2tensor/tensor2tensor/utils/expert_utils.py", line 294, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/git/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 40, in fn_with_timing
    res = fn(*args, **kwargs)
  File "/git/tensor2tensor/tensor2tensor/models/transformer.py", line 53, in model_fn_body
    inputs = tf.squeeze(inputs, 2)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2281, in squeeze
    return gen_array_ops._squeeze(input, axis, name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3329, in _squeeze
    squeeze_dims=squeeze_dims, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 508, in apply_op
    (input_name, err))
ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.
```

**Comment by lukaszkaiser** [comment]
This combination will not work: `MODEL=transformer HPARAMS=basic_1`. Please use a `HPARAM` that's defined in `transformer.py`, e.g., `transformer_base`.
