### ISSUE TITLE
Dependency mismatch for Cloud ML Engine runtime 1.12

### ISSUE THREAD

**Issue by jvmancuso** [tensorflow/tensor2tensor#1472]
### Description
TensorFlow Probability has just released 0.6.0 to PyPI, which expects TF 1.13.1.  The current Runtime Version on Cloud ML Engine comes with TF 1.12.0.  Without either:
1. upgrading the default tensorflow version to 1.13.1 on ML Engine, or
2. downgrading the version of tensorflow-probability to 0.5.0,
jobs cannot currently be submitted to ML Engine.

FWIW, I already tried specifying both of these in the requirements.txt file of my t2t_usr_dir package with no change in error output, so I'm assuming these requirements.txt are superseded by the versions imposed by PyPI.

### Environment information
Cloud ML Engine Runtime Version 1.12

#### Steps to reproduce:
Submit any `t2t-trainer` job to Cloud ML Engine.

#### Error logs:
```
The replica master 0 exited with a non-zero status of 1. 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 24, in <module>
    from tensor2tensor import models  # pylint: disable=unused-import
  File "/root/.local/lib/python3.5/site-packages/tensor2tensor/models/__init__.py", line 25, in <module>
    from tensor2tensor.layers import modalities  # pylint: disable=g-import-not-at-top
  File "/root/.local/lib/python3.5/site-packages/tensor2tensor/layers/modalities.py", line 22, in <module>
    from tensor2tensor.layers import common_attention
  File "/root/.local/lib/python3.5/site-packages/tensor2tensor/layers/common_attention.py", line 31, in <module>
    from tensor2tensor.layers import common_layers
  File "/root/.local/lib/python3.5/site-packages/tensor2tensor/layers/common_layers.py", line 30, in <module>
    import tensorflow_probability as tfp
  File "/root/.local/lib/python3.5/site-packages/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/root/.local/lib/python3.5/site-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.13.1; Detected an installation of version 1.12.0. Please upgrade TensorFlow to proceed.
```

**Comment by jvmancuso** [comment]
Current workaround is to hardcode `tensorflow-probability==0.5.0` in `setup.py` and install tensor2tensor from source locally before sending the job to ML Engine.  Given no currently scheduled release date for runtime version 1.13 ML Engine, this isn't yet a satisfactory solution.

**Comment by mrmartin** [comment]
I resolved the issue on my local install with `pip install tensor2tensor==1.8.0`

**Comment by Roshanson** [comment]
you can also degrade the  TensorFlow Probability .   
In my case , set the version of TensorFlow Probability  from 0.7.0 to 0.6.0

**Comment by Next-Sunshine** [comment]
My Error:
ImportError: This version of TensorFlow Addons requires TensorFlow version >= 2.1.0; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.
I upgrade TensorFlow to 2.1.0, but it also shows the same error.

**Comment by andmek** [comment]
T2T: skipped importing 1 data_generators modules.
Did not import module: tensor2tensor.data_generators.moving_mnist; Cause: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0; Detected an installation of version 1.15.2. Please upgrade TensorFlow to proceed.
From module tensor2tensor.data_generators.moving_mnist
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/bin/t2t-datagen", line 18, in <module>
    from tensor2tensor.bin import t2t_datagen
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/bin/t2t_datagen.py", line 39, in <module>
    from tensor2tensor import problems as problems_lib  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/problems.py", line 33, in <module>
    all_problems.import_modules(all_problems.ALL_MODULES)
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/all_problems.py", line 143, in import_modules
    _handle_errors(errors)
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/all_problems.py", line 133, in _handle_errors
    raise err
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/all_problems.py", line 140, in import_modules
    importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/moving_mnist.py", line 39, in <module>
    import tensorflow_datasets as tfds
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/__init__.py", line 51, in <module>
    from tensorflow_datasets import __init__py3 as api
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/__init__py3.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/__init__.py", line 21, in <module>
    tf_compat.ensure_tf_install()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/tf_compat.py", line 59, in ensure_tf_install
    "This version of TensorFlow Datasets requires TensorFlow "
ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0; Detected an installation of version 1.15.2. Please upgrade TensorFlow to proceed.
