### ISSUE TITLE
Can serving use multiple gpus? about concurrent volume.

### ISSUE THREAD

**Issue by kudou1994** [tensorflow/tensor2tensor#1491]
### Description
I trained a NMT model, exported the model, and deployed a prediction service using nvidia-docker and ad-serving.At the same time, I sent 1,000 requests at the same time on the LAN to test the concurrency, but the test soon ran out of memory. OOM problems occur from time to time. How should solve excuse me?

### Environment information

```
OS: <Ubuntu16.04>

$ pip freeze | grep tensor
mesh-tensorflow==0.0.5
tensor2tensor==1.9.0
tensorboard==1.12.2
tensorflow-datasets==1.0.1
tensorflow-estimator==1.13.0
tensorflow-gpu==1.12.0
tensorflow-metadata==0.12.1
tensorflow-probability==0.5.0
tensorflow-serving-api==1.13.0

$ python -V
python 3.6
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
docker error
2019-03-15 09:55:57.234033: I external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 167201280 totalling 159.46MiB
2019-03-15 09:55:57.234047: I external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:641] 3 Chunks of size 167327232 totalling 478.73MiB
2019-03-15 09:55:57.234060: I external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 167453184 totalling 159.70MiB
2019-03-15 09:55:57.234074: I external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 10.16GiB
2019-03-15 09:55:57.234090: I external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats: 
Limit:                 10911298356
InUse:                 10911267584
MaxInUse:              10911295232
NumAllocs:                 9451313
MaxAllocSize:            167453184

2019-03-15 09:55:57.234435: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:271] ****************************************************************************************************
2019-03-15 09:55:57.234492: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at concat_op.cc:153 : Resource exhausted: OOM when allocating tensor with shape[31884,656] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

```

```
# Error logs:
test error
[2019-03-15 17:55:58,071] ERROR in app: Exception on /main [POST]
Traceback (most recent call last):
  File "/home/yyq/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yyq/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yyq/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yyq/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/yyq/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yyq/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "testFlask_fix.py", line 97, in main
    outputs = serving_utils.predict([input_1], problem, request_fn)
  File "/home/yyq/tensor2tensor/serving/serving_utils.py", line 157, in predict
    predictions = request_fn(examples)
  File "/home/yyq/tensor2tensor/serving/serving_utils.py", line 113, in _make_grpc_request
    response = stub.Predict(request, timeout_secs)
  File "/home/yyq/.local/lib/python3.6/site-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/yyq/.local/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "OOM when allocating tensor with shape[31932,656] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node transformer/symbol_modality_31932_656/parallel_0/symbol_modality_31932_656/input_emb/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
"
	debug_error_string = "{"created":"@1552643758.070673111","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"OOM when allocating tensor with shape[31932,656] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node transformer/symbol_modality_31932_656/parallel_0/symbol_modality_31932_656/input_emb/concat}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n","grpc_status":8}"
```

**Comment by kudou1994** [comment]
GPU: GTX1080ti *4
memory:64G
