### ISSUE TITLE
ImportError: cannot import name 'summary_op_util'

### ISSUE THREAD

**Issue by guotong1988** [tensorflow/tensor2tensor#1496]
Tensorflow version：
`1.13.1-cpu-windows`

Project git version:
`8d93b2eb65d30a36a1b14ba861fd2a3c59c56d0f`

Error log:
```
Traceback (most recent call last):
  File "C:/Users/gt/Desktop/tensor2tensor-master/tensor2tensor/bin/t2t_trainer.py", line 25, in <module>
    from tensor2tensor import models  # pylint: disable=unused-import
  File "C:\Users\gt\Desktop\tensor2tensor-master\tensor2tensor\models\__init__.py", line 58, in <module>
    from tensor2tensor.models.research import rl
  File "C:\Users\gt\Desktop\tensor2tensor-master\tensor2tensor\models\research\rl.py", line 31, in <module>
    from tensor2tensor.models.video import basic_deterministic_params
  File "C:\Users\gt\Desktop\tensor2tensor-master\tensor2tensor\models\video\basic_deterministic_params.py", line 22, in <module>
    from tensor2tensor.models.video import base
  File "C:\Users\gt\Desktop\tensor2tensor-master\tensor2tensor\models\video\base.py", line 27, in <module>
    from tensor2tensor.layers import common_video
  File "C:\Users\gt\Desktop\tensor2tensor-master\tensor2tensor\layers\common_video.py", line 27, in <module>
    from tensorflow.python.distribute import summary_op_util as distribute_summary_op_util  # pylint: disable=g-direct-tensorflow-import
ImportError: cannot import name 'summary_op_util'
```

**Comment by epurdy** [comment]
I'm also seeing this error.

**Comment by epurdy** [comment]
This is fixed in master.
