### ISSUE TITLE
Error in speech recognition training

### ISSUE THREAD

**Issue by manuel3265** [tensorflow/tensor2tensor#1573]
### Description

I do not know why this error occurs.

TypeError: __init__() got an unexpected keyword argument 'experimental_export_device_assignment'
...

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
mesh-tensorflow==0.0.5
tensor2tensor==1.13.4
tensorboard==1.12.0
tensorflow==1.13.1
tensorflow-datasets==1.0.2
tensorflow-estimator==1.13.0
tensorflow-metadata==0.13.0
tensorflow-probability==0.6.0
tensorflow-serving-api==1.12.0

$ python -V
Python 3.5.3
```

### For bugs: reproduction and error logs

```
t2t-trainer --model=transformer --hparams_set=transformer_librispeech_tpu --problem=librispeech --train_steps=210000 --eval_steps=3 --local_eval_frequency=100 --data_dir=$DATA --output_
dir=$OUT --use_tpu --cloud_tpu_name=$TPU_NAME 
...
```

```
# Error logs:
...
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
INFO:tensorflow:Importing user module manuel_garcia02 from path /home
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 398, in main
    exp = exp_fn(create_run_config(hparams), hparams)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/utils/trainer_lib.py", line 774, in experiment_fn
    return create_experiment(run_config, hparams, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/utils/trainer_lib.py", line 672, in create_experiment
    use_xla=use_xla)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/utils/trainer_lib.py", line 318, in create_estimator
    experimental_export_device_assignment=True)
TypeError: __init__() got an unexpected keyword argument 'experimental_export_device_assignment'
```

**Comment by bzz** [comment]
Experiencing the same error on a different problem with t2t `v1.13.2` on Cloab.

**Comment by manuel3265** [comment]
The solution is intall the tensor2tensor 1.13.2
