### ISSUE TITLE
serving/query.py 'tensorflow' has no attribute 'bytes'

### ISSUE THREAD

**Issue by JakubSido** [tensorflow/tensor2tensor#1611]
### Description
When using query.py from serving the following appears.
It looks like tensorflow' has no attribute 'bytes'. What does it mean? 

Traceback (most recent call last):
  File "C:/Program Files/Python37/Lib/site-packages/tensor2tensor/serving/query.py", line 119, in <module>
    tf.app.run()
  File "C:\Users\Jakub\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:/Program Files/Python37/Lib/site-packages/tensor2tensor/serving/query.py", line 90, in main
    outputs = serving_utils.predict([inputs], problem, request_fn)
  File "C:\Program Files\Python37\lib\site-packages\tensor2tensor\serving\serving_utils.py", line 159, in predict
    for input_ids in input_ids_list]
  File "C:\Program Files\Python37\lib\site-packages\tensor2tensor\serving\serving_utils.py", line 159, in <listcomp>
    for input_ids in input_ids_list]
  File "C:\Program Files\Python37\lib\site-packages\tensor2tensor\serving\serving_utils.py", line 75, in _make_example
    if ftype.dtype == tf.bytes:
AttributeError: module 'tensorflow' has no attribute 'bytes'

...
### Environment information
```
OS: win10


$ pip freeze | grep tensor
tensor2tensor==1.13.2
tensorboard==1.13.1
tensorflow-datasets==1.0.1
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
tensorflow-hub==0.4.0
tensorflow-metadata==0.13.0
tensorflow-probability==0.6.0
tensorflow-serving-api==1.13.0

$ python -V
Python 3.7.3
```

```
# Steps to reproduce:
run serving/query.py send >> "Hello world"

**Comment by manuel3265** [comment]
what model you trained?

**Comment by JakubSido** [comment]
It was transformer-encoder or seq2seq-encoder.

**Comment by RoeeRephraser** [comment]
Not sure that's the cause of this but query.py is Py2 only.
