### ISSUE TITLE
file fr_mono_en.txt not found

### ISSUE THREAD

**Issue by shadigit** [tensorflow/tensor2tensor#1647]
### Description
Hi,
Thank you for this wonderful platform. 
I was trying to test problem 
translate_enfr_wmt32k_with_backtranslate_fr
but found the error of 
t2t_datagen/fr_mono_en.txt; No such file or directory
it seems that these files are not downloaded.
### Environment information

```
OS: Ubuntu 18.04.2 LTS

$ pip freeze | grep tensor
# your output here
bert-tensorflow==1.0.1
mesh-tensorflow==0.0.5
tensor2tensor==1.13.4
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
tensorflow-hub==0.5.0
tensorflow-probability==0.7.0

$ python -V
# your output here
```
Python 2.7.15+ and Python 3.6.8
### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```
same as tutorial with the above problem
```
# Error logs:
...
Traceback (most recent call last):
  File "/usr/local/bin/t2t-datagen", line 28, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/bin/t2t-datagen", line 23, in main
    t2t_datagen.main(argv)
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/bin/t2t_datagen.py", line 216, in main
    generate_data_for_registered_problem(problem)
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/bin/t2t_datagen.py", line 301, in generate_data_for_registered_problem
    problem.generate_data(data_dir, tmp_dir, task_id)
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/text_problems.py", line 362, in generate_data
    self.generate_encoded_samples(data_dir, tmp_dir, split), paths)
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/generator_utils.py", line 166, in generate_files
    for case in generator:
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/text_problems.py", line 712, in text2text_generate_encoded
    for sample in sample_generator:
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/translate_enfr.py", line 193, in generate_samples
    for example in text_problems.text2text_txt_iterator(path1, path2):
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/text_problems.py", line 636, in text2text_txt_iterator
    txt_line_iterator(source_txt_path), txt_line_iterator(target_txt_path)):
  File "/usr/local/lib/python3.6/dist-packages/tensor2tensor/data_generators/text_problems.py", line 611, in txt_line_iterator
    for line in f:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 220, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 214, in next
    retval = self.readline()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 178, in readline
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /t2t_datagen/fr_mono_en.txt; No such file or directory

```

**Comment by martinpopel** [comment]
See the comment in the source code:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/translate_enfr.py#L164

You need to download some French monolingual data, e.g. from http://data.statmt.org/news-crawl/fr/
save this as `fr_mono_fr.txt`, train an FR->EN system, translate the data with this system and store the output as `fr_mono_en.txt`.
Yes, it does not work out of the box. Most probably you will want to parallelize the translation on multiple GPUs/TPUs/CPUs. Thus, it does not make sense to make this process fully automatic, using the same hardware for both training and decoding.

**Comment by shadigit** [comment]
right. Thank you very much. I'll do it.
