### ISSUE TITLE
problem translate translate_enes_wmt32k English-Spanish translation problem 

### ISSUE THREAD

**Issue by iamyihwa** [tensorflow/tensor2tensor#1653]
### Description

Hello! Thanks for adding en-es module and making it available! 

I have ran into an issue when I tried to download data using 't2t-datagen' command. 
It seems the data for translate_enes_wmt32k is not downloaded when using t2t-datagen command. 

It works when i use translate_ende_wmt32k.

Some part of the error message that I get clearly show that spanish module is not part of the available one at the moment.  (there is no enes module appearing where it should be since things seem to be ordered alphabetically.)

I have tried installing through 'pip install tensor2tensor' as well as 'pip install git+https://github.com/tensorflow/tensor2tensor.git' to check if the last changes were not reflected for the official release. 

### Environment information

```
OS: Linux

$ pip freeze | grep tensor
mesh-tensorflow==0.0.5
tensor2tensor==1.13.4
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-datasets==1.1.0
tensorflow-estimator==1.14.0
tensorflow-metadata==0.14.0
tensorflow-probability==0.7.0

$ python -V
Python 3.7.3

### For bugs: reproduction and error logs

```
# Steps to reproduce:

>export PROBLEM=translate_enes_wmt32k
> t2t-datagen --data_dir=$DATA_DIR --tmp_dir=$TMP_DIR --problem=$PROBLEM

In contrast, it works when I use english to german module for example by doing  
>export PROBLEM=translate_ende_wmt32k

# Error logs:

``` 

ValueError: You must specify one of the supported problems to generate data for:
  * algorithmic_addition_binary40
...

  * translate_ende_wmt_clean_pc_clean32k
  * translate_ende_wmt_multi64k
  * translate_ende_wmt_multi64k_packed1k
  * translate_ende_wmt_pc32k
  * translate_ende_wmt_pc_clean32k
  * translate_enet_wmt32k
  * translate_enet_wmt_characters
  * translate_enfr_wmt32k
```

**Comment by iamyihwa** [comment]
Hello @voluntadpear!  I have seen that you have trained the spanish part. Thanks ! 

Could I ask if it worked for you in following manner? 
I see that it is added to the master branch, but should I have downloaded a specific branch?
Any comment would be welcomed, thanks in advance!

**Comment by voluntadpear** [comment]
Hi @iamyihwa I didn't try it that way since I submitted the PR after I was able to use my problem definition for my training purposes.

I don't know the exact details with respect of the `t2t` releases but since it didn't work even after you used the code from the `master` branch, maybe there is a build step the maintainers have to make as part of the next release.

What you could do to try the spanish problem definition is copying the [translate_enes.py](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/translate_enes.py) file locally and use the [`--t2t_usr_dir` flag to load the problem](https://github.com/tensorflow/tensor2tensor#adding-your-own-components):

```bash
t2t-datagen --t2t_use_dir=$PROBLEM_DIR --data_dir=$DATA_DIR --tmp_dir=$TMP_DIR --problem=translate_enes_wmt32k
```

Good luck!

**Comment by iamyihwa** [comment]
Thanks @voluntadpear for the help! 
I just tried in the manner that you suggested. 
However I get the same error. 
(I have put the code translate_enes.py  in the PROBLEM_DIR, also i have tried both t2t_use_dir and t2t_usr_dir because the link that you reference to, and also your command  had both versions . ) 

> t2t-datagen --t2t_use_dir=$PROBLEM_DIR --data_dir=$DATA_DIR --tmp_dir=$TMP_DIR --problem=translate_enes_wmt32k
> t2t-datagen --t2t_usr_dir=$PROBLEM_DIR --data_dir=$DATA_DIR --tmp_dir=$TMP_DIR --problem=translate_enes_wmt32k


If you depend on functionality not listed there, please file an issue.

W0828 10:27:37.527163 140556880152384 deprecation_wrapper.py:119] From /home/ubuntu/anaconda3/envs/SpanishTranslate/lib/python3./site-packages/tensor2tensor/utils/expert_utils.py:68: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variabl_scope instead.

W0828 10:27:39.088318 140556880152384 deprecation_wrapper.py:119] From /home/ubuntu/anaconda3/envs/SpanishTranslate/lib/python3./site-packages/tensor2tensor/rl/gym_utils.py:219: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info istead.

W0828 10:27:39.092015 140556880152384 deprecation_wrapper.py:119] From /home/ubuntu/anaconda3/envs/SpanishTranslate/bin/t2t-dataen:27: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0828 10:27:39.092154 140556880152384 deprecation_wrapper.py:119] From /home/ubuntu/anaconda3/envs/SpanishTranslate/bin/t2t-dataen:27: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0828 10:27:39.092272 140556880152384 deprecation_wrapper.py:119] From /home/ubuntu/anaconda3/envs/SpanishTranslate/bin/t2t-dataen:28: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

I0828 10:27:39.092669 140556880152384 usr_dir.py:43] Importing user module t2t_problem from path /home/ubuntu/SpanishTranslate
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/SpanishTranslate/bin/t2t-datagen", line 28, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/SpanishTranslate/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, inrun
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ubuntu/anaconda3/envs/SpanishTranslate/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/SpanishTranslate/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/anaconda3/envs/SpanishTranslate/bin/t2t-datagen", line 23, in main
    t2t_datagen.main(argv)
  File "/home/ubuntu/anaconda3/envs/SpanishTranslate/lib/python3.7/site-packages/tensor2tensor/bin/t2t_datagen.py", line 196, inmain
    raise ValueError(error_msg)
ValueError: You must specify one of the supported problems to generate data for:

**Comment by voluntadpear** [comment]
@iamyihwa I think you also need to have a `__init__.py` file in the `PROBLEM_DIR` like they show in this example: [https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/test_data/example_usr_dir](https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/test_data/example_usr_dir)

And `PROBLEM_DIR` should point to the directory containing the file and not the file itself.
