### ISSUE TITLE
cannot import name 'loas2'

### ISSUE THREAD

**Issue by KyunghyunLee** [tensorflow/tensor2tensor#1663]
### Description
I am trying to run `rl/trainer_model_based.py`. 
I run the example command in the file and got the error at line 24 of `env/client_env.py`. 
`from grpc import loas2`

I tried several version of grpc in case of library change, but not succeed. 

### Environment information

```
OS: ubuntu 16.04

$ pip freeze | grep tensor
mesh-tensorflow==0.0.5
-e git+https://github.com/tensorflow/tensor2tensor@33783fd63bd0debe2138c5569698b31d9af350f6#egg=tensor2tensor
tensorboard==1.14.0
tensorflow-datasets==1.1.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
tensorflow-metadata==0.14.0
tensorflow-probability==0.7.0

$ python -V
Python 3.6.9 :: Anaconda, Inc.
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:

python -m tensor2tensor.rl.trainer_model_based \
    --output_dir=$HOME/t2t/rl_v1 \
    --loop_hparams_set=rlmb_base \
    --loop_hparams='num_real_env_frames=10000,epochs=3'

(same as the Example invocation in trainer_model_based.py)
```
```
# Error logs:
WARNING: Logging before flag parsing goes to stderr.
W0816 23:41:59.412693 139681197864704 deprecation_wrapper.py:119] From /home/lkh/Codes/tensor2tensor/tensor2tensor/utils/expert_utils.py:68: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0816 23:42:00.307283 139681197864704 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0816 23:42:03.780892 139681197864704 deprecation_wrapper.py:119] From /home/lkh/Codes/tensor2tensor/tensor2tensor/utils/adafactor.py:27: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0816 23:42:03.782154 139681197864704 deprecation_wrapper.py:119] From /home/lkh/Codes/tensor2tensor/tensor2tensor/utils/multistep_optimizer.py:32: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

W0816 23:42:03.838312 139681197864704 deprecation_wrapper.py:119] From /home/lkh/anaconda3/envs/cule/lib/python3.6/site-packages/mesh_tensorflow/ops.py:4237: The name tf.train.CheckpointSaverListener is deprecated. Please use tf.estimator.CheckpointSaverListener instead.

W0816 23:42:03.838605 139681197864704 deprecation_wrapper.py:119] From /home/lkh/anaconda3/envs/cule/lib/python3.6/site-packages/mesh_tensorflow/ops.py:4260: The name tf.train.SessionRunHook is deprecated. Please use tf.estimator.SessionRunHook instead.

W0816 23:42:03.916944 139681197864704 deprecation_wrapper.py:119] From /home/lkh/Codes/tensor2tensor/tensor2tensor/models/research/neural_stack.py:38: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Traceback (most recent call last):
  File "/home/lkh/Downloads/pycharm-community-2018.2.5/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/lkh/Downloads/pycharm-community-2018.2.5/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/lkh/Downloads/pycharm-community-2018.2.5/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lkh/Downloads/pycharm-community-2018.2.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lkh/Codes/tensor2tensor/tensor2tensor/rl/trainer_model_based.py", line 38, in <module>
    from tensor2tensor.bin import t2t_trainer  # pylint: disable=unused-import
  File "/home/lkh/Codes/tensor2tensor/tensor2tensor/bin/t2t_trainer.py", line 24, in <module>
    from tensor2tensor import models  # pylint: disable=unused-import
  File "/home/lkh/Codes/tensor2tensor/tensor2tensor/models/__init__.py", line 61, in <module>
    from tensor2tensor.models.research import rl
  File "/home/lkh/Codes/tensor2tensor/tensor2tensor/models/research/rl.py", line 27, in <module>
    from tensor2tensor.envs import tic_tac_toe_env
  File "/home/lkh/Codes/tensor2tensor/tensor2tensor/envs/__init__.py", line 24, in <module>
    from tensor2tensor.envs import client_env
  File "/home/lkh/Codes/tensor2tensor/tensor2tensor/envs/client_env.py", line 24, in <module>
    from grpc import loas2
ImportError: cannot import name 'loas2'
We've got an error while stopping in post-mortem: <class 'KeyboardInterrupt'>
```

**Comment by mschonwe** [comment]
FYI, There was a gitter discussion about this:
>@lukaszkaiser Aug 16 13:18
>This looks like an installation and dependencies issue. I already see the bug with not exporting config files. Will correct that and try to make a fresh release next week (still a few tests to investigate for that).

(from: https://news.ycombinator.com/item?id=17574361): 
>LOAS is how Stubby (gRPC) connections on the Google internal network are secured, looks a bit like mTLS and is partially being open sourced as ALTS: https://cloud.google.com/security/encryption-in-transit/application-layer-transport-security/

**Comment by sahajgarg** [comment]
In the meantime, I was able to run the code by reverting to an earlier commit
