### ISSUE TITLE
Transformer-XL gets unhappy with unexpected batch sizes

### ISSUE THREAD

**Issue by tomweingarten** [tensorflow/tensor2tensor#1707]
### Description

When training a Transformer-xl (model: transformer_memory, hyperparameters:transformer_wikitext103_l4k_memory_v0), if the transformer encounters an unexpected batch size, it halts training. At least, I think that's what's happening. When I set the max_length=batch_size, and choose max_length so that every example fits exactly one batch, this error goes away.

### Environment information

```
OS: Ubuntu 18

$ pip freeze | grep tensor
mesh-tensorflow==0.0.5
tensor2tensor==1.14.0
tensorboard==1.14.0
tensorflow-datasets==1.2.0
tensorflow-estimator==1.14.0
tensorflow-gan==1.0.0.dev0
tensorflow-gpu==1.14.0
tensorflow-metadata==0.14.0
tensorflow-model-optimization==0.1.3
tensorflow-probability==0.7.0

$ python -V
Python 2.7.16
$ python3 -V
Python 3.7.3

Error happens in both Python2 and Python3. I haven't tried with TF2 yet.
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
I fed in a new Problem with sequence length between 2k-3k tokens. I set the max_length and batch_size to 5k. Received the Traceback below.
```

```
# Error logs:
Traceback (most recent call last):
  File "/home/tom/.local/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/tom/.local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/tom/.local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/tom/.local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 412, in main
    execute_schedule(exp)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 367, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 456, in continuous_train_and_eval
    self._eval_spec)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1192, in _train_model_default
    saving_listeners)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1484, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [2,64,256] vs. shape[1] = [3,64,256]
	 [[node transformer_memory/parallel_0_5/transformer_memory/transformer_memory/body/decoder/layer_0/self_attention/multihead_attention/concat (defined at home/tom/.local/lib/python2.7/site-packages/tensor2tensor/layers/transformer_memory.py:137) ]]
	 [[transformer_memory/parallel_0_5/transformer_memory/transformer_memory/body/decoder/layer_7/self_attention/multihead_attention/Pad/_2497]]
  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [2,64,256] vs. shape[1] = [3,64,256]
```

**Comment by tomweingarten** [comment]
I'm not actually sure I should be setting the batch_size at all, but if I don't set it I get an ambiguous dimension error: Traceback (most recent call last):
  File "/home/tom/.local/bin/t2t-decoder", line 17, in <module>
    tf.app.run()
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/tom/.local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/tom/.local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/tom/.local/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 205, in main
    decode(estimator, hp, decode_hp)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 94, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/utils/decoding.py", line 474, in decode_from_file
    for elapsed_time, result in timer(result_iter):
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/utils/decoding.py", line 468, in timer
    item = next(gen)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 619, in predict
    features, None, ModeKeys.PREDICT, self.config)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 1415, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 1458, in estimator_model_fn
    _reuse=reuse)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/models/transformer.py", line 1705, in __init__
    layer_name + "/recurrent_memory", hparams)
  File "/home/tom/.local/lib/python2.7/site-packages/tensor2tensor/layers/transformer_memory.py", line 96, in __init__
    initializer=tf.constant_initializer(0))
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1496, in get_variable
    aggregation=aggregation)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1239, in get_variable
    aggregation=aggregation)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 562, in get_variable
    aggregation=aggregation)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 514, in _true_getter
    aggregation=aggregation)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 845, in _get_single_variable
    shape = tensor_shape.as_shape(shape)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1204, in as_shape
    return TensorShape(shape)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 774, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 716, in as_dimension
    return Dimension(value)
  File "/home/tom/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 188, in __init__
    raise ValueError("Ambiguous dimension: %s" % value)
ValueError: Ambiguous dimension: 87.3813333333

Setting batch_size=max_length, or setting max_length to 4096 resolves this issue.
