### ISSUE TITLE
Restore world model error

### ISSUE THREAD

**Issue by ZaneH1992** [tensorflow/tensor2tensor#1713]
### Description

I have trained a world model of GYM breakout game, but I can't restore it afterwards due to some kind of key missing error.Also there is a [attribute '_video_writer' not found error] during training and restoring prpcess. I didn't change any code.

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
mesh-tensorflow==0.0.5
tensor2tensor==1.13.1
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-datasets==1.2.0
tensorflow-estimator==1.13.0
tensorflow-gan==1.0.0.dev0
tensorflow-gpu==1.13.1
tensorflow-metadata==0.14.0
tensorflow-probability==0.6.0

$ python -V
Python 3.6.8

### For bugs: reproduction and error logs
...
```
# Steps to reproduce:
...
```
python -m tensor2tensor.rl.player \
  --wm_dir=/home/issme/t2t_train/mb_det_breakout_random/world_model \
  --loop_hparams_set=rlmb_base_stochastic_discrete \
  --loop_hparams=game=breakout \
  --game_from_filenames=False \
  --zoom=3 \
  --fps=5
```
# Error logs:
...
```
INFO:tensorflow:Restoring parameters from /home/issme/t2t_train/mb_det_breakout_random/world_model/model.ckpt-45000
2019-09-25 11:08:52.655536: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key next_frame_basic_stochastic_discrete/body/action_enc_add/bias not found in checkpoint
Traceback (most recent call last):
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key next_frame_basic_stochastic_discrete/body/action_enc_add/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key next_frame_basic_stochastic_discrete/body/action_enc_add/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]

Caused by op 'save/RestoreV2', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 541, in <module>
    tf.app.run()
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 514, in main
    which_epoch_data=None, setable_initial_frames=True)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 509, in make_simulated_env
    setable_initial_frames=setable_initial_frames)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player_utils.py", line 185, in load_data_and_make_simulated_env
    setable_initial_frames=setable_initial_frames)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player_utils.py", line 99, in __init__
    env = env_fn(in_graph=False)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/models/research/rl.py", line 236, in env_fn
    return class_(**env_kwargs)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_gym_env.py", line 68, in __init__
    self._batch_env.initialize(self._sess)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py", line 163, in initialize
    var_list=tf.global_variables(scope="next_frame*")  # pylint:disable=unexpected-keyword-arg
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key next_frame_basic_stochastic_discrete/body/action_enc_add/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1591, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 541, in <module>
    tf.app.run()
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 514, in main
    which_epoch_data=None, setable_initial_frames=True)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 509, in make_simulated_env
    setable_initial_frames=setable_initial_frames)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player_utils.py", line 185, in load_data_and_make_simulated_env
    setable_initial_frames=setable_initial_frames)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player_utils.py", line 99, in __init__
    env = env_fn(in_graph=False)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/models/research/rl.py", line 236, in env_fn
    return class_(**env_kwargs)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_gym_env.py", line 68, in __init__
    self._batch_env.initialize(self._sess)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py", line 167, in initialize
    self._model_dir, saver=model_loader, sess=sess, must_restore=True
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/utils/trainer_lib.py", line 792, in restore_checkpoint
    saver.restore(sess, path)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key next_frame_basic_stochastic_discrete/body/action_enc_add/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]

Caused by op 'save/RestoreV2', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 541, in <module>
    tf.app.run()
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 514, in main
    which_epoch_data=None, setable_initial_frames=True)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player.py", line 509, in make_simulated_env
    setable_initial_frames=setable_initial_frames)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player_utils.py", line 185, in load_data_and_make_simulated_env
    setable_initial_frames=setable_initial_frames)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/player_utils.py", line 99, in __init__
    env = env_fn(in_graph=False)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/models/research/rl.py", line 236, in env_fn
    return class_(**env_kwargs)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_gym_env.py", line 68, in __init__
    self._batch_env.initialize(self._sess)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py", line 163, in initialize
    var_list=tf.global_variables(scope="next_frame*")  # pylint:disable=unexpected-keyword-arg
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key next_frame_basic_stochastic_discrete/body/action_enc_add/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]
	 [[node save/RestoreV2 (defined at /home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py:163) ]]

Exception ignored in: <bound method SimulatedBatchEnv.__del__ of <tensor2tensor.rl.envs.simulated_batch_env.SimulatedBatchEnv object at 0x7f354fb38518>>
Traceback (most recent call last):
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py", line 298, in __del__
  File "/home/issme/env-tf1.13.1-PRL/lib/python3.6/site-packages/tensor2tensor/rl/envs/simulated_batch_env.py", line 293, in _video_reset_writer
AttributeError: 'SimulatedBatchEnv' object has no attribute '_video_writer'

**Comment by Jthon** [comment]
I have the same error... Could you please tell me how to solve it? Thanks!
