### ISSUE TITLE
File Not Found: gs://tensor2tensor-data/wikisum/commoncrawl_metadata/xxx.metadata.json

### ISSUE THREAD

**Issue by EddieChuang** [tensorflow/tensor2tensor#1765]
### Description
I tried to download the **wikisum** dataset used in the paper GENERATING WIKIPEDIA BY SUMMARIZING LONG SEQUENCES and wanted to use my own computer to do it instead of GCP. I executed the following command:
```
python get_references_commoncrawl.py --out_dir wikisum_commoncrawl
```
and I got this error:
```
tensorflow.python.framework.errors_impl.NotFoundError: The specified path gs://tensor2tensor-data/wikisum/commoncrawl_metadata/CC-MAIN-20170919112242-20170919132242-00000.warc.wet.gz'.metadata.json was not found.
```
Is **wikisum** dataset still available?
Is there any other way to download the full dataset instead of crawling it?
Thanks for your great works.

### Environment information

```
OS: Ubuntu 18.04.1 LST

$ pip freeze | grep tensor
mesh-tensorflow==0.1.7
tensor2tensor==1.15.2
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-datasets==1.3.2
tensorflow-estimator==1.14.0
tensorflow-gan==2.0.0
tensorflow-hub==0.7.0
tensorflow-metadata==0.15.1
tensorflow-probability==0.7.0

$ python -V
Python 3.6.9 :: Anaconda, Inc.
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
$ git clone https://github.com/tensorflow/tensor2tensor.git
$ cd tensor2tensor-master/tensor2tensor/data_generators/wikisum
$ python get_references_commoncrawl.py --out_dir wikisum_commoncrawl
```

```
# Error logs:
Traceback (most recent call last):
  File "get_references_commoncrawl.py", line 71, in <module>
    tf.app.run()
  File "/home/chiamin/anaconda3/envs/wikisum/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/chiamin/anaconda3/envs/wikisum/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/chiamin/anaconda3/envs/wikisum/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "get_references_commoncrawl.py", line 66, in main
    wikisum.extract_references_from_wets(wet_files, FLAGS.metadata_dir, out_dir)
  File "/home/chiamin/.local/lib/python3.6/site-packages/tensor2tensor/data_generators/wikisum/wikisum.py", line 521, in extract_references_from_wets
    wet_metadata = json.loads(f.read())
  File "/home/chiamin/anaconda3/envs/wikisum/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 124, in read
    length = self.size() - self.tell()
  File "/home/chiamin/anaconda3/envs/wikisum/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 102, in size
    return stat(self.__name).length
  File "/home/chiamin/anaconda3/envs/wikisum/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 727, in stat
    return stat_v2(filename)
  File "/home/chiamin/anaconda3/envs/wikisum/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 744, in stat_v2
    pywrap_tensorflow.Stat(compat.as_bytes(path), file_statistics)
tensorflow.python.framework.errors_impl.NotFoundError: The specified path gs://tensor2tensor-data/wikisum/commoncrawl_metadata/CC-MAIN-20170919112242-20170919132242-00000.warc.wet.gz'.metadata.json was not found.

```

**Comment by martinpopel** [comment]
Try accessing the file from Google Colab. If it is available (I cannot check it now), upload the file to your Google Drive (there are tutorials how to do it) and from there you can download it to your machine.

**Comment by EddieChuang** [comment]
Thanks for your prompt response. I will try it.
