### ISSUE TITLE
ImportError: No module named 'cPickle'， however,  cPickle is obsolete。。。

### ISSUE THREAD

**Issue by loveJasmine** [tensorflow/tensor2tensor#18]
$t2t-datagen   --data_dir=$DATA_DIR   --tmp_dir=$TMP_DIR   --num_shards=100   --problem=$PROBLEM
Traceback (most recent call last):
  File "/home/yike.yk/tf1.2py3_venv/venv/bin/t2t-datagen", line 39, in <module>
    from tensor2tensor.data_generators import image
  File "/home/yike.yk/tf1.2py3_venv/venv/lib/python3.6/site-packages/tensor2tensor/data_generators/image.py", line 21, in <module>
    import cPickle
ImportError: No module named 'cPickle'

**Comment by lukaszkaiser** [comment]
Thanks for pointing this out! Would you like to help and make a PR that solves it?

**Comment by loveJasmine** [comment]
I had this issue solved, but I think maybe  https://github.com/tensorflow/tensor2tensor/issues/2 is also on going...
