### ISSUE TITLE
LM1B_32k exception

### ISSUE THREAD

**Issue by fminkin** [tensorflow/tensor2tensor#186]
I've encountered an exception when launching lm1b_32 problem with following config:

PROBLEM=lm1b_32k
MODEL=atttention_lm_moe
HPARAMS=attention_lm_moe_small

After it's done downloading the data and preparations with outputs like this:

INFO:tensorflow:filepath = /home/f-minkin/t2t_datagen/1-billion-word-language-modeling-benchmark-r13output/training-monolingual.tokenized.shuffled/news.en-00099-of-00100
INFO:tensorflow:Generating case 30000000.
INFO:tensorflow:Generating case 30100000.
INFO:tensorflow:Generating case 30200000.
INFO:tensorflow:Generating case 30300000.
INFO:tensorflow:Generating development data for lm1b_32k.
INFO:tensorflow:filepath = /home/f-minkin/t2t_datagen/1-billion-word-language-modeling-benchmark-r13output/heldout-monolingual.tokenized.shuffled/news.en.heldout-00000-of-00050
INFO:tensorflow:Shuffling data...
INFO:tensorflow:Shuffling data...
INFO:tensorflow:read: 100000
INFO:tensorflow:read: 200000
INFO:tensorflow:read: 300000
INFO:tensorflow:write: 100000

After a while it falls with exception:

> Traceback (most recent call last):
  File "/home/f-minkin/.pyenv/versions/tf/bin/t2t-trainer", line 81, in <module>
    tf.app.run()
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/f-minkin/.pyenv/versions/tf/bin/t2t-trainer", line 77, in main
    schedule=FLAGS.schedule)
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 266, in run
    run_locally(exp_fn(output_dir))
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 145, in experiment_fn
    eval_steps=eval_steps)
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 152, in create_experiment
    hparams = create_hparams(FLAGS.hparams_set, data_dir)
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 234, in create_hparams
    p_hparams = problem_hparams.problem_hparams(problem_name, hparams)
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/data_generators/problem_hparams.py", line 47, in problem_hparams
    p = _lookup_problem_hparams_fn(base_name)(model_hparams)
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/data_generators/problem_hparams.py", line 326, in lm1b_32k
    os.path.join(model_hparams.data_dir, "lm1b_32k.subword_text_encoder"))
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 238, in __init__
    self._load_from_file(filename)
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 484, in _load_from_file
    for line in f:
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 207, in next
    retval = self.readline()
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 176, in readline
    self._preread_check()
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/f-minkin/.pyenv/versions/2.7.13/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/f-minkin/.pyenv/versions/2.7.13/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/f-minkin/tensor2tensor/t2t_data/lm1b_32k.subword_text_encoder

Any way to fix this?

**Comment by lukaszkaiser** [comment]
Oh, probably the file `lm1b_32k.subword_text_encoder` is in your $TMP_DIR and we forgot to copy it to $DATA_DIR. For now, please just copy it yourself, I'll check to add that to the code.

**Comment by fminkin** [comment]
thanks, it's working

**Comment by lukaszkaiser** [comment]
Great to hear that, thanks!
