### ISSUE TITLE
tutorial fails with latest release 1.1.2 because of wrong encoding for python3

### ISSUE THREAD

**Issue by fac2003** [tensorflow/tensor2tensor#187]
Running the tutorial with python3, I get:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/t2t-datagen", line 41, in <module>
    from tensor2tensor.data_generators import all_problems  # pylint: disable=unused-import
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensor2tensor/data_generators/all_problems.py", line 22, in <module>
    from tensor2tensor.data_generators import algorithmic
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensor2tensor/data_generators/algorithmic.py", line 27, in <module>
    from tensor2tensor.data_generators import generator_utils as utils
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensor2tensor/data_generators/generator_utils.py", line 35, in <module>
    from tensor2tensor.data_generators import text_encoder
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensor2tensor/data_generators/text_encoder.py", line 56
    _UNESCAPE_REGEX = re.compile(ur"\\u|\\\\|\\([0-9]+);")

This can be fixed by removing the u in front of the regexp. Python3 does not support it. 

Note that there is another spot with the same problem:

    from tensor2tensor.data_generators import text_encoder
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensor2tensor/data_generators/text_encoder.py", line 222
    c if c in alphabet and c != u"\n" else ur"\%d;" % ord(c)

Remove u in front of ur"\%d will solve this.

**Comment by rsepassi** [comment]
Fixed in 1.1.3! Sorry about that.

**Comment by lukaszkaiser** [comment]
Of course please reopen if you see any other problem in 1.1.3!

**Comment by colmantse** [comment]
running the tutorial t2t-trainer i got the following

Traceback (most recent call last):
  File "t2t-trainer", line 82, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "t2t-trainer", line 78, in main
    schedule=FLAGS.schedule)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 284, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 665, in _call_train
    monitors=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 955, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1162, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\model_builder.py", line 218, in model_fn
    len(my_hp.problems) - 1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\input_fn_builder.py", line 200, in cond_on_index
    return fn(cur_idx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\model_builder.py", line 198, in nth_model
    for loss_key, loss_value in losses_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by lukaszkaiser** [comment]
This was a python3 problem, already corrected in PR #210. We're in the process of adding automated tests for python3, that should prevent it from happening again. I'm closing this as it's already solved on master (will make a release tomorrow). Thanks for reporting!

**Comment by colmantse** [comment]
ah i saw the merge request, i thought it is already updated. so it will be fixed if i pull the master again tomorrow? thanks!

**Comment by lukaszkaiser** [comment]
Should be fixed if you pull the master now :). (Just remember to do `pip install -e .` in your pulled repo and/or `pip uninstall tensor2tensor` so your python will use your downloaded repo and not the pip release which wasn't updated yet.)

**Comment by colmantse** [comment]
that will require administrator privilege i assume?

Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_uninstall.py", line 117, in remove
    pth.remove()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_uninstall.py", line 183, in remove
    with open(self.file, 'wb') as fh:
PermissionError: [Errno 13] Permission denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\easy-install.pth'

**Comment by colmantse** [comment]
thanks i think i got it running now !!
