### ISSUE TITLE
not the same tf.Graph() issue when decoding the en-de NMT model

### ISSUE THREAD

**Issue by liuliu8622** [tensorflow/tensor2tensor#1873]
### Description
following the Walkthrough shown in the front page, I trained a en-de NMT transformer for evalling. but got a error while decoding them.

### Environment information

```
OS: Ubuntu Server 18.04.5 LTS

python 3.7.0

tensorflow-gpu 2.3.1

tensor2tensor 1.15.7
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
PROBLEM=translate_ende_wmt32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu
DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS
mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problem=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR

DECODE_FILE=$DATA_DIR/decode_this.txt
echo "Hello world" >> $DECODE_FILE
echo "Goodbye world" >> $DECODE_FILE
echo -e 'Hallo Welt\nAuf Wiedersehen Welt' > ref-translation.de

BEAM_SIZE=4
ALPHA=0.6

t2t-decoder \
  --data_dir=$DATA_DIR \
  --problem=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --decode_hparams="beam_size=$BEAM_SIZE,alpha=$ALPHA" \
  --decode_from_file=$DECODE_FILE \
  --decode_to_file=translation.en
```

```
# Error logs:
INFO:tensorflow:Loading hparams from existing json /home/caiy/nmt/onmt/en_de/t2t_train/translate_ende_wmt32k/transformer-transformer_base_single_gpu/hparams.json
INFO:tensorflow:Configuring DataParallelism to replicate the model.
INFO:tensorflow:schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
INFO:tensorflow:sync=False
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
INFO:tensorflow:Using config: {'_model_dir': '/home/caiy/nmt/onmt/en_de/t2t_train/translate_ende_wmt32k/transformer-transformer_base_single_gpu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
    global_jit_level: OFF
  }
}
isolate_session_state: true
, '_keep_checkpoint_max': 20, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, 'use_tpu': False, 't2t_device_info': {'num_async_replicas': 1}, 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f1348bad358>}
INFO:tensorflow:decode_hp.batch_size not specified; default=32
INFO:tensorflow:Performing decoding from file (/home/caiy/nmt/onmt/en_de/t2t_data/decode_this.txt).
INFO:tensorflow:Getting sorted inputs
INFO:tensorflow: batch 1
INFO:tensorflow:Decoding batch 0
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Setting T2TModel mode to 'infer'
INFO:tensorflow:Setting hparams.dropout to 0.0
INFO:tensorflow:Setting hparams.label_smoothing to 0.0
INFO:tensorflow:Setting hparams.layer_prepostprocess_dropout to 0.0
INFO:tensorflow:Setting hparams.symbol_dropout to 0.0
INFO:tensorflow:Setting hparams.attention_dropout to 0.0
INFO:tensorflow:Setting hparams.relu_dropout to 0.0
INFO:tensorflow:Beam Decoding with beam size 4
INFO:tensorflow:Done calling model_fn.
Traceback (most recent call last):
  File "/home/caiy/miniconda3/envs/LLQ/bin/t2t-decoder", line 17, in <module>
    tf.app.run()
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/caiy/miniconda3/envs/LLQ/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 209, in main
    decode(estimator, hp, decode_hp)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 98, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensor2tensor/utils/decoding.py", line 479, in decode_from_file
    for elapsed_time, result in timer(result_iter):
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensor2tensor/utils/decoding.py", line 473, in timer
    item = next(gen)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 629, in predict
    hooks=all_hooks) as mon_sess:
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 902, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 660, in create_session
    self._scaffold.finalize()
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 232, in finalize
    summary.merge_all)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 297, in get_or_default
    op = default_constructor()
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/summary/summary.py", line 406, in merge_all
    return merge(summary_ops, name=name)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/summary/summary.py", line 370, in merge
    with _ops.name_scope(name, 'Merge', inputs):
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6480, in __enter__
    g_from_inputs = _get_graph_from_inputs(self._values)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6113, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/caiy/miniconda3/envs/LLQ/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6048, in _assert_same_graph
    (item, original_item, graph, original_graph))
ValueError: Tensor("body/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention:0", shape=(), dtype=string, device=/device:GPU:0) must be from the same graph as Tensor("transformer_hparams:0", shape=(), dtype=string) (graphs are FuncGraph(name=transformer_while_body_4413, id=139722899435360) and <tensorflow.python.framework.ops.Graph object at 0x7f1348bad4e0>).
```

**Comment by liuliu8622** [comment]
issue resolved.
see [https://github.com/tensorflow/tensor2tensor/issues/1849](url)
