### ISSUE TITLE
Demo from Walkthrough and Attemptions of multimodels are inexecutable

### ISSUE THREAD

**Issue by duxy-me** [tensorflow/tensor2tensor#191]
Dear authors, 

I have got several problems since I started to attempt t2t. I list them here:
1. The file name of wmt_zhen lack of the suffix `.sgm`. Maybe this is caused by the datasets.
2. I've tried the demo from Walkthrough. It did work in 1.1.1 but reports errors after I updated the command with `pip install --upgrade`. The exceptions are attached below.
3. I can not successfully run any multimodels even using only two image problems or two wmt problems. I'm not sure what happened and It is hard to fix the inner problem. Could you please give a tutorial for the fascinating model?

The running parameters in problem 2 are as follows:
```
# See what problems, models, and hyperparameter sets are available.
# You can easily swap between them (and add new ones).
t2t-trainer --registry_help

#PROBLEM=wmt_zhen_tokens_32k #image_mnist_tune #wmt_zhen_tokens_8k
PROBLEM=image_mnist_tune
MODEL=transformer
HPARAMS=transformer_base #_single_gpu

ROOT=/home/dxy/expr/tensor2tensor
DATA_DIR=$ROOT/t2t_data
TMP_DIR=$ROOT/t2t_datagen
TRAIN_DIR=$ROOT/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --num_shard=100 \
  --problem=$PROBLEM

echo "down datagen"

# Train
# *  If you run out of memory, add --hparams='batch_size=2048' or even 1024.
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR
```
The errors mentioned in problem 2 are as follows:
```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 4, in <module>
    __import__('pkg_resources').run_script('tensor2tensor==1.1.3', 't2t-trainer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/EGG-INFO/scripts/t2t-trainer", line 82, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/EGG-INFO/scripts/t2t-trainer", line 78, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 292, in run
    run_locally(exp_fn(output_dir))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 610, in run_locally
    exp.train_and_evaluate()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 955, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1162, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 491, in model_fn
    len(hparams.problems) - 1)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 811, in _cond_on_index
    return fn(cur_idx)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 472, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/t2t_model.py", line 396, in model_fn
    sharded_features[key], dp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/modality.py", line 95, in bottom_sharded
    return data_parallelism(self.bottom, xs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/expert_utils.py", line 295, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/models/modalities.py", line 89, in bottom
    return self.bottom_simple(x, "shared", reuse=None)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/models/modalities.py", line 81, in bottom_simple
    ret = tf.gather(var, x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1179, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 589, in apply_op
    param_name=input_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'indices' has DataType uint8 not in list of allowed values: int32, int64
INFO:tensorflow:Creating experiment, storing model files in /home/dxy/expr/tensor2tensor/t2t_train/image_mnist_tune/transformer-transformer_base
```

The running parameters in problem 3 are as follows:
```
t2t-trainer --schedule=local_run --data_dir=/home/dxy/expr/tensor2tensor/data --problems=wmt_zhen_tokens_8k-image_mnist_tune --model=multi_model --hparams_set=multimodel_base --output_dir=/home/dxy/expr/tensor2tensor/t2t_train
```
The errors mentioned in problem 3 are as follows:
```
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py:268: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
Traceback (most recent call last):
  File "/home/dxy/expr/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 82, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/dxy/expr/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 78, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 292, in run
    run_locally(exp_fn(output_dir))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 610, in run_locally
    exp.train_and_evaluate()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 953, in _train_model
    features, labels = input_fn()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 1158, in input_fn
    lambda n: batches[n], problem_choice, 0, problem_count - 1)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.1.3-py2.7.egg/tensor2tensor/utils/trainer_utils.py", line 814, in _cond_on_index
    lambda: _cond_on_index(fn, index_tensor, cur_idx + 1, max_idx))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1861, in cond
    (val_x.dtype.name, val_y.dtype.name))
ValueError: Outputs of true_fn and false_fn must have the same type: int32, uint8
```

**Comment by lukaszkaiser** [comment]
I think problem 1 is corrected already. Transformer is not really an image model, but I'll still take a look at problem 2, it should work in principle. But maybe use `--model=xception --hparams_set=xception_tiny` for that.
