### ISSUE TITLE
'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Helmsman-Lab** [tensorflow/tensor2tensor#1922]
C:\Users\zhaoxianghui\AppData\Local\Programs\Python\Python38\python.exe D:\project\python\tensor2tensor-master\tensor2tensor\bin\t2t-trainer --registry_help 
Traceback (most recent call last):
  File "D:\project\python\tensor2tensor-master\tensor2tensor\bin\t2t-trainer", line 23, in <module>
    from tensor2tensor.bin import t2t_trainer
  File "D:\project\python\tensor2tensor-master\tensor2tensor\bin\t2t_trainer.py", line 24, in <module>
    from tensor2tensor import models  # pylint: disable=unused-import
  File "D:\project\python\tensor2tensor-master\tensor2tensor\models\__init__.py", line 51, in <module>
    from tensor2tensor.models.research import rl
  File "D:\project\python\tensor2tensor-master\tensor2tensor\models\research\rl.py", line 27, in <module>
    from tensor2tensor.envs import tic_tac_toe_env
  File "D:\project\python\tensor2tensor-master\tensor2tensor\envs\__init__.py", line 23, in <module>
    from tensor2tensor.envs import tic_tac_toe_env
  File "D:\project\python\tensor2tensor-master\tensor2tensor\envs\tic_tac_toe_env.py", line 244, in <module>
    register()
  File "D:\project\python\tensor2tensor-master\tensor2tensor\envs\tic_tac_toe_env.py", line 239, in register
    unused_tictactoe_id, unused_tictactoe_env = gym_utils.register_gym_env(
  File "D:\project\python\tensor2tensor-master\tensor2tensor\rl\gym_utils.py", line 360, in register_gym_env
    return env_name, gym.make(env_name)
  File "C:\Users\zhaoxianghui\AppData\Local\Programs\Python\Python38\lib\site-packages\gym\envs\registration.py", line 572, in make
    _kwargs = spec_.kwargs.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by Helmsman-Lab** [comment]
@TimOgden
[Change kwargs=None optional parameter to **kwargs](https://github.com/tensorflow/tensor2tensor/pull/1908/commits/8dbd4f680c97a56207dea7394ae8c2740703bb40)   this works to me
