### ISSUE TITLE
wmt_encs_tokens_32k  - Datagen error

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#197]
I am trying to start the d
"datagen" for the "wmt_encs_tokens_32k" and I receive the following error:

```
INFO:tensorflow:Generating problems:
  * wmt_encs_tokens_32k

INFO:tensorflow:Generating training data for wmt_encs_tokens_32k.
Traceback (most recent call last):
  File "/home/ahmed/tensorflow/bin/t2t-datagen", line 290, in <module>
    tf.app.run()
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ahmed/tensorflow/bin/t2t-datagen", line 239, in main
    generate_data_for_registered_problem(problem)
  File "/home/ahmed/tensorflow/bin/t2t-datagen", line 286, in generate_data_for_registered_problem
    task_id=task_id)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 383, in generate_data
    self.train_generator(data_dir, tmp_dir, True),
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/wmt.py", line 589, in train_generator
    data_dir, tmp_dir, self.vocab_file, self.targeted_vocab_size,
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 371, in vocab_file
    return "%s.%d" % (self.vocab_name, self.targeted_vocab_size)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 343, in targeted_vocab_size
    raise NotImplementedError()  # Not needed if self.is_character_level.
NotImplementedError
```

**Comment by martinpopel** [comment]
I am sorry, this is my fault - now fixed in #198.

I have fixed this some time ago in my repo, but also increased the encs training data (with CzEng corpus with 15M sentence pairs),
which required changing several other files in the codebase and I had not time to rebase it to the newest t2t.
