### ISSUE TITLE
Tensor2Tensor 1.1.4 require "requests"

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#202]
The new version of tensor2tensor requires "requests" python library.
I think it will much better to install it as dependency automatically once we installed tensor2tensor.
Otherwise, we will have the following error:

```
Traceback (most recent call last):
  File "/home/ahmed/tensorflow/bin/t2t-trainer", line 36, in <module>
    from tensor2tensor.utils import trainer_utils
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 37, in <module>
    from tensor2tensor.data_generators import all_problems  # pylint: disable=unused-import
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/all_problems.py", line 22, in <module>
    from tensor2tensor.data_generators import algorithmic
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/algorithmic.py", line 27, in <module>
    from tensor2tensor.data_generators import generator_utils as utils
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/generator_utils.py", line 31, in <module>
    import requests
ImportError: No module named requests
```

If you didn't, we have to manually install it "pip install requests".

**Comment by rsepassi** [comment]
Thank you for reporting and sorry about that. Will update `setup.py` with the dependency in the next release.
