### ISSUE TITLE
Out of memory on GPU in wmt_ende_tokens_32k

### ISSUE THREAD

**Issue by vthorsteinsson** [tensorflow/tensor2tensor#24]
`t2t-trainer` runs out of GPU memory when training on a single nVidia 1080 GTX (8 GB) with the following parameters:

```
PROBLEM=wmt_ende_tokens_32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu
```
Any hints on this?

More specifically, the exception `ResourceExhaustedError` is raised, cf. the following dump:
```
2017-06-22 11:55:49.859461: I tensorflow/core/common_runtime/bfc_allocator.cc:693]      Summary of in-use Chunks by size:
2017-06-22 11:55:49.859468: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 142 Chunks of size 256 totalling 35.5KiB
2017-06-22 11:55:49.859473: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
2017-06-22 11:55:49.859477: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 414 Chunks of size 2048 totalling 828.0KiB
2017-06-22 11:55:49.859482: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 24 Chunks of size 4096 totalling 96.0KiB
2017-06-22 11:55:49.859487: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 48 Chunks of size 6144 totalling 288.0KiB
2017-06-22 11:55:49.859491: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 48 Chunks of size 8192 totalling 384.0KiB
2017-06-22 11:55:49.859495: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 32768 totalling 160.0KiB
2017-06-22 11:55:49.859500: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 45824 totalling 44.8KiB
2017-06-22 11:55:49.859505: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 65536 totalling 256.0KiB
2017-06-22 11:55:49.859509: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 96 Chunks of size 1048576 totalling 96.00MiB
2017-06-22 11:55:49.859514: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 24 Chunks of size 2097152 totalling 48.00MiB
2017-06-22 11:55:49.859518: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 46 Chunks of size 3145728 totalling 138.00MiB
2017-06-22 11:55:49.859523: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 65 Chunks of size 4030464 totalling 249.84MiB
2017-06-22 11:55:49.859527: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 97 Chunks of size 4194304 totalling 388.00MiB
2017-06-22 11:55:49.859532: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 227 Chunks of size 16711680 totalling 3.53GiB
2017-06-22 11:55:49.859536: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 43 Chunks of size 20889600 totalling 856.64MiB
2017-06-22 11:55:49.859541: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 64487424 totalling 61.50MiB
2017-06-22 11:55:49.859546: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 12 Chunks of size 66846720 totalling 765.00MiB
2017-06-22 11:55:49.859550: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1288182528 totalling 1.20GiB
2017-06-22 11:55:49.859554: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 7.28GiB
2017-06-22 11:55:49.859561: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats:
Limit:                  7969800192
InUse:                  7813304576
MaxInUse:               7966874112
NumAllocs:                    1912
MaxAllocSize:           1288182528

2017-06-22 11:55:49.859613: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *************************************************************************************************xxx
2017-06-22 11:55:49.859627: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[102,80,1,1,31488]
Traceback (most recent call last):
  File "/home/villi/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/villi/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/villi/tf/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[102,80,1,1,31488]
         [[Node: symbol_modality_31488_512_2/parallel_0_1/symbol_modality_31488_512/padded_cross_entropy/smoothing_cross_entropy/one_hot = OneHot[T=DT_FLOAT, TI=DT_INT32, axis=-1, _device="/job:localhost/replica:0/task:0/gpu:0"](symbol_modality_31488_512_2/parallel_0_1/symbol_modality_31488_512/padded_cross_entropy/pad_with_zeros/pad_to_same_length/Pad_1/_2643, symbol_modality_31488_512_2/parallel_0_1/symbol_modality_31488_512/strided_slice, symbol_modality_31488_512_2/parallel_0_1/symbol_modality_31488_512/padded_cross_entropy/smoothing_cross_entropy/one_hot/on_value, symbol_modality_31488_512_2/parallel_0_1/symbol_modality_31488_512/padded_cross_entropy/smoothing_cross_entropy/truediv)]]
         [[Node: training/train/update/_2730 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_13171_training/train/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

**Comment by stefan-it** [comment]
You could try to specify a lower `batch_size` with `--hparams='batch_size=2048` - maybe this could help :)

**Comment by vthorsteinsson** [comment]
FYI, `wmt_ende_tokens_8k` also runs out of memory, with the following message:

```
2017-06-22 14:44:26.123238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
2017-06-22 14:44:26.123250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2017-06-22 14:44:26.123253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2017-06-22 14:44:26.123258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
2017-06-22 14:44:27.445354: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1266 get requests, put_count=1200 evicted_count=1000 eviction_rate=0.833333 and unsatisfied allocation rate=0.921011
2017-06-22 14:44:27.445376: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:Saving checkpoints for 1 into /home/villi/t2t_train/wmt_ende_tokens_8k/transformer-transformer_base_single_gpu/model.ckpt.
INFO:tensorflow:loss = 8.20178, step = 1
2017-06-22 14:44:51.372631: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 4706 get requests, put_count=4631 evicted_count=1000 eviction_rate=0.215936 and unsatisfied allocation rate=0.233319
2017-06-22 14:44:51.372678: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
2017-06-22 14:45:58.090401: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 256.09MiB.  Current allocation summary follows.
```

**Comment by vthorsteinsson** [comment]
Thanks @stefan-it - will try!

**Comment by rsepassi** [comment]
And please report back on what you find. We may want to rename the hparams sets based on memory requirements. e.g. "single_gpu" might assume 12gb right now.

**Comment by vthorsteinsson** [comment]
`--hparams='batch_size=2048'` seems to work - it's training now. Will let you know how it goes tomorrow (the full training run will take 20 hrs, it's 250,000 steps, where 100 steps take 30 seconds) ;-)

**Comment by vthorsteinsson** [comment]
Training completed successfully in under 20 hours for `wmt_ende_tokens_32k` using
`--hparams='batch_size=2048'`. Looks good!

**Comment by lukaszkaiser** [comment]
Oh, I'm not sure if the default (250K train steps?) is enough to train a good model at reduced batch size. You can train more by increasing `--train_steps`. Did you try decoding? How does it look, are the decodes reasonable? Thanks for trying it!

**Comment by daiwk** [comment]
My configuration is GTX860M and I have 8G memory, and I am using 'transformer_base' Hparams and 'transformer' model. I tried --hparams='batch_size=2048' but it still oom......

**Comment by daiwk** [comment]
my gpu memory is 2G..

**Comment by stefan-it** [comment]
You could try to use a smaller `batch_size` like 1024, maybe this helps :)

**Comment by daiwk** [comment]
@stefan-it  I tried 

 batch_size =1024 or 100 or even 10
all resulted in the same result...

> 2017-06-24 16:20:01.110115: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 73197568 totalling 69.81MiB
> 2017-06-24 16:20:01.110120: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 1.71GiB
> 2017-06-24 16:20:01.110129: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats:
> Limit:                  1861353472
> InUse:                  1841349632
> MaxInUse:               1854568960
> NumAllocs:                    1365
> MaxAllocSize:             73197568
> 
> 2017-06-24 16:20:01.110180: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ****************************************************************************************************
> 2017-06-24 16:20:01.110198: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[85,43,1,512]
> Traceback (most recent call last):
>

**Comment by lukaszkaiser** [comment]
@daiwk : to be truthful, I have to say that I doubt you'll have much success training on GTX 860M. 2GB of GPU memory is just not enough, even if it worked with very small batch size you'll have trouble setting learning rates, and you'll have to wait many days for any reasonable results. It might be easier to try training on CPU instead: just install the cpu-only TensorFlow or set CUDA_VISIBLE_DEVICES to empty. I'm sorry, but earlier laptops were just not built for training ML models, only recently there are some decent ones with desktop-grate 10XX-cards.
