### ISSUE TITLE
Embedding size and hidden unit size

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#244]
I am not sure if I should post it here or the mailing list. I am aware of this problem however I could not find the previous issue that made me aware of it.

It seems that if the embedding size is different then the hidden size, tensor2tensor would not be able to support it. I wonder if there is any work around currently? Below is a log where a attempt to pass embedding to the transformer with different size.

```
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\trainer_utils.py", line 293, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 677, in _call_train
    monitors=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 958, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1165, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1136, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\model_builder.py", line 227, in model_fn
    len(my_hp.problems) - 1)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\input_fn_builder.py", line 196, in cond_on_index
    return fn(cur_idx)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\model_builder.py", line 200, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\t2t_model.py", line 474, in model_fn
    transformed_features)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\t2t_model.py", line 527, in model_fn_body_sharded
    datashard_to_features)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\expert_utils.py", line 191, in _call_
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\t2t_model.py", line 40, in fn_with_timing
    res = fn(*args, **kwargs)
  File "L:/python34_colman/projects/trans/usr\t2t_usr\full_char.py", line 64, in model_fn_body
    encoder_input, encoder_self_attention_bias, hparams)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\models\transformer.py", line 202, in transformer_encoder
    x = common_layers.layer_postprocess(x, y, hparams)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\layers\common_layers.py", line 594, in layer_postprocess
    name="layer_postprocess")
  File "l:\python34_colman\tensor2tensor\tensor2tensor\layers\common_layers.py", line 523, in layer_prepostprocess
    x += previous_value
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 865, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 80, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2632, in create_op
    set_shapes_for_outputs(ret)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1911, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1861, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 512 and 2100 for 'body/model/parallel_0/body/encoder/layer_0/self_attention/layer_postprocess/add' (op: 'Add') with input shapes: [2048,?,512], [2048,?,2100].
```

**Comment by mirkobronzi** [comment]
May this be related to the fact that when embedding_size == hidden_size then it is easier to deal with multi-layer architecture because there is no need to treat differently the first layers (accepting embeddings) from the successive layers (accepting hidden states)?
not sure because I would need to study more in details the models to be 100% certain.

assuming this is correct, is it the only solution to apply projections to make the dimensions match?
(when embedding_size != hidden_size)

**Comment by colmantse** [comment]
yeah, i tweaked the model and apply a fully_connected layer to upscale or downscale the size of the hidden layer.

**Comment by rsepassi** [comment]
Yes, currently the hidden size hparam is used to determine the embedding size. We'll keep that for now.

**Comment by vince62s** [comment]
@colmantse Even if it's not for merge right now, I am interested in how you did this.
I would like to try the Big model (size 1024) with smaller embeddings (eg 512 )
Thanks for sharing this.

**Comment by colmantse** [comment]
@vince62s I was naïve then, I basically introduced a new param and edit a user_version transformer that project everything to the usr_defined hidden_size (replace hidden_size with user_hidden_size), and include a projection layer right at transformer.encode() after the flatten operation to up scale the stuff. So that I would be using a hidden_size of 512 (embedding) and a usr_hidden_size (layer) of 1024. I don't recommend doing it, because it is pretty dumb and whenever there is major upgrade, then its a start all over. So I scrapped the idea after the upgrade lol.

I would suggest looking at symbol modality at modalities, there is an interesting _get_weight function which assume hidden_size=None and use _body_input_depth. Unfortunately, I have still not worked out how t2t_model receive its 'features' from modalities, if you find anything, do let me know.
