### ISSUE TITLE
NaN loss during training error

### ISSUE THREAD

**Issue by carlosep93** [tensorflow/tensor2tensor#245]
Hi,

I'm trying to apply the cycle_gan model to a translation task and I'm having two errors that  I cannot figure out their cause.

I'm using and NVIDIA TITAN X gpu and I'm getting a CUDA_ERROR_OUT_OF_MEMORY.  Batch size is  1024.

After this error the training seems to start but then  the following error appears: NaN loss during training.

I'm using translate_ende_wmt8k as problem, cycle_gan as model and the following defined hparams:

```
from tensor2tensor.models import cycle_gan
 from tensor2tensor.utils import registry
  
  @registry.register_hparams
  def cycle_gan_wmt():
       hparams = cycle_gan.cycle_gan_small()
       hparams.vocab_size=8000
       hparams.batch_size = 1024
       return hparams
```

The script I'm using:

```
PROBLEM=translate_ende_wmt8k
MODEL=cycle_gan
HPARAMS=cycle_gan_wmt
WORKERS=4

DATA_DIR=./t2t_data
TMP_DIR=.t/2t_datagen
TRAIN_DIR=./t2t_train/$PROBLEM/$MODEL-$HPARAMS
USR_DIR=my-registrations

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM

# Train
#  If you run out of memory, add --hparams='batch_size=1024'.

t2t-trainer \
  --t2t_usr_dir=$USR_DIR \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR 


# Decode

DECODE_FILE=$DATA_DIR/decode_this.txt
echo "Hello world" >> $DECODE_FILE
echo "Goodbye world" >> $DECODE_FILE

BEAM_SIZE=4
ALPHA=0.6

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --train_steps=0 \
  --eval_steps=0 \
  --decode_beam_size=$BEAM_SIZE \
  --decode_alpha=$ALPHA \
  --decode_from_file=$DECODE_FILE

cat $DECODE_FILE.$MODEL.$HPARAMS.beam$BEAM_SIZE.alpha$ALPHA.decodes
```

and the error:

```
2017-08-23 12:06:53.223951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name
: GeForce GTX TITAN X, pci bus id: 0000:42:00.0)
2017-08-23 12:06:53.264180: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 11.92G (12800163840 bytes) from device:
 CUDA_ERROR_OUT_OF_MEMORY
INFO:tensorflow:Restoring parameters from ./t2t_train/translate_ende_wmt8k/cycle_gan-cycle_gan_wmt/model.ckpt-6
2017-08-23 12:07:09.186257: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 3591 get requests, put_count=16
62 evicted_count=1000 eviction_rate=0.601685 and unsatisfied allocation rate=0.843498
2017-08-23 12:07:09.186632: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:Saving checkpoints for 7 into ./t2t_train/translate_ende_wmt8k/cycle_gan-cycle_gan_wmt/model.ckpt.
ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in ru
n
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 293, i
n run
    exp.train_and_evaluate()
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.p
y", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.p
y", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.p
y", line 665, in _call_train
    monitors=hooks)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, 
in new_func
    return func(*args, **kwargs)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/e
stimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/e
stimator.py", line 1007, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", 
line 505, in run
    run_metadata=run_metadata)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", 
line 842, in run
    run_metadata=run_metadata)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", 
line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", 
line 960, in run
    run_metadata=run_metadata))
  File "/home/usuaris/veu/cescola/virtualenv-15.1.0/entornotf/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks
.py", line 477, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```

Thanks in advance,

Carlos

**Comment by lukaszkaiser** [comment]
Hopefully this is gone with the newer Tensorflow, the CUDA stuff can often be ignored, it's actually only a warning.
