### ISSUE TITLE
Unable to locate new writable file midway during training

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#246]
Dear all, 

I have not yet been unable to identify the cause of this problem, but it seems memory correlated. 
If the model has a size of 80,000,000 then it will stop around 9k steps. if the model is of 60,000,000 then it will stop around 18k. Help would be appreciated. I am running the transformer with a little preprocessing at model_body_fn before feeding the input into prepare encoder. It works normal and all the stats are showing until the mentioned fail appear. Any help would be appreciated!

```
INFO:tensorflow:loss = 2.11804, step = 17901 (15.054 sec)
INFO:tensorflow:global_step/sec: 6.57254
INFO:tensorflow:loss = 1.99967, step = 18001 (15.216 sec)
INFO:tensorflow:Saving checkpoints for 18079 into L:/python34_colman/projects/trans/t2t_train/translate_enzh_wmt_characters/full__char__transformer-full_char_transformer_base_single_gpu\model.ckpt.
2017-08-23 20:01:18.341582: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Not found: Failed to create a NewWriteableFile: L:/python34_colman/projects/trans/t2t_train/translate_enzh_wmt_characters/full__char__transformer-full_char_transformer_base_single_gpu\model.ckpt-18079_temp_48af120a5a84466781278b0bea135f2e/part-00000-of-00002.data-00000-of-00001.tempstate13234710060557317781 : The system cannot find the path specified.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 88, in _exit_
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: L:/python34_colman/projects/trans/t2t_train/translate_enzh_wmt_characters/full__char__transformer-full_char_transformer_base_single_gpu\model.ckpt-18079_temp_48af120a5a84466781278b0bea135f2e/part-00000-of-00002.data-00000-of-00001.tempstate13234710060557317781 : The system cannot find the path specified.

         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step, losses_avg/problem_0/extra_loss/_5365, losses_avg/problem_0/total_loss/_5367, losses_avg/problem_0/training_loss/_5369, train_stats/problem_0_steps)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\trainer_utils.py", line 293, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 677, in _call_train
    monitors=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1010, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 980, in run
    run_metadata=run_metadata))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 442, in after_run
    self._save(global_step, run_context.session)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 458, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1490, in save
    raise exc
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1474, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: L:/python34_colman/projects/trans/t2t_train/translate_enzh_wmt_characters/full__char__transformer-full_char_transformer_base_single_gpu\model.ckpt-18079_temp_48af120a5a84466781278b0bea135f2e/part-00000-of-00002.data-00000-of-00001.tempstate13234710060557317781 : The system cannot find the path specified.

         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step, losses_avg/problem_0/extra_loss/_5365, losses_avg/problem_0/total_loss/_5367, losses_avg/problem_0/training_loss/_5369, train_stats/problem_0_steps)]]

Caused by op 'save/SaveV2', defined at:
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\trainer_utils.py", line 293, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 677, in _call_train
    monitors=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1006, in _train_model
    config=self._session_config
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 365, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 668, in _init_
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 490, in _init_
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 842, in _init_
    _WrappedSession.__init__(self, self._create_session())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 847, in _create_session
    return self._sess_creator.create_session()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 551, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 416, in create_session
    self._scaffold.finalize()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 209, in finalize
    self._saver.build()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1172, in build
    filename=self._filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 682, in build
    save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddShardedSaveOps
    return self._AddShardedSaveOpsForV2(filename_tensor, per_device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddShardedSaveOpsForV2
    sharded_saves.append(self._AddSaveOps(sharded_filename, saveables))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 276, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 219, in save_op
    tensors)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 768, in save_v2
    tensors=tensors, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in _init_
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Failed to create a NewWriteableFile: L:/python34_colman/projects/trans/t2t_train/translate_enzh_wmt_characters/full__char__transformer-full_char_transformer_base_single_gpu\model.ckpt-18079_temp_48af120a5a84466781278b0bea135f2e/part-00000-of-00002.data-00000-of-00001.tempstate13234710060557317781 : The system cannot find the path specified.

         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step, losses_avg/problem_0/extra_loss/_5365, losses_avg/problem_0/total_loss/_5367, losses_avg/problem_0/training_loss/_5369, train_stats/problem_0_steps)]]
```

**Comment by martinpopel** [comment]
Wild guess: the file which cannot be created contains a mix of Unix and Windows path separators (forward and backward slash): `...full_char_transformer_base_single_gpu\model.ckpt-18079_temp_48af120a5a84466781278b0bea135f2e/par...`
Maybe there is `os.path.join` missing somewhere in the code.

**Comment by colmantse** [comment]
Yea but it is quite weird, since I have not modify any codes apart from calling several layer before preparing transformer's encoder. The rest are left unaltered. But transformer work just fine..

**Comment by colmantse** [comment]
I have readjust the altered transformer to 47,000,000 units and no crash has been encountered in all 120k steps (I set train_sets=120k), so i think it is more likely a memory problem although no conclusive answer can be found.

**Comment by abhishekraok** [comment]
I used os.path.abspath and os.path.join and that helped.

**Comment by Bhavyabhushanyadav** [comment]
https://github.com/una-dinosauria/human-motion-prediction/issues/10
