### ISSUE TITLE
Failed to create a NewWriteableFile for registering new dataset.

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#253]
Following #111 , I am wondering if the below error log was due to the size of the data file (4gb and 2 gb). I double checked my self-registered problem and make sure that I didn't do anything on ende_wmt_character apart from changing names and substituting component. While the original one work, my altered one got the log below.

```
INFO:tensorflow:Importing user module t2t_usr from path usr
INFO:tensorflow:Generating problems:
    translate:
      * translate_enzh_un_characters
INFO:tensorflow:Generating data for translate_enzh_un_characters.
INFO:tensorflow:Not downloading, file already found: tmp/t2t_datagen\
INFO:tensorflow:Not downloading, file already found: tmp/t2t_datagen\
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-datagen", line 231, in <module>
    tf.app.run()
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-datagen", line 197, in main
    generate_data_for_registered_problem(problem)
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-datagen", line 227, in generate_data_for_registered_problem
    task_id=task_id)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\problem.py", line 418, in generate_data
    self.dev_filepaths(data_dir, self.num_dev_shards, shuffled=False))
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\generator_utils.py", line 448, in generate_dataset_and_shuffle
    generate_files(train_gen, train_paths)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\generator_utils.py", line 141, in generate_files
    writers = [tf.python_io.TFRecordWriter(fname) for fname in output_filenames]
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\generator_utils.py", line 141, in <listcomp>
    writers = [tf.python_io.TFRecordWriter(fname) for fname in output_filenames]
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: L:/python34_colman/project/trans/t2t_data\translate_enzh_un_characters-unshuffled-train-00000-of-00100 : ???????????
```

**Comment by colmantse** [comment]
just figured out this is a memory issue.

**Comment by appyfizzA** [comment]
@colmantse how did you solve it? 
I'm trying to save models trained by deep networks into a folder. Although the folder is getting created, saving doesn't happen. And I get this same error.

Kindly help.

**Comment by andimarafioti** [comment]
For me it was a jupyter notebook that didn't release the GPU after using it. Just restarting the kernel did the trick.

**Comment by colmantse** [comment]
do not use a laptop, use a proper desktop with enough ram lol
