### ISSUE TITLE
data_reader failed after upgrading to 1.2.0

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#256]
I trained some model half way with t2t 1.1.9 and then upgraded to 1.2.0. Under which version data_reader failed to work, and so the training can't proceed. The entire log is as follows. Other info includes tensorflow 1.3.0, cudnn 6.0, cuda 8.0, python 3.6.  

INFO:tensorflow:Skipping training since max_steps has already saved.
Traceback (most recent call last):
  File "/home/ec2-user/kklab/src/anaconda3/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ec2-user/kklab/src/anaconda3/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensor2tensor/utils/trainer_utils.py", line 305, in run
    exp.train_and_evaluate()
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 508, in train_and_evaluate
    hooks=self._eval_hooks)
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 700, in _call_evaluate
    hooks=hooks)
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 546, in evaluate
    log_progress=log_progress)
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 829, in _evaluate_model
    features, labels = input_fn()
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensor2tensor/utils/input_fn_builder.py", line 103, in input_fn
    length_multiplier=(p_hparams.batch_size_multiplier)))
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensor2tensor/utils/data_reader.py", line 274, in input_pipeline
    batching_scheme["batch_sizes"])
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensor2tensor/utils/data_reader.py", line 359, in bucket_by_sequence_length
    bucket_batch_sizes1 = [_closest_small_primes(b) for b in bucket_batch_sizes]
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensor2tensor/utils/data_reader.py", line 359, in <listcomp>
    bucket_batch_sizes1 = [_closest_small_primes(b) for b in bucket_batch_sizes]
  File "/home/ec2-user/kklab/src/anaconda3/lib/python3.6/site-packages/tensor2tensor/utils/data_reader.py", line 333, in _closest_small_primes
    for i in xrange(x):
NameError: name 'xrange' is not defined

**Comment by martinpopel** [comment]
`from six.moves import xrange` is missing in `utils/data_reader.py` so it works in Python3

Even with this fix I am not sure the 1.2.0 code is able to load pre1.2.0 datasets and models (I would guess no).

Also: You wrote "half way trained", but the log says max_steps of training were already achieved.

**Comment by anglil** [comment]
@martinpopel thanks. importing python2 xrange does solve the problem. Stating it as "half way trained" was indeed not accurate, but other half way trained models that I have from 1.1.9 can't be trained incrementally under 1.2.0 either; I'm retraining all models from scratch now.

**Comment by anglil** [comment]
Thanks!

**Comment by colmantse** [comment]
Please reopen, I think they have the same issue with input_fn after the upgrade to 1.2.1. Below is the trace:

```
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 508, in train_and_evaluate
    hooks=self._eval_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 700, in _call_evaluate
    hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 546, in evaluate
    log_progress=log_progress)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 829, in _evaluate_model
    features, labels = input_fn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\input_fn_builder.py", line 103, in input_fn
    length_multiplier=(p_hparams.batch_size_multiplier)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\data_reader.py", line 457, in hparams_to_batching_scheme
    length_multiplier=length_multiplier)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\data_reader.py", line 423, in _batching_scheme
    divisors = [i for i in xrange(1, window_size + 1) if window_size % i == 0]
NameError: name 'xrange' is not defined
```

**Comment by ghego** [comment]
Should be fixed here: https://github.com/tensorflow/tensor2tensor/pull/267, please check
