### ISSUE TITLE
input_fn fails again with xrange after upgrading to 1.2.1

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#265]
I suspect this is a similar issue with #256 . 

Below is the trace:

```
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 508, in train_and_evaluate
    hooks=self._eval_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 700, in _call_evaluate
    hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 546, in evaluate
    log_progress=log_progress)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 829, in _evaluate_model
    features, labels = input_fn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\input_fn_builder.py", line 103, in input_fn
    length_multiplier=(p_hparams.batch_size_multiplier)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\data_reader.py", line 457, in hparams_to_batching_scheme
    length_multiplier=length_multiplier)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\data_reader.py", line 423, in _batching_scheme
    divisors = [i for i in xrange(1, window_size + 1) if window_size % i == 0]
NameError: name 'xrange' is not defined
```

P.S. this is fixed by the mentioned solution in the other post by importing from six xrange but would just want to bring this to the attention of the t2t-team. That the script does not work with python 3.6 without the import.

**Comment by colmantse** [comment]
will not be able to test until next week, will reopen if it remains an issue then, thanks!

**Comment by lukaszkaiser** [comment]
Thanks guys!
