### ISSUE TITLE
Weird occasional breakdown: TypeError: '<=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#270]
Dear all, 

I would like to report a weird occasional breakdown with the trace below. If I restart it, it will be able to run for a bit and then crash like this again. This error surface after the recent upgrade to 1.2.1, I have the custom getter tweaked as None manually. I am not sure if this is the cause. Any insights would be greatly appreciated.

Warmest Regards,
Colman Tse

```
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 677, in _call_train
    monitors=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1010, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 980, in run
    run_metadata=run_metadata))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 509, in after_run
    if self._timer.should_trigger_for_step(global_step):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 128, in should_trigger_for_step
    if step >= self._last_triggered_step + self._every_steps:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

**Comment by colmantse** [comment]
It seems that this happens only when the desktop fell asleep. I disabled the automatically fell asleep option and so far it has been alright. I will reopen if it turns out sleep mode unrelated.

**Comment by lukaszkaiser** [comment]
Great thanks for finding out the cause! It might be worth to warn others too.
