### ISSUE TITLE
ptb10k error

### ISSUE THREAD

**Issue by vince62s** [tensorflow/tensor2tensor#272]
From the pip install.

Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 74, in main
    problem.generate_data(data_dir, tmp_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/data_generators/problem.py", line 419, in generate_data
    self.generator(data_dir, tmp_dir, False), dev_paths)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/data_generators/generator_utils.py", line 465, in generate_dataset_and_shuffle
    generate_files(train_gen, train_paths)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/data_generators/generator_utils.py", line 143, in generate_files
    for case in generator:
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/data_generators/ptb.py", line 155, in _generator
    tok = encoder.encode(line)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/data_generators/text_encoder.py", line 199, in encode
    ret = [self._token_to_id[tok] for tok in tokens]
KeyError: '<EOS>'

**Comment by ghego** [comment]
Confirmed, I get the exact same error. @lukaszkaiser any ideas on this?

**Comment by ghego** [comment]
@rsepassi could you test the datagen for ptb and see if you can get it to work? It'd be great to have a much smaller dataset working to debug the many other issues we see with attention models. Thanks

**Comment by rsepassi** [comment]
I believe this has been fixed. Just ran datagen on languagemodel_ptb10k and it worked fine.

**Comment by duyvuleo** [comment]
I just tried this and got the error on languagemodel_ptb10k. I am using the latest tensor2tensor with python 3. 
```
t2t-datagen --data_dir=/nfs/team/nlp/users/vhoang/experiments/nmt/data/tensor2tensor/ptb10k  --tmp_dir=/nfs/team/nlp/users/vhoang/tmp/ptb10k --problem=languagemodel_ptb10k
INFO:tensorflow:Generating problems:
    languagemodel:
      * languagemodel_ptb10k
[2018-03-08 17:18:26,909] Generating problems:
    languagemodel:
      * languagemodel_ptb10k
INFO:tensorflow:Generating data for languagemodel_ptb10k.
[2018-03-08 17:18:26,910] Generating data for languagemodel_ptb10k.
Traceback (most recent call last):
  File "/nfs/team/nlp/users/vhoang/ve3/bin/t2t-datagen", line 27, in <module>
    tf.app.run()
  File "/nfs/team/nlp/users/vhoang/ve3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/nfs/team/nlp/users/vhoang/ve3/bin/t2t-datagen", line 23, in main
    t2t_datagen.main(argv)
  File "/nfs/team/nlp/users/vhoang/ve3/lib/python3.6/site-packages/tensor2tensor/bin/t2t_datagen.py", line 185, in main
    generate_data_for_registered_problem(problem)
  File "/nfs/team/nlp/users/vhoang/ve3/lib/python3.6/site-packages/tensor2tensor/bin/t2t_datagen.py", line 234, in generate_data_for_registered_problem
    problem.generate_data(data_dir, tmp_dir, task_id)
  File "/nfs/team/nlp/users/vhoang/ve3/lib/python3.6/site-packages/tensor2tensor/data_generators/text_problems.py", line 248, in generate_data
    if self.is_generate_per_split:
  File "/nfs/team/nlp/users/vhoang/ve3/lib/python3.6/site-packages/tensor2tensor/data_generators/text_problems.py", line 84, in is_generate_per_split
    raise NotImplementedError()
```

**Comment by duyvuleo** [comment]
@rsepassi : can you double check it? thanks!

**Comment by martinpopel** [comment]
see #625
