### ISSUE TITLE
Model LSTMSeq2seqAttention never registered

### ISSUE THREAD

**Issue by Peony-q** [tensorflow/tensor2tensor#275]
I ran the model bytenet and LSTMSeq2seqAttention, but the same problem appeared:

Model LSTMSeq2seqAttention never registered
Model bytenet never registered

My codes:
t2t-trainer \
>   --generate_data \
>   --data_dir=./lstm_data \
>   --problems=translate_ende_wmt8k \
>   --model=LSTMSeq2seqAttention\
>   --hparams_set=lstm_attention \
>   --output_dir=./lstm_train
 
t2t-trainer \
> generate_data \
> --data_dir =./bytenet_data \
> --problems=translate_ende_wmt8k\
> --model=bytenet \
> --hparams_set=bytenet_base \
> --output_dir=./bytenet_train

the stack:
Traceback (most recent call last):
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 677, in _call_train
    monitors=hooks)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 958, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1165, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1136, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensor2tensor/utils/model_builder.py", line 273, in model_fn
    len(my_hp.problems) - 1)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 200, in cond_on_index
    return fn(cur_idx)
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensor2tensor/utils/model_builder.py", line 214, in nth_model
    model_class = registry.model(model)(
  File "/home/datadisk/mqdata/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensor2tensor/utils/registry.py", line 140, in model
    raise ValueError("Model %s never registered." % name)
ValueError: Model LSTMSeq2seqAttention never registered.

There must be something wrong, but I can't figure out what's the problem. Could you help me? Thanks!

**Comment by colmantse** [comment]
please use t2t-trainer --registry_help to navigate which model is actually registered. Sometimes they have different names. 

lstm:
      * lstm_seq2seq
      * lstm_seq2seq_attention

**Comment by Peony-q** [comment]
It works, thanks you!
