### ISSUE TITLE
error when running the plain command from instructions... (wmt-deen)

### ISSUE THREAD

**Issue by vince62s** [tensorflow/tensor2tensor#277]
version issue ?

INFO:tensorflow:Performing local training and evaluation.
WARNING:tensorflow:From /home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:268: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:batching_scheme = {'boundaries': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 33, 36, 39, 42, 46, 50, 55, 60, 66, 72, 79, 86, 94, 103, 113, 124, 136, 149, 163, 179, 196, 215, 236], 'window_size': 720, 'max_length': 256, 'batch_sizes': [240, 180, 180, 180, 144, 144, 144, 120, 120, 120, 90, 90, 90, 90, 80, 72, 72, 60, 60, 48, 48, 48, 40, 40, 36, 30, 30, 24, 24, 20, 20, 18, 18, 16, 15, 12, 12, 10, 10, 9, 8, 8], 'shuffle_queue_size': 270}
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 953, in _train_model
    features, labels = input_fn()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 103, in input_fn
    length_multiplier=(p_hparams.batch_size_multiplier)))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/data_reader.py", line 263, in input_pipeline
    dataset = read_examples(problem, data_file_pattern, capacity, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/data_reader.py", line 236, in read_examples
    data_items_to_decoders=data_items_to_decoders)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/data_reader.py", line 122, in examples_reader
    dataset = dataset.map(decode_record, num_threads=num_threads)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 813, in map
    return MapDataset(self, map_func, num_threads, output_buffer_size)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 1436, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 619, in add_to_graph
    self._create_definition_if_needed()
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/data/python/framework/function.py", line 167, in _create_definition_if_needed
    outputs = self._func(*inputs)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 1427, in tf_map_func
    flattened_ret = [ops.convert_to_tensor(t) for t in nest.flatten(ret)]
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/moses/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 462, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'inputs': <tf.Tensor 'SparseToDense:0' shape=(?,) dtype=int64>, 'targets': <tf.Tensor 'SparseToDense_1:0' shape=(?,) dtype=int64>}. Consider casting elements to a supported type.

**Comment by lukaszkaiser** [comment]
Thanks for reporting! Could you paste exactly the command you used, and also which TensorFlow version you have? Thanks!

**Comment by vince62s** [comment]
CUDA_VISIBLE_DEVICES=0 && t2t-trainer --generate_data --data_dir=t2t/data --problems=translate_ende_wmt32k --model=transformer --hparams_set=transformer_base_single_gpu --output_dir=t2t/train

tensorflow-gpu 1.2.0

**Comment by lukaszkaiser** [comment]
Sorry, starting from T2T 1.2 we require TensorFlow 1.3 or above. Could you upgrade and try again?

**Comment by vince62s** [comment]
it seems to run BUT:
eventhough I have the CUDA_VISIBLE_DEVICES=0 it uses the 2 gpu memory
and I see a strange error below "cuda out of memory" 

2017-09-03 21:49:06.106028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:847] Peer access not supported between device ordinals 0 and 1
2017-09-03 21:49:06.106041: I tensorflow/core/common_runtime/gpu/gpu_device.cc:847] Peer access not supported between device ordinals 1 and 0
2017-09-03 21:49:06.106049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 1 
2017-09-03 21:49:06.106052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y N 
2017-09-03 21:49:06.106055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 1:   N Y 
2017-09-03 21:49:06.106074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
2017-09-03 21:49:06.106078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
2017-09-03 21:49:06.108752: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 10.91G (11713708032 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2017-09-03 21:49:06.376157: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 7.92G (8508145664 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
INFO:tensorflow:Saving checkpoints for 1 into t2t/train/model.ckpt.
INFO:tensorflow:loss = 9.63484, step = 1
INFO:tensorflow:global_step/sec: 4.9957

**Comment by vince62s** [comment]
okay, to get a first flavor I interrupted training afeter a few hours, last eval saying:

INFO:tensorflow:Finished evaluation at 2017-09-04-05:33:44
INFO:tensorflow:Saving dict for global step 168828: global_step = 168828, loss = 1.69196, metrics-translate_ende_wmt32k/accuracy = 0.638574, metrics-translate_ende_wmt32k/accuracy_per_sequence = 0.00289855, metrics-translate_ende_wmt32k/accuracy_top5 = 0.820715, metrics-translate_ende_wmt32k/approx_bleu_score = 0.356522, metrics-translate_ende_wmt32k/neg_log_perplexity = -1.96287, metrics-translate_ende_wmt32k/rouge_2_fscore = 0.435023, metrics-translate_ende_wmt32k/rouge_L_fscore = 0.629634
INFO:tensorflow:Validation (step 170000): metrics-translate_ende_wmt32k/accuracy_per_sequence = 0.00289855, metrics-translate_ende_wmt32k/accuracy = 0.638574, global_step = 168828, loss = 1.69196, metrics-translate_ende_wmt32k/accuracy_top5 = 0.820715, metrics-translate_ende_wmt32k/rouge_L_fscore = 0.629634, **metrics-translate_ende_wmt32k/approx_bleu_score = 0.356522**, metrics-translate_ende_wmt32k/rouge_2_fscore = 0.435023, metrics-translate_ende_wmt32k/neg_log_perplexity = -1.96287
INFO:tensorflow:global_step/sec: 2.3342

does this mean 35.7 BLEU on the dev set ? looks too good to be true.

then I run

CUDA_VISIBLE_DEVICES=0 && t2t-decoder --data_dir=t2t/data --problems=translate_ende_wmt32k --model=transformer --hparams_set=transformer_base_single_gpu --output_dir=t2t/train --decode_beam_size=4 --decode_alpha=0.6 --decode_from_file=newstest2015-deen-src.de

the output is still in german ....

any clue ?

**Comment by martinpopel** [comment]
> does this mean 35.7 BLEU on the dev set ?

No. I expect real BLEU (wmt13) will be about 20, if approx_bleu is 35.7 on the ende problem.
* approx_bleu is computed on the internal subword tokenization, thus it is not comparable to the real BLEU on full words. This is the biggest factor for the difference, causing approx_bleu to be much higher than BLEU.
* approx_bleu is computed without beam search
* approx_bleu is computed only on `eval_steps` batches (10 by default) of the dev set (depending on the batch size, this may be e.g. just one tenth of the full dev set). 

> decode_from_file=newstest2015-deen-src.de
> the output is still in german ....

Use English on the input: decode_from_file=newstest2015-deen-src.en

**Comment by vince62s** [comment]
wait, I thought this was the "deen" task as the name says ...

**Comment by martinpopel** [comment]
> I thought this was the "deen" task as the name s

"deen" is just a name of the file with the dataset.
The task name you use is `translate_ende_wmt32k`.
If you want German to English translation, use `t2t-trainer --problems=translate_ende_wmt32k_rev`.

**Comment by vince62s** [comment]
ok, nice.
now do you know why it still uses 2 GPU even if I prepend the CUDA_VISIBLE_DEVICES=0 command ?

**Comment by martinpopel** [comment]
> do you know why it still uses 2 GPU even if I prepend the CUDA_VISIBLE_DEVICES=0 command ?
No. When I use `export CUDA_VISIBLE_DEVICES=0`, TensorFlow respects this.

**Comment by vince62s** [comment]
okay Nist Bleu 23.57 on newstest2015 not bad for less than half a day of training ....
