### ISSUE TITLE
Issue with LM1B

### ISSUE THREAD

**Issue by ghego** [tensorflow/tensor2tensor#283]
I tried running the language model LM1B provided but I run into an error;

I generated the data with:

```bash
PROBLEM=languagemodel_lm1b32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM
```
which worked fine and it generated data and a vocab file named `vocab-2016-09-10.txt.en` (which is supposedly the original vocab?)

When I run the problem with:

```bash
PROBLEM=languagemodel_lm1b32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
```

The program fails with error:

```python
Traceback (most recent call last):
  File "/opt/tensor2tensor/1.2.1/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/opt/tensorflow/1.3.0/cuDNN/5.1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/opt/tensor2tensor/1.2.1/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 305, in run
    experiment_fn=exp_fn, schedule=schedule, output_dir=output_dir)
  File "/opt/tensorflow/1.3.0/cuDNN/5.1/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 200, in run
    experiment = experiment_fn(output_dir=output_dir)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 140, in experiment_fn
    eval_steps=eval_steps)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 149, in create_experiment
    FLAGS.hparams_set, FLAGS.problems, data_dir, passed_hparams=FLAGS.hparams)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 270, in create_hparams
    return add_problem_hparams(hparams, problems)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 240, in add_problem_hparams
    p_hparams = problem.internal_hparams(hparams)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 242, in internal_hparams
    self.internal_build_encoders(model_hparams.data_dir)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 237, in internal_build_encoders
    self._encoders = self.feature_encoders(data_dir)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 426, in feature_encoders
    encoder = text_encoder.SubwordTextEncoder(vocab_filename)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 364, in __init__
    self._load_from_file(filename)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 674, in _load_from_file
    self._load_from_file_object(f)
  File "/opt/tensor2tensor/1.2.1/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 657, in _load_from_file_object
    for line in f:
  File "/opt/tensorflow/1.3.0/cuDNN/5.1/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 207, in next
    retval = self.readline()
  File "/opt/tensorflow/1.3.0/cuDNN/5.1/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 176, in readline
    self._preread_check()
  File "/opt/tensorflow/1.3.0/cuDNN/5.1/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/opt/python/2.7.11/gnu/4.9.3/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/opt/tensorflow/1.3.0/cuDNN/5.1/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /data/t2t/data/vocab.lm1b.en.32768
```
I am not sure if it's a simple typo in the [naming of the vocab](https://github.com/tensorflow/tensor2tensor/blob/24071ba07d5a14c170044c5e60a24bda8179fb7a/tensor2tensor/data_generators/lm1b.py#L173) or if the problem is that the actual vocab is never created by the generator function.

**Comment by rsepassi** [comment]
I believe this has been fixed.
