### ISSUE TITLE
algorithmic_reverse_decimal40 with baseline_lstm_seq2seq model produce Error NaN

### ISSUE THREAD

**Issue by ReDeiPirati** [tensorflow/tensor2tensor#31]
### Steps to reproduce
Before training on a new generator(nlplike) i have tried to train on the **baseline_lstm_seq2seq** model to see how it works on the `algorithmic_reverse_decimal40`, this is the result(i am inside a Docker container):
```bash
root@df1a91a7be96:/t2t# PROBLEM=algorithmic_reverse_decimal40
root@df1a91a7be96:/t2t# MODEL=baseline_lstm_seq2seq
root@df1a91a7be96:/t2t# HPARAMS=basic_1
root@df1a91a7be96:/t2t# DATA_DIR=/tmp/t2t_data
root@df1a91a7be96:/t2t# TMP_DIR=/tmp/t2t_datagen
root@df1a91a7be96:/t2t# TRAIN_DIR=/tmp/t2t_train/$PROBLEM/$MODEL-$HPARAMS
root@df1a91a7be96:/t2t# mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR
root@df1a91a7be96:/t2t# # Generate data
root@df1a91a7be96:/t2t# t2t-datagen \
>   --data_dir=$DATA_DIR \
>   --tmp_dir=$TMP_DIR \
>   --problem=$PROBLEM

INFO:tensorflow:Generating training data for algorithmic_reverse_decimal40.
INFO:tensorflow:Generating case 0 for algorithmic_reverse_decimal40-unshuffled-train.
INFO:tensorflow:Generating development data for algorithmic_reverse_decimal40.
INFO:tensorflow:Generating case 0 for algorithmic_reverse_decimal40-unshuffled-dev.
INFO:tensorflow:Shuffling data...
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
INFO:tensorflow:read: 10000
INFO:tensorflow:write: 0
root@df1a91a7be96:/t2t# 
root@df1a91a7be96:/t2t# t2t-trainer \
>   --data_dir=$DATA_DIR \
>   --problems=$PROBLEM \
>   --model=$MODEL \
>   --hparams_set=$HPARAMS \
>   --output_dir=$TRAIN_DIR
INFO:tensorflow:Creating experiment, storing model files in /tmp/t2t_train/algorithmic_reverse_decimal40/baseline_lstm_seq2seq-basic_1
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': '/tmp/t2t_train/algorithmic_reverse_decimal40/baseline_lstm_seq2seq-basic_1', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fdc4e2b5390>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_session_config': allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
}
INFO:tensorflow:Performing local training.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Doing model_fn_body took 0.668 sec.
INFO:tensorflow:This model_fn took 0.983 sec.
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_2/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_2/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_3/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/decoder/rnn/multi_rnn_cell/cell_3/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_2/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_2/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_3/basic_lstm_cell/bias        	shape    (256,)              	size    256
INFO:tensorflow:Weight    body/lstm_seq2seq/encoder/rnn/multi_rnn_cell/cell_3/basic_lstm_cell/kernel      	shape    (128, 256)          	size    32768
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_0                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_10                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_11                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_12                                      	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_13                                      	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_14                                      	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_15                                      	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_1                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_2                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_3                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_4                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_5                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_6                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_7                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_8                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/input_emb/weights_9                                       	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_0                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_10                                        	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_11                                        	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_12                                        	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_13                                        	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_14                                        	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_15                                        	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_1                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_2                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_3                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_4                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_5                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_6                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_7                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_8                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/softmax/weights_9                                         	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_0                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_10                                     	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_11                                     	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_12                                     	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_13                                     	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_14                                     	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_15                                     	shape    (0, 64)             	size    0
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_1                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_2                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_3                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_4                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_5                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_6                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_7                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_8                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Weight    symbol_modality_12_64/target_emb/weights_9                                      	shape    (1, 64)             	size    64
INFO:tensorflow:Total trainable variables size: 266496
INFO:tensorflow:Total embedding variables size: 0
INFO:tensorflow:Total non-embedding variables size: 266496
INFO:tensorflow:Computing gradients for global model_fn.
INFO:tensorflow:Global model_fn finished.
INFO:tensorflow:Create CheckpointSaverHook.
2017-06-23 11:14:29.014420: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 11:14:29.014488: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 11:14:29.014519: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-23 11:14:29.076780: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-06-23 11:14:29.077245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 670MX
major: 3 minor: 0 memoryClockRate (GHz) 0.601
pciBusID 0000:01:00.0
Total memory: 2.94GiB
Free memory: 2.62GiB
2017-06-23 11:14:29.077338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-06-23 11:14:29.077374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-06-23 11:14:29.084741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 670MX, pci bus id: 0000:01:00.0)
2017-06-23 11:14:38.368302: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 5370 get requests, put_count=3301 evicted_count=1000 eviction_rate=0.302939 and unsatisfied allocation rate=0.59013
2017-06-23 11:14:38.368375: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:Saving checkpoints for 1 into /tmp/t2t_train/algorithmic_reverse_decimal40/baseline_lstm_seq2seq-basic_1/model.ckpt.
ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 240, in run
    run_locally(exp_fn(output_dir))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 531, in run_locally
    exp.train()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1007, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 960, in run
    run_metadata=run_metadata))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 477, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```
I have missed something during configuration? I have also tried the same problem on the transformer model and the training seems fine, but during inference it doesn't reproduce reverse input!!!(Later i'll post the output of this last command and my configuration). 

Edit: With transformer everything is ok.

**Comment by ReDeiPirati** [comment]
After the update to v1.0.7 it works!! 
I close.
