### ISSUE TITLE
custom model that runs in training fails in decoding

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#313]
Hi i previously trained a custom model, change minor adaptation in the transformer framework, and i got the trace below, it seems initialization is not doing right in the t2t-decoder. would be great to know what causes the problem, since it trains perfectly.

`Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-decoder", line 90, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-decoder", line 76, in main
    decoding.decode_from_file(estimator, FLAGS.decode_from_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\decoding.py", line 191, in decode_from_file
    for result in result_iter:
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 340, in predict
    model_fn_lib.ModeKeys.PREDICT)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 615, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\model_builder.py", line 269, in model_fn
    len(my_hp.problems) - 1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\input_fn_builder.py", line 199, in cond_on_index
    return fn(cur_idx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\model_builder.py", line 225, in nth_model
    decode_length=FLAGS.decode_extra_length)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 211, in infer
    last_position_only, alpha)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 269, in _beam_decode
    alpha)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\beam_search.py", line 406, in beam_search
    back_prop=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\beam_search.py", line 337, in inner_loop
    i, alive_seq, alive_log_probs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\beam_search.py", line 241, in grow_topk
    flat_logits = symbols_to_logits_fn(flat_ids)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 239, in symbols_to_logits_fn
    features, False, last_position_only=last_position_only)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 474, in model_fn
    transformed_features)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 527, in model_fn_body_sharded
    datashard_to_features)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\expert_utils.py", line 213, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 40, in fn_with_timing
    res = fn(*args, **kwargs)
  File "L:/python34_colman/projects/trans/usr\t2t_usr\transformer_aug.py", line 50, in model_fn_body
    inputs=forenetwork(inputs,hparams)
  File "L:/python34_colman/projects/trans/usr\t2t_usr\transformer_aug.py", line 262, in forenetwork
    return fc(inputs,hparams)
  File "L:/python34_colman/projects/trans/usr\t2t_usr\transformer_aug.py", line 149, in fc
    b = tf.Variable(tf.constant(0,dtype=tf.float32,shape=[filter]), name="b")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 296, in _init_from_args
    "initializer." % name)
ValueError: Initializer for variable while/body/model/parallel_0/body/conv-filter-0/b/ is from inside a control-flow construct, such as a loop or conditional. When creating a variable inside a loop or conditional, use a lambda as the initializer.`

**Comment by lukaszkaiser** [comment]
Please, make sure all your initializers are functions, not constants. I mean: `initializer=tf.constant(2.4)` is dangerous: it'll work outside of loops, but will crash in a loop (e.g., in decoding). This is a general TF issue, and the best workaround is to make it a function. As in, the above would become sth like `initializer=lambda _: tf.constant(2.4)`. Please try and let us know if that helps!

**Comment by colmantse** [comment]
hi, sorry, I figured out I should use tf.get_variables() instead. so the decoder has moved past this line already, but seems not able to detect changes that occurs in loop, but for this issue, should be settled. Thank you.
