### ISSUE TITLE
Greedy decoding raises an error

### ISSUE THREAD

**Issue by vince62s** [tensorflow/tensor2tensor#320]
command line is as follow:
t2t-decoder --data_dir=t2t/data --problems=translate_ende_wmt32k --model=transformer \
  --hparams_set=transformer_base_single_gpu --output_dir=t2t/train_ende --decode_hparams=beam_size=1 \
  --decode_alpha=0.6 --decode_from_file=$testset-src.$sl --decode_to_file=$testset-tra.$tl

here it goes:
INFO:tensorflow:decode_hp.batch_size not specified; default=32
INFO:tensorflow:Performing decoding from a file.
INFO:tensorflow:Getting sorted inputs
INFO:tensorflow: batch 94
INFO:tensorflow:Decoding batch 0
WARNING:tensorflow:Input graph does not contain a QueueRunner. That means predict yields forever. This is probably a mistake.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Greedy Decoding
Traceback (most recent call last):
  File "/usr/local/bin/t2t-decoder", line 99, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-decoder", line 91, in main
    FLAGS.decode_to_file)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/decoding.py", line 221, in decode_from_file
    for result in result_iter:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 340, in predict
    model_fn_lib.ModeKeys.PREDICT)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 615, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/model_builder.py", line 348, in wrapping_model_fn
    return model_fn(model, features, mode, hparams, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/model_builder.py", line 163, in model_fn
    max_idx=len(hparams.problems) - 1)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 192, in cond_on_index
    flat_out = wrapped_fn()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 187, in wrapped_fn
    out = fn(cur_idx)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/model_builder.py", line 119, in nth_model
    decode_length=decode_hp.extra_length)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/t2t_model.py", line 207, in infer
    last_position_only)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/models/transformer.py", line 167, in _greedy_infer
    raise ValueError("Fast decoding only deals with the last positions!")
ValueError: Fast decoding only deals with the last positions!

**Comment by vince62s** [comment]
vince62s @vince62s 08:24
@lukaszkaiser any clue how to solve #320 ?

Lukasz Kaiser @lukaszkaiser 08:43
For now to use fast decoding you need to set the hparam to only use last softmax position
In decode_hparams set use_last_position_only to true (we need to make it the default for SymbolModality at some point, for now it's a decode hparam).

vince62s @vince62s 08:47
ok thanks, I'll copy this in the issue and close it.
_

**Comment by twairball** [comment]
I'm unable to get `use_last_position_only=True` working, on t2t version 1.2.4:

````
$ t2t-decoder   --t2t_usr_dir=./data_generators   --data_dir=$DATA_DIR   --problems=$PROBLEM   --model=$MODEL   --hparams_set=$HPARAMS   --output_dir=$TRAIN_DIR   --decode_hparams="beam_size=0,alpha=$ALPHA,use_last_position_only=True"   --decode_from_file=$DECODE_FILE
INFO:tensorflow:Importing user module data_generators from path .
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/user/1000/jieba.cache
Loading model cost 0.293 seconds.
Prefix dict has been built succesfully.
INFO:tensorflow:Creating experiment, storing model files in train/wmt17
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': 'train/wmt17', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fd6af95d8d0>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_log_step_count_steps': 100}
INFO:tensorflow:decode_hp.batch_size not specified; default=32
INFO:tensorflow:Performing decoding from a file.
INFO:tensorflow:Getting sorted inputs
INFO:tensorflow: batch 63
INFO:tensorflow:Decoding batch 0
WARNING:tensorflow:Input graph does not contain a QueueRunner. That means predict yields forever. This is probably a mistake.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Beam Decoding with beam size 0
INFO:tensorflow:Doing model_fn_body took 3.245 sec.
INFO:tensorflow:This model_fn took 3.418 sec.
Traceback (most recent call last):
  File "/usr/local/bin/t2t-decoder", line 102, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-decoder", line 91, in main
    FLAGS.decode_to_file)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/decoding.py", line 219, in decode_from_file
    for result in result_iter:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 340, in predict
    model_fn_lib.ModeKeys.PREDICT)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 615, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/model_builder.py", line 348, in wrapping_model_fn
    return model_fn(model, features, mode, hparams, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/model_builder.py", line 163, in model_fn
    max_idx=len(hparams.problems) - 1)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 190, in cond_on_index
    flat_out = wrapped_fn()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 185, in wrapped_fn
    out = fn(cur_idx)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/model_builder.py", line 119, in nth_model
    decode_length=decode_hp.extra_length)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/t2t_model.py", line 211, in infer
    last_position_only, alpha)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/t2t_model.py", line 279, in _beam_decode
    alpha)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/beam_search.py", line 434, in beam_search
    back_prop=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2585, in _BuildLoop
    _EnforceShapeInvariant(m_var, n_var)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 575, in _EnforceShapeInvariant
    % (merge_var.name, m_shape, n_shape))
ValueError: The shape for while/Merge_2:0 is not an invariant for the loop. It enters the loop with shape (?, 1), but has shape (?, 0) after one iteration. Provide shape invariants using either the `shape_invariants` argument of tf.while_loop or set_shape() on the loop variables.
````
