### ISSUE TITLE
Cannot train any problem with version 1.2.3

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#321]
After releasing the new version, I gave it a try because I had an [issue #311](https://github.com/tensorflow/tensor2tensor/issues/311) with version 1.2.2. However, I am now facing another issue, and I cannot train any problem now.

I really hope that you release a working version, without a lot of issues soon, because my students depend now in tensor2tensor.

Versions:
Tensorflow 1.3
Tensor2tensor 1.2.3

Command:
Any training problem like:
`t2t-trainer   --data_dir=~/t2t_data    --problems=image_cifar10   --model=multimodel   --hparams_set=multimodel_tiny    --output_dir=~/t2t_train/multimodel_tiny_img`

Output:
```
Traceback (most recent call last):
  File "/home/ahmed/tensorflow/bin/t2t-trainer", line 94, in <module>
    tf.app.run()
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ahmed/tensorflow/bin/t2t-trainer", line 90, in main
    schedule=FLAGS.schedule)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 351, in run
    hparams=hparams)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 620, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 362, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 801, in _call_train
    hooks=hooks)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 256, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 647, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 517, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 603, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 104, in input_fn
    name="problem_%d" % problem_idx)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 235, in features_for_problem
    batching_scheme)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/utils/data_reader.py", line 230, in input_pipeline
    padded_shapes=batching_scheme["padded_shapes"])
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/utils/data_reader.py", line 320, in bucket_by_sequence_length
    None, window_size_fn))
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 2780, in group_by_window
    return GroupByWindowDataset(dataset, key_func, reduce_func, window_size_func)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 2646, in __init__
    self._make_key_func(key_func, input_dataset)
  File "/home/ahmed/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 2669, in _make_key_func
    @function.Defun(*nest.flatten(input_dataset.output_types))
AttributeError: 'function' object has no attribute 'output_types'
```

**Comment by rsepassi** [comment]
Please try again in v1.2.4. The travis tests now include training and decoding with the Transformer model and a dummy dataset so essential functionality should be more stable.

**Comment by rsepassi** [comment]
Please reopen if there’s still an issue.
