### ISSUE TITLE
Cannot Decode: ModuleNotFoundError: No module named 'tensorflow.contrib.hooks.python'

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#324]
Dear all, 
Would be great if someone could help, many thanks!

Tensor2tensor 1.2.3, tensorflow 1.3.0, window 10

tried reinstall with pip install -e link #egg=tensor2tensor  as well, same issue.
it looks like this is my version of tensorflow not working?

Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-decoder", line 41, in <module>
    from tensor2tensor.utils import trainer_utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 37, in <module>
    from tensorflow.contrib.hooks.python.training.profiler_hook import ProfilerHook
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\hooks\__init__.py", line 25, in <module>
    from tensorflow.contrib.hooks.python.training import *
ModuleNotFoundError: No module named 'tensorflow.contrib.hooks.python'

**Comment by colmantse** [comment]
this is a simple import error, for quick fix just remove the line. Thanks @lukaszkaiser .
