### ISSUE TITLE
Failed to train multimodel with different modality (V1.2.4)

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#338]
Software:
tensor2tensor (1.2.4)
tensorflow-gpu (1.3.0)

Hardware:
DGX-1

The new version doesn't train the multimodal algorithm using different modalities. It only works if all the problems were text for example, but if I tried to combine text problem and image problem it doesn't work.

Text only based problems works fine:-
Command:
`t2t-trainer   --data_dir=~/t2t_data   --TMP_DIR=~/tmp/t2t_datagen   --problems=languagemodel_wiki_full32k-programming_desc2code_py-sentiment_imdb-translate_encs_wmt32k-translate_encs_wmt32k_rev-translate_ende_wmt32k-translate_ende_wmt32k_rev-translate_enfr_wmt32k-translate_enfr_wmt32k_rev   --model=multi_model   --hparams_set=multimodel_tiny --output_dir=~/t2t_train/multimodel_tiny_all_txt`

However, after combining image based modality problem, it doesn't work:-

Command 1:
`t2t-trainer   --data_dir=~/t2t_data   --TMP_DIR=~/tmp/t2t_datagen   --problems=image_ms_coco_tokens32k-languagemodel_wiki_full32k-programming_desc2code_py-sentiment_imdb-translate_encs_wmt32k-translate_encs_wmt32k_rev-translate_ende_wmt32k-translate_ende_wmt32k_rev-translate_enfr_wmt32k-translate_enfr_wmt32k_rev   --model=multi_model   --hparams_set=multimodel_tiny --output_dir=~/t2t_train/multimodel_tiny_all`

Result 1:
```
Traceback (most recent call last):
  File "/home/ahmed/tensor2tensorp3/bin/t2t-trainer", line 96, in <module>
    tf.app.run()
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ahmed/tensor2tensorp3/bin/t2t-trainer", line 92, in main
    schedule=FLAGS.schedule)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensor2tensor/utils/trainer_utils.py", line 352, in run
    hparams=hparams)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 209, in run
    return _execute_schedule(experiment, schedule)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 672, in _call_train
    hooks=hooks)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 628, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 499, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 585, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensor2tensor/utils/input_fn_builder.py", line 122, in input_fn
    problem_count - 1)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensor2tensor/utils/input_fn_builder.py", line 185, in cond_on_index
    lambda: cond_on_index(fn, index_tensor, max_idx, cur_idx + 1)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/home/ahmed/tensor2tensorp3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1846, in cond
    "Incompatible return values of true_fn and false_fn: {}".format(e))
ValueError: Incompatible return values of true_fn and false_fn: The two structures don't have the same number of elements.

First structure (3 elements): {'target_space_id': <tf.Tensor 'input_fn/Const:0' shape=() dtype=int32>, 'inputs': <tf.Tensor 'input_fn/problem_0/input_pipeline/IteratorGetNext:0' shape=(?, ?, ?, ?) dtype=int32>, 'targets': <tf.Tensor 'input_fn/ExpandDims_1:0' shape=(?, ?, 1, 1) dtype=int32>}

Second structure (4 elements): {'input_space_id': <tf.Tensor 'cond/cond/Merge:0' shape=() dtype=int32>, 'target_space_id': <tf.Tensor 'cond/cond/Merge_2:0' shape=() dtype=int32>, 'inputs': <tf.Tensor 'cond/cond/Merge_1:0' shape=(?, ?, 1, 1) dtype=int32>, 'targets': <tf.Tensor 'cond/cond/Merge_3:0' shape=(?, ?, 1, 1) dtype=int32>}
```

Command 2:
`t2t-trainer   --data_dir=~/t2t_data   --TMP_DIR=~/tmp/t2t_datagen   --problems=image_cifar10-languagemodel_wiki_full32k-programming_desc2code_py-sentiment_imdb-translate_encs_wmt32k-translate_encs_wmt32k_rev-translate_ende_wmt32k-translate_ende_wmt32k_rev-translate_enfr_wmt32k-translate_enfr_wmt32k_rev   --model=multi_model   --hparams_set=multimodel_tiny --output_dir=~/t2t_train/multimodel_tiny_all`

Result 2:
```
Traceback (most recent call last):
  File "/home/ahmed/tensor2tensor/bin/t2t-trainer", line 96, in <module>
    tf.app.run()
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ahmed/tensor2tensor/bin/t2t-trainer", line 92, in main
    schedule=FLAGS.schedule)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 352, in run
    hparams=hparams)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 209, in run
    return _execute_schedule(experiment, schedule)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 672, in _call_train
    hooks=hooks)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 628, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 499, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 585, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 122, in input_fn
    problem_count - 1)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 185, in cond_on_index
    lambda: cond_on_index(fn, index_tensor, max_idx, cur_idx + 1)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1828, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1694, in BuildCondBranch
    original_result = fn()
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 185, in <lambda>
    lambda: cond_on_index(fn, index_tensor, max_idx, cur_idx + 1)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 185, in cond_on_index
    lambda: cond_on_index(fn, index_tensor, max_idx, cur_idx + 1)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/home/ahmed/tensor2tensor/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1866, in cond
    (val_x.dtype.name, val_y.dtype.name))
ValueError: Outputs of true_fn and false_fn must have the same type: uint8, int32
```

**Comment by agemagician** [comment]
This is still a problem with version 1.2.6.
Any idea when you are going to fix it ?

**Comment by agemagician** [comment]
The problem still exists with version 1.2.7
@lukaszkaiser Any plans for fixing this issue ?

**Comment by rsepassi** [comment]
See #413
