### ISSUE TITLE
Attempt to employ get_or_generate_vocab in custom manner, enzh single vocab 8k, failed

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#350]
Hi all,

I am trying to use single vocab implementation for enzh datasets, following ende's implementation instead of the current wmt8k enzh implementation (bivocab). I don't quite get how two '/' is added at the end of the tmp_dir. stack trace as follow:

```
INFO:tensorflow:Generating data for translate_enzh_ai8k.
INFO:tensorflow:Data_dir: L:/python34_colman/projects/trans/t2t_data
INFO:tensorflow:tmp_dir: L:/python34_colman/projects/trans/tmp/t2t_datagen
INFO:tensorflow:Generating vocab file: L:/python34_colman/projects/trans/t2t_data\vocab.zhen.8192
INFO:tensorflow:Generating vocab from: [['', ('training/translation_train_20170912/train.zh', 'training/translation_train_20170912/train.en')]]
INFO:tensorflow:Not downloading, file already found: L:/python34_colman/projects/trans/tmp/t2t_datagen\
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-datagen", line 213, in <module>
    tf.app.run()
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-datagen", line 179, in main
    generate_data_for_registered_problem(problem)
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-datagen", line 209, in generate_data_for_registered_problem
    task_id=task_id)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\problem.py", line 418, in generate_data
    self.generator(data_dir, tmp_dir, True), train_paths,
  File "L:/python34_colman/projects/trans/usr\t2t_usr\data_add_param.py", line 345, in generator
    data_dir, tmp_dir, self.vocab_file, self.targeted_vocab_size, datasets)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\generator_utils.py", line 386, in get_or_generate_vocab
    data_dir, vocab_filename, vocab_size, generator_fn=generate)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\generator_utils.py", line 328, in get_or_generate_vocab_inner
    for item in generator_fn():
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\data_generators\generator_utils.py", line 357, in generate
    with tarfile.open(compressed_file, read_type) as corpus_tar:
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\tarfile.py", line 1559, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\tarfile.py", line 1624, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
OSError: [Errno 22] Invalid argument: 'L:/python34_colman/projects/trans/tmp/t2t_datagen\\'
```

codes:

```
@registry.register_problem
class TranslateEnzhAi8k(wmt.TranslateProblem):
  """"Problem spec for AI subword translation"""

  @property
  def targeted_vocab_size(self):
    return 2**13

  @property
  def num_shards(self):
    return 10

  @property
  def vocab_name(self):
    return "vocab.zhen"

  def generator(self, data_dir, tmp_dir, train):
    import tensorflow as tf
    tf.logging.info("Data_dir: %s", str(data_dir))
    tf.logging.info("tmp_dir: %s", str(tmp_dir))
    datasets = _AI_ENZH_TRAIN_DATASETS if train else _AI_ENZH_TEST_DATASETS
    symbolizer_vocab = generator_utils.get_or_generate_vocab(
        data_dir, tmp_dir, self.vocab_file, self.targeted_vocab_size, datasets)
    tag = "train" if train else "dev"
    data_path = _compile_data(tmp_dir, datasets, "ai_enzh_tok_%s" % tag)
    return token_generator(data_path + ".lang1", data_path + ".lang2",
                           symbolizer_vocab, EOS)

  @property
  def input_space_id(self):
    return problem.SpaceID.ZH_TOK

  @property
  def target_space_id(self):
    return problem.SpaceID.EN_TOK
```

**Comment by colmantse** [comment]
Figure using pip to install tensor2tensor 1.2.4 is not exactly as update as this repo. Using own dataset for subword model might yield error. Uninstalled tensor2tensor, and use pip to install directly via git did the job.
