### ISSUE TITLE
Cannot run parsing task

### ISSUE THREAD

**Issue by sensus-sextus** [tensorflow/tensor2tensor#403]
When trying to launch any of parsing problems, it always crashes
For example following output when trying to generate data 
for  ptb8k problem

`
```
INFO:tensorflow:Generating problems:
    parsing:
      * parsing_english_ptb8k
      * parsing_english_ptb8k
INFO:tensorflow:Generating training data for parsing_english_ptb8k.
Traceback (most recent call last):
  File "/usr/local/bin/t2t-datagen", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-datagen", line 177, in main
    generate_data_for_problem(problem)
  File "/usr/local/bin/t2t-datagen", line 190, in generate_data_for_problem
    generator_utils.generate_files(training_gen(), train_output_files,
  File "/usr/local/bin/t2t-datagen", line 85, in <lambda>
    lambda: translate.parsing_token_generator(
AttributeError: module 'tensor2tensor.data_generators.translate' has no attribute 'parsing_token_generator'

```
`
please help!
Thank you

**Comment by rsepassi** [comment]
Thanks for reporting this. Will have a fix in the next release.
