### ISSUE TITLE
translate_enzh_wmt8k_rev didn't support

### ISSUE THREAD

**Issue by beichao1314** [tensorflow/tensor2tensor#467]
Hi， everyone. Is there anyone who have train a Chinese to English transformer model? When running data generation, translate_enzh_wmt8k_rev didn't support.
```
beichao@ubuntu16:~/train/enzh_3k5_1119/t2t-zhen$ ~/anaconda2/bin/t2t-datagen --data_dir=./datagen/ --tmp_dir=./data --problem=translate_enzh_wmt8k_rev
Traceback (most recent call last):
  File "/home/beichao/anaconda2/bin/t2t-datagen", line 4, in <module>
    __import__('pkg_resources').run_script('tensor2tensor==1.3.2', 't2t-datagen')
  File "/home/beichao/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/beichao/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/home/beichao/anaconda2/lib/python2.7/site-packages/tensor2tensor-1.3.2-py2.7.egg/EGG-INFO/scripts/t2t-datagen", line 212, in <module>
    tf.app.run()
  File "/home/beichao/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/beichao/anaconda2/lib/python2.7/site-packages/tensor2tensor-1.3.2-py2.7.egg/EGG-INFO/scripts/t2t-datagen", line 159, in main
    raise ValueError(error_msg)
ValueError: You must specify one of the supported problems to generate data for:
  * algorithmic_addition_binary40
  * algorithmic_addition_decimal40
  * algorithmic_algebra_inverse
  * algorithmic_cipher_shift200
  * algorithmic_cipher_shift5
  * algorithmic_cipher_vigenere200
  * algorithmic_cipher_vigenere5
  * algorithmic_identity_binary40
  * algorithmic_identity_decimal40
  * algorithmic_multiplication_binary40
  * algorithmic_multiplication_decimal40
  * algorithmic_reverse_binary40
  * algorithmic_reverse_binary40_test
  * algorithmic_reverse_decimal40
  * algorithmic_reverse_nlplike32k
  * algorithmic_reverse_nlplike8k
  * algorithmic_shift_decimal40
  * audio_timit_characters_test
  * audio_timit_characters_tune
  * audio_timit_tokens8k_test
  * audio_timit_tokens8k_tune
  * audio_timit_tokens_32k_test
  * audio_timit_tokens_8k_test
  * genomics_expression_cage10
  * genomics_expression_gm12878
  * genomics_expression_l262k
  * image_celeba_tune
  * image_cifar10
  * image_cifar10_plain
  * image_cifar10_plain8
  * image_cifar10_tune
  * image_fsns
  * image_imagenet
  * image_imagenet224
  * image_imagenet32
  * image_imagenet64
  * image_mnist
  * image_mnist_tune
  * image_ms_coco_characters
  * image_ms_coco_tokens32k
  * image_ms_coco_tokens8k
  * img2img_cifar10
  * img2img_imagenet
  * inference_snli32k
  * languagemodel_lm1b32k
  * languagemodel_lm1b8k_packed
  * languagemodel_lm1b_characters
  * languagemodel_ptb10k
  * languagemodel_ptb_characters
  * languagemodel_wiki_full32k
  * languagemodel_wiki_scramble128
  * languagemodel_wiki_scramble1k50
  * languagemodel_wiki_scramble8k50
  * librispeech
  * multinli_matched
  * multinli_mismatched
  * ocr_test
  * parsing_english_ptb16k
  * parsing_english_ptb16k
  * parsing_english_ptb8k
  * parsing_english_ptb8k
  * parsing_icelandic16k
  * programming_desc2code_cpp
  * programming_desc2code_py
  * sentiment_imdb
  * summarize_cnn_dailymail32k
  * translate_encs_wmt32k
  * translate_encs_wmt_characters
  * translate_ende_wmt32k
  * translate_ende_wmt32k_packed
  * translate_ende_wmt8k
  * translate_ende_wmt_bpe32k
  * translate_ende_wmt_characters
  * translate_enfr_wmt32k
  * translate_enfr_wmt32k_packed
  * translate_enfr_wmt8k
  * translate_enfr_wmt_characters
  * translate_enfr_wmt_small32k
  * translate_enfr_wmt_small8k
  * translate_enfr_wmt_small_characters
  * translate_enmk_setimes32k
  * translate_enzh_wmt8k
TIMIT and parsing need data_sets specified with --timit_paths and --parsing_path.
```

**Comment by martinpopel** [comment]
You must generate data for translate_enzh_wmt8k, but then train translate_enzh_wmt8k_rev.

**Comment by beichao1314** [comment]
Thanks a lot @martinpopel, it works. 👍
