### ISSUE TITLE
[question] Librispeech + Multimodel not working

### ISSUE THREAD

**Issue by ricardokleinklein** [tensorflow/tensor2tensor#474]
I am trying to run the model multi_model on the Librispeech task using tensor2tensor(1.3.2). However, is shows the following error: 
`AttributeError: 'HParams' object has no attribute 'audio_compression'`
when starting to train. The following is the complete log:
```bash
(multimodel)v-ricardo@gpu08:/work/smg/v-ricardo/EXPERIMENTS/multimodel$ bash run_speech_enhancement.sh 
INFO:tensorflow:Generating problems:
    librispeech:
      * librispeech
INFO:tensorflow:Generating data for librispeech.
INFO:tensorflow:Not downloading, file already found: /work/smg/v-ricardo/EXPERIMENTS/multimodel/tmp/train-clean-100.tar.gz
INFO:tensorflow:Downloading http://www.openslr.org/resources/12/dev-clean.tar.gz to /work/smg/v-ricardo/EXPERIMENTS/multimodel/tmp/dev-clean.tar.gz
100% completed
INFO:tensorflow:Successfully downloaded dev-clean.tar.gz, 337926286 bytes.
INFO:tensorflow:Shuffling data...
run_speech_enhancement.sh: line 18: R: command not found
WARNING:tensorflow:uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:Creating experiment, storing model files in /work/smg/v-ricardo/EXPERIMENTS/multimodel/t2t_train/librispeech/multi_model-multimodel_tiny
WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': '/work/smg/v-ricardo/EXPERIMENTS/multimodel/t2t_train/librispeech/multi_model-multimodel_tiny', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f2bcf2a7d90>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_log_step_count_steps': 100}
WARNING:tensorflow:From /work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:267: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
WARNING:tensorflow:uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:batching_scheme = {'min_length': 0, 'window_size': 360, 'shuffle_queue_size': 1080, 'boundaries': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 33, 36, 39, 42, 46, 50, 55, 60, 66, 72, 79, 86, 94, 103, 113, 124, 136, 149, 163, 179, 196, 215, 236, 259, 284, 312, 343, 377, 414, 455, 500, 550, 605, 665, 731, 804, 884, 972], 'max_length': 1024, 'batch_sizes': [120, 90, 90, 90, 72, 72, 72, 60, 60, 60, 45, 45, 45, 45, 40, 36, 36, 30, 30, 24, 24, 24, 20, 20, 18, 15, 15, 12, 12, 10, 10, 9, 9, 8, 6, 6, 6, 5, 5, 4, 4, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]}
INFO:tensorflow:Reading data files from /work/smg/v-ricardo/EXPERIMENTS/multimodel/data/librispeech/librispeech-train*
WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
Traceback (most recent call last):
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/bin/t2t-trainer", line 108, in <module>
    tf.app.run()
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/bin/t2t-trainer", line 104, in main
    run_experiment()
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/bin/t2t-trainer", line 94, in run_experiment
    schedule=FLAGS.schedule)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 385, in run
    hparams=hparams)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 625, in train_and_evaluate
    self.train(delay_secs=0)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 367, in train
    hooks=self._train_monitors + extra_hooks)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
    hooks=hooks)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/model_builder.py", line 334, in wrapping_model_fn
    return model_fn(model, features, mode, hparams, **kwargs)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/model_builder.py", line 163, in model_fn
    max_idx=len(hparams.problems) - 1)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/input_fn_builder.py", line 182, in cond_on_index
    return fn(cur_idx)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/model_builder.py", line 131, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 697, in call
    inputs_dict, skip=skip, force_full_predict=force_full_predict)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 571, in _model_fn
    sharded_features[key], dp)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/modality.py", line 128, in bottom_sharded
    return data_parallelism(self.bottom, xs)
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/utils/expert_utils.py", line 251, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/work/smg/v-ricardo/EXPERIMENTS/multimodel/local/lib/python2.7/site-packages/tensor2tensor/data_generators/librispeech.py", line 204, in bottom
    for i in xrange(self._model_hparams.audio_compression):
AttributeError: 'HParams' object has no attribute 'audio_compression'
```
Although `audio_compression` is explicitly defined in the script, it seems t2t is not correctly reading the additional hparams. Any idea what could be causing this?

Thank you very much

**Comment by rsepassi** [comment]
It seems that the `LibrispeechModality` expects the hparams to have `audio_compression`, so you'll have to add it to the hparams you're using. See the [hparams](https://github.com/tensorflow/tensor2tensor/blob/5c8009561c4604be53e27310d0014ce69176c5db/tensor2tensor/data_generators/librispeech.py#L314) that were added in the PR.
