### ISSUE TITLE
InvalidArgumentError: The node 'Merge/MergeSummary' has inputs from different frames.

### ISSUE THREAD

**Issue by apeterswu** [tensorflow/tensor2tensor#491]
Hi,

I am trying to implement reinforcement learning for translation task, which needs online sampling y' for source sentence x and then calculate bleu score between y' and y.
What I am doing is to add: 

``
samples, _, _ = model_class._slow_greedy_infer(features)
``

in train mode when build model (it seems that _fast_decode  doesn't support if there are multiple data shards, so I use _slow_greedy_infer). And then call model_class.model_fn( ). basically, it likes this: 

`samples, _, _ = model_class._slow_greedy_infer(features, decode_length=50)`
`train_metric_fn = metrics.METRICS_FNS[metrics.Metrics.APPROX_BLEU_TRAIN]`
`labels = features.get("targets", None) `
`scores, weights = train_metric_fn(samples, labels)`
`metric_value, metric_update = tf.metrics.mean(scores, weights)`
`features["samples"] = samples`
`sharded_logits, losses_dict = model_class.model_fn(features, skip=(skipping_is_on and skip_this_one))`

However, I met the problem shows like this:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'Merge/MergeSummary' has inputs from different frames. The input 'while/body/model/parallel_0/body/decoder/layer_5/encdec_attention/multihead_attention/dot_product_attention/attention' is in frame 'while/while/'. The input 'training/loss' is in frame ''.`
 I guess it may caused by "while_loop" function in _slow_greedy_infer in t2t_model.py, but I am not sure, anyone could help me on this? 

Thanks and appreciate a lot. 

-----------------------------------------------------------------------------------------------
The full output is:
`
Traceback (most recent call last):
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/lijun/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'Merge/MergeSummary' has inputs from different frames. The input 'while/body/model/parallel_0/body/decoder/layer_5/encdec_attention/multihead_attention/dot_product_attention/attention' is in frame 'while/while/'. The input 'training/loss' is in frame ''.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lijun/transformer_rl/tensor2tensor/bin/t2t-trainer", line 96, in <module>
    tf.app.run()
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/lijun/transformer_rl/tensor2tensor/bin/t2t-trainer", line 92, in main
    schedule=FLAGS.schedule)
  File "/home/lijun/transformer_rl/tensor2tensor/utils/trainer_utils.py", line 388, in run
    hparams=hparams)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 209, in run
    return _execute_schedule(experiment, schedule)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 672, in _call_train
    hooks=hooks)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 686, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/lijun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'Merge/MergeSummary' has inputs from different frames. The input 'while/body/model/parallel_0/body/decoder/layer_5/encdec_attention/multihead_attention/dot_product_attention/attention' is in frame 'while/while/'. The input 'training/loss' is in frame ''. `

**Comment by apeterswu** [comment]
By the way, is there any way to support _fast_decode for multiple datashards if I want to sample data during training? Thanks.

**Comment by rsepassi** [comment]
@apeterswu, open a separate issue please.

**Comment by rsepassi** [comment]
The problem is that within the while loops there are summary ops being created which you probably don't want since you won't be able to run all of the summaries during train/eval, which is what the error is complaining about. Usually when infer is being called, no summaries are being requested which is why it's usually not a problem.

You can remove the summaries from the summaries collection. Here's an [example](https://github.com/tensorflow/tensor2tensor/blob/c1cd87517cf12f6e0bb0089291466846fc1ac260/tensor2tensor/utils/t2t_model.py#L817) of removing all summaries (which you probably don't need to do; you can probably rm all summaries that have a name that starts with "while/").

**Comment by apeterswu** [comment]
@rsepassi Thanks for your reply. I will have a try. Besides, I will open a new issue about _fast_decode. Thanks.

**Comment by xmkang** [comment]
Hi, have you solved this problem? I encountered the same problem. Could you show me some details about the solution? Thank you!

**Comment by xmkang** [comment]
Hi, have you solved this problem? I encountered the same problem. Could you show me some details about the solution? Thank you!
