### ISSUE TITLE
t2t-insights-server won't start

### ISSUE THREAD

**Issue by mehmedes** [tensorflow/tensor2tensor#515]
Trying to decode with ```decode_interactive``` or running ```t2t-insights-server``` produces the following errors.

```decode_interactive```:
```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_decoder.py", line 105, in main
    decode(estimator, hp, decode_hp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_decoder.py", line 76, in decode
    decoding.decode_interactively(estimator, hparams, decode_hp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/decoding.py", line 343, in decode_interactively
    for result in result_iter:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 409, in predict
    input_fn, model_fn_lib.ModeKeys.PREDICT)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 567, in _get_features_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 663, in _call_input_fn
    return input_fn(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/decoding.py", line 339, in input_fn
    example = _interactive_input_tensor_to_features_dict(example, hparams)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/decoding.py", line 589, in _interactive_input_tensor_to_features_dict
    input_fn, feature_map["problem_choice"], len(hparams.problems) - 1)
KeyError: 'problem_choice'
```
Running ```decode_interactive``` as follows:
```
PROBLEM=translate_ende_wmt32k_packed
MODEL=transformer
HPARAMS=transformer_big_lr05_w2k_d999

DATA_DIR=$HOME/t2t_data
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS


t2t-decoder \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --decode_interactive
```

```t2t-insights-server```:
```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-insights-server", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-insights-server", line 12, in main
    server.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/insights/server.py", line 78, in main
    configuration = json.load(configuration_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 14 column 5 (char 498)
```

My config json looks like this:
```
  {
    "configuration": [{
      "source_language": "en",
      "target_language": "de",
      "label": "translate_ende_wmt32k_packed",
      "transformer": {
        "model": "transformer",
        "model_dir": "/home/mehmedes/t2t_train/translate_ende_wmt32k_packed/transformer-transformer_big_lr05_w2k_d999",
        "data_dir": "/home/mehmedes/t2t_data",
        "hparams": "",
        "hparams_set": "transformer_big_lr05_w2k_d999",
        "problems": "translate_ende_wmt32k_packed"
      },
    }]
    "language": [{
      "code": "en",
      "name": "English",
    },{
      "code": "de",
      "name": "German",
    }]
  }
```

The model was trained on ```1.4.1```. Continuing training the model with ```1.4.2``` works.

**Comment by mehmedes** [comment]
I'll test with the latest release (1.4.3) and reopen if needed.

**Comment by mehmedes** [comment]
Since 1.4.3 ```decode_interactive``` works again.
The ```t2t-insights-server``` still won't start.
```t2t-insights-server``` used to work in 1.4.1 when hparams could be passed as flags:
```
 t2t-insights-server \
   --t2t_data_dir=~/t2t_data \
   --t2t_model_dir=~/t2t_train \
   --problems=translate_ende_wmt32k_packed \
    --model=transformer \
    --hparams_set=transformer_big_lr05_w2k_d999 \
    --static_path=`pwd`/tensor2tensor/insights/polymer
```
 but with the configuration.json, it won't work with me.

**Comment by mehmedes** [comment]
There seems to be something wrong with commas in the README.
With the following json config, t2t-insights-server works with me:
```
{
	"configuration": [{
		"source_language": "en",
		"target_language": "de",
		"label": "translate_ende_wmt32k_packed",
		"transformer": {
			"model": "transformer",
			"model_dir": "/home/t2t_train/translate_ende_wmt32k_packed/transformer-transformer_big_adafactor",
			"data_dir": "/home/t2t_data",
			"hparams": "",
			"hparams_set": "transformer_big_adafactor",
			"problems": "translate_ende_wmt32k_packed"
		}
	}],
	"language": [{
		"code": "en",
		"name": "English"
	}, {
		"code": "de",
		"name": "German"
	}]
}
