### ISSUE TITLE
Decode issue at inference

### ISSUE THREAD

**Issue by rafaelbou** [tensorflow/tensor2tensor#579]
Hi all,
I'm working on the languagemodel_wiki_noref_v8k_l1k problem.
the configuration file for datagen, train and decode is:

  `PROBLEM=languagemodel_wiki_noref_v8k_l1k
MODEL=transformer
HPARAMS=transformer_base_v1

DATA_DIR=/home/razor22/PycharmProjects/TED_AI/t2t_wiki
TMP_DIR=/home/razor22/PycharmProjects/TED_AI/tmp/t2t_wiki
TRAIN_DIR=/home/razor22/PycharmProjects/TED_AI/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM

# Train
# *  If you run out of memory, add --hparams='batch_size=1024'.
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --hparams='batch_size=1024' \
  --output_dir=$TRAIN_DIR

# Decode
BEAM_SIZE=4
ALPHA=0.6

t2t-decoder \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --decode_hparams="beam_size=$BEAM_SIZE,alpha=$ALPHA"
`
*****************************************************************************************************
I trained the model, then, when decoding I get the following error:

`INFO:tensorflow:schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
INFO:tensorflow:sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 20, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4c8c613090>, '_keep_checkpoint_every_n_hours': 10000, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': 1234, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 1000, '_environment': 'local', '_master': '', '_model_dir': '/home/razor22/PycharmProjects/TED_AI/t2t_train/languagemodel_wiki_noref_v8k_l16k/transformer-transformer_base_v1', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f4c9784ad50>, '_save_summary_steps': 100}
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f4c922d0c80>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Performing local inference from dataset for ['languagemodel_wiki_noref_v8k_l1k'].
INFO:tensorflow:Reading data files from /home/razor22/PycharmProjects/TED_AI/t2t_wiki/languagemodel_wiki_noref_v8k_l1k-dev*
INFO:tensorflow:partition: 0 num_data_files: 1
INFO:tensorflow:Setting T2TModel mode to 'infer'
INFO:tensorflow:Setting hparams.layer_prepostprocess_dropout to 0.0
INFO:tensorflow:Setting hparams.symbol_dropout to 0.0
INFO:tensorflow:Setting hparams.attention_dropout to 0.0
INFO:tensorflow:Setting hparams.dropout to 0.0
INFO:tensorflow:Setting hparams.relu_dropout to 0.0
WARNING:tensorflow:Beam searching for a model with no inputs.
WARNING:tensorflow:Non-random sampling for a model with no inputs.
INFO:tensorflow:Beam Decoding with beam size 4
Traceback (most recent call last):
  File "/usr/local/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_decoder.py", line 114, in main
    decode(estimator, hp, decode_hp)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_decoder.py", line 96, in decode
    dataset_split="test" if FLAGS.eval_use_test_set else None)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/decoding.py", line 158, in decode_from_dataset
    for num_predictions, prediction in enumerate(predictions):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 423, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/t2t_model.py", line 788, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/t2t_model.py", line 833, in estimator_model_fn
    return model.estimator_spec_predict(features)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/t2t_model.py", line 919, in estimator_spec_predict
    decode_length=decode_hparams.extra_length)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/t2t_model.py", line 437, in infer
    features, decode_length, beam_size, top_beams, alpha)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/models/transformer.py", line 227, in _beam_decode
    features, decode_length, beam_size, top_beams, alpha)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/models/transformer.py", line 298, in _fast_decode
    partial_targets = tf.squeeze(tf.to_int64(features["inputs"]), [2, 3])
KeyError: 'inputs'`

*************************************************************************************************************
I've no clue why I get this error.
Can anyone help me to solve this issue?

**Comment by rasmi** [comment]
This is an issue with the language model code. If you modify `tensor2tensor/models/transformer.py` to have this line at the start of the `else` statement around line 295:
```
if 'inputs' not in features:
    features['inputs'] = features['targets']
```
It should work. Though this may have unintended consequences elsewhere in the code. @nshazeer, @rsepassi, is this an okay hack or is it better handled elsewhere?

**Comment by FreeAlex** [comment]
Hi Rasmi,

I have same issue with @rafaelbou. When I tried your solution of adding 2 lines here:
```
    else:
      if 'inputs' not in features:
        features['inputs'] = features['targets']
      # The problem has no inputs.
      # In this case, features["inputs"] contains partial targets.
      # We force the outputs to begin with these sequences.
      encoder_output = None
      encoder_decoder_attention_bias = None
```
It stop complain about missing 'inputs' but it complains about another issue. 
```
Traceback (most recent call last):
  File "/home/xiaonzha/.local/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/xiaonzha/.local/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/bin/t2t_decoder.py", line 187, in main
    decode(estimator, hp, decode_hp)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/bin/t2t_decoder.py", line 89, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/utils/decoding.py", line 267, in decode_from_file
    for result in result_iter:
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 411, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/utils/t2t_model.py", line 886, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/utils/t2t_model.py", line 931, in estimator_model_fn
    return model.estimator_spec_predict(features)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/utils/t2t_model.py", line 1052, in estimator_spec_predict
    decode_length=decode_hparams.extra_length)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/utils/t2t_model.py", line 537, in infer
    top_beams, alpha)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/models/transformer.py", line 237, in _beam_decode
    features, decode_length, beam_size, top_beams, alpha)
  File "/home/xiaonzha/xzefs/repos/t2t-official/tensor2tensor/models/transformer.py", line 405, in _fast_decode
    ret["outputs"] = ret["outputs"][:, :, partial_targets_length:]
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 538, in _SliceHelper
    name=name)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 706, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5430, in strided_slice
    name=name)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/xiaonzha/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Index out of range using input dim 2; input has only 2 dims for 'transformer/strided_slice_6' (op: 'StridedSlice') with input shapes: [?,?], [3], [3], [3] and with computed input tensors: input[3] = <1 1 1>.
```
I'm trying to decode one of held-out data of languagemodel_lm1b32k
```
ROBLEM=languagemodel_lm1b32k
MODEL=transformer
HPARAMS=transformer_base

efs=$HOME/xzefs
DATA_DIR=$efs/t2t-ws/data
TMP_DIR=$efs/tmp/t2t_datagen
TRAIN_DIR=$efs/t2t-ws/lm-3

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
# t2t-datagen \
#  --data_dir=$DATA_DIR \
#  --tmp_dir=$TMP_DIR \
#  --problem=$PROBLEM

# Train
# *  If you run out of memory, add --hparams='batch_size=1024'.
export CUDA_VISIBLE_DEVICES=7
t2t-decoder \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --decode_from_file="tmp/1-billion-word-language-modeling-benchmark-r13output/heldout-monolingual.tokenized.shuffled/news.en.heldout-00000-of-00050" \
  # --decode_to_file test2.txt \

```

**Comment by rasmi** [comment]
Hi @FreeAlex, I think that error is addressed in #655. That PR has not been merged -- you can modify your source directly using the changes there as a guide in the meantime.

**Comment by stefan-it** [comment]
@rafaelbou Is this issue fixed with #679?
