### ISSUE TITLE
Running transformer on multiple GPUs on the same machine loss=NAN error 

### ISSUE THREAD

**Issue by ahmadrash** [tensorflow/tensor2tensor#606]
I am running tensorflow 1.4.1 and tensor2tensor 1.4.2. I am training the transformer big hyper-parameter set on my own translation data. If I #run the training on multiple GPUs what is the difference between just using   export CUDA_VISIBLE_DEVICES="4,5,6,7" and adding the "worker_gpu" flag. When I run just with the former I see that all 4 GPUs are being used. 

However when I add the worker_gpu flag to the same setup I see:
`ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "t2t-trainer", line 16, in <module>
    tf.app.run()
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "t2t-trainer", line 12, in main
    t2t_trainer.main(argv)
  File "/home/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 237, in main
    execute_schedule(exp)
  File "/home/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 217, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/framework/experimental.py", line 64, in new_func
    return func(*args, **kwargs)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 717, in continuous_train_and_eval
    hooks=self._train_monitors)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
    hooks=hooks)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 783, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1032, in run
    run_metadata=run_metadata))
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 579, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
`

**Comment by martinpopel** [comment]
You need both, exporting CUDA_VISIBLE_DEVICES=4,5,6,7 and `--worker_gpu=4`. Without the first, TF does not see the GPUs. Without the second, it allocates memory on all four GPUs (I think), but uses just one of them.
Are you sure you won't get the NaN error if running long enough on a single GPU (at least 4 times longer than on 4 GPUs)?

**Comment by ahmadrash** [comment]
Without the `--worker_gpu=4` my code is still running after 8000 iterations. When I used the flag it crashed immediately after creating the first checkpoint before displaying the loss for the first iteration.

**Comment by ahmadrash** [comment]
I should add that I am running a batch size of 1800. I tried 2048 on a single K80 (12G) with transformer big but it crashed  with `Resource exhausted: OOM` error after a few iterations. I have seen some of the discussions on batch sizes.

**Comment by ahmadrash** [comment]
@yudianer That is the way to run on multiple GPUs but unfortunately I see the aforementioned NAN error when I try that. I have tried multiple combinations of parameters but it has not worked for me.

**Comment by yudianer** [comment]
@ahmadrash Thank you. I have tried to set CUDA_VISIBLE_DEVICES=0, --worker_gpu=1, and still I got the Nan error. Did you success to run your custom transformer problem on single gpu?  would you please help me figure out the error I made? thank you every much!

**Comment by ahmadrash** [comment]
@yudianer Yes I can run it on a single GPU. I am still trying to figure out the issue. I will update if I have a resolution. I see on your other thread that you are generating your own encoding?  Can you validate that once you replace the extra tokens your data has only 32k tokens?

**Comment by ahmadrash** [comment]
I was able to train with 2 GPUs. I think it may be the way we have set up our K80 server set up rather than a Tensor2Tensor issue so I am closing it for now.

**Comment by nxphi47** [comment]
Hi, can anyone open this again. I have updated all to newest version (t2t 1.9, tf 1.10) and got Nan Loss error whenever I try to use more than 1 GPU.

Of course I have set CUDA_VISIBLE_DEVICES=0,1 and --worker_gpu=2

This happens in all dataset, all configuration.

Can anyone help?
