### ISSUE TITLE
ValueError: Cannot use 'while/transformer/problem_choice' as input to 'Equal' because 'while/transformer/problem_choice' is in a while loop. See info log for more details.

### ISSUE THREAD

**Issue by dixiematt8** [tensorflow/tensor2tensor#613]
PROBLEM=e2_e_nlg
MODEL=transformer
HPARAMS=transformer_base_single_gpu

DATA_DIR=./t2t_data
TMP_DIR=./tmp/t2t_datagen
TRAIN_DIR=./t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM \
  --t2t_usr_dir=./usr_dir/

# Train
# *  If you run out of memory, add --hparams='batch_size=1024'.
CUDA_VISIBLE_DEVICES=0 t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --t2t_usr_dir=./usr_dir/ \
  --hparams="eval_run_autoregressive=True"

Traceback (most recent call last):
  File "/home/mdixie/.conda/envs/py35/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/mdixie/.conda/envs/py35/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 337, in main
    execute_schedule(exp)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 287, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/framework/python/framework/experimental.py", line 64, in new_func
    return func(*args, **kwargs)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 780, in continuous_train_and_eval
    hooks=self._eval_hooks)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 889, in _call_evaluate
    hooks=hooks)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 367, in evaluate
    name=name)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _evaluate_model
    features, labels, model_fn_lib.ModeKeys.EVAL, self.config)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/utils/t2t_model.py", line 829, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/utils/t2t_model.py", line 916, in estimator_model_fn
    losses_dict)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/utils/t2t_model.py", line 965, in estimator_spec_eval
    eval_metrics[metric_name] = metric_fn(logits, features)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/utils/metrics.py", line 300, in problem_metric_fn
    tf.equal(problem_idx, problem_choice), wrapped_metric_fn,
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1498, in equal
    "Equal", x=x, y=y, name=name)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1672, in __init__
    control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_util.py", line 200, in CheckInputFromValidContext
    raise ValueError(error_msg + " See info log for more details.")
ValueError: Cannot use 'while/transformer/problem_choice' as input to 'Equal' because 'while/transformer/problem_choice' is in a while loop. See info log for more details.

**Comment by agemagician** [comment]
Any plans to fix this problem ?
It is still doesn't work with the latest t2t version.
