### ISSUE TITLE
Walkthrough training error

### ISSUE THREAD

**Issue by sempreyj** [tensorflow/tensor2tensor#64]
when run Walkthrough
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --train_steps=0 \
  --eval_steps=0 \
  --decode_beam_size=$BEAM_SIZE \
  --decode_alpha=$ALPHA \
  --decode_from_file=$DECODE_FILE

the error infomation is as follows:

INFO:tensorflow:Creating experiment, storing model files in /root/t2t_train/wmt_ende_tokens_32k/transformer-transformer_base
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 240, in run
    run_locally(exp_fn(output_dir))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 126, in experiment_fn
    eval_steps=eval_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 138, in create_experiment
    model_name=model_name)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 174, in create_experiment_components
    keep_checkpoint_max=FLAGS.keep_checkpoint_max))
TypeError: __init__() got an unexpected keyword argument 'session_config'
INFO:tensorflow:Creating experiment, storing model files in /root/t2t_train/wmt_ende_tokens_32k/transformer-transformer_base
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 240, in run
    run_locally(exp_fn(output_dir))
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 126, in experiment_fn
    eval_steps=eval_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 138, in create_experiment
    model_name=model_name)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 174, in create_experiment_components
    keep_checkpoint_max=FLAGS.keep_checkpoint_max))
TypeError: __init__() got an unexpected keyword argument 'session_config'

**Comment by lukaszkaiser** [comment]
Which version of TensorFlow are you running? You need at least 1.2 for T2T, I'm afraid. Or is this something else?

**Comment by sempreyj** [comment]
@lukaszkaiser   I have upgraded  my version to 1.2，but Errors still exist.
# python3 -c 'import tensorflow as tf; print(tf.__version__)'
1.2.0-rc0

**Comment by lukaszkaiser** [comment]
It's saying that RunConfig doesn't have a "session_config" argument, right? But in 1.2 it does:
https://www.tensorflow.org/api_docs/python/tf/contrib/learn/RunConfig

I think it wasn't there in 1.2-rc0, you might need to upgrade to rc1 or the final 1.2. Sorry for that!

**Comment by sempreyj** [comment]
Thank you for your help.!
But I have met a new problem when running # Decode, could you help me ?
https://github.com/tensorflow/tensor2tensor/issues/76

**Comment by sempreyj** [comment]
@lukaszkaiser 
If I use CPU instead of GPU，which HPARAMS should I choose，transformer_base or transformer_big ?

**Comment by sempreyj** [comment]
HPARAMS = transformer_base 
I used python2 instead of python3, the issue is resolved.
