### ISSUE TITLE
"t2t-query-server " got error

### ISSUE THREAD

**Issue by yudianer** [tensorflow/tensor2tensor#648]
There were no error during after training translation model with t2t , exporting for server as well as launch server as described [Serving]( https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/serving)

However when I "Query the Server", here came an error as below:
```
(tfgpu1.6-2.7) jack@ubuntu516:~/dev1.8t/corpus/mn-zh/trans/mn-zh-split/gpu2.7$ bash query_server.sh 
>> ᠭᠠᠵᠠᠷ
Traceback (most recent call last):
  File "/home/jack/tools/ana2/envs/tfgpu1.6-2.7/bin/t2t-query-server", line 16, in <module>
    tf.app.run()
  File "/home/jack/tools/ana2/envs/tfgpu1.6-2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/jack/tools/ana2/envs/tfgpu1.6-2.7/bin/t2t-query-server", line 12, in main
    query.main(argv)
  File "/home/jack/tools/ana2/envs/tfgpu1.6-2.7/lib/python2.7/site-packages/tensor2tensor/serving/query.py", line 109, in main
    output_ids = query(stub, input_ids, feature_name=fname)
  File "/home/jack/tools/ana2/envs/tfgpu1.6-2.7/lib/python2.7/site-packages/tensor2tensor/serving/query.py", line 71, in query
    response = stub.Predict(request, FLAGS.timeout_secs)
  File "/home/jack/tools/ana2/envs/tfgpu1.6-2.7/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/jack/tools/ana2/envs/tfgpu1.6-2.7/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: transformer/attention_bias_lower_triangle/attention_bias_local/ones = Fill[T=DT_FLOAT, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](transformer/attention_bias_lower_triangle/attention_bias_local/ones/packed, transformer/ones/Const). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: transformer/attention_bias_lower_triangle/attention_bias_local/ones = Fill[T=DT_FLOAT, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](transformer/attention_bias_lower_triangle/attention_bias_local/ones/packed, transformer/ones/Const)]]")
```

query_server.sh ：
```
export CUDA_VISIBLE_DEVICES="1"
t2t-query-server \
  --server=localhost:9000 \
  --servable_name=transformer \
  --problem=translate_mnzh_bpe32k \
  --data_dir=/home/jack/dev1.8t/corpus/mn-zh/trans/mn-zh-split/gpu2.7 \
  --worker_gpu=1
```

**Comment by yudianer** [comment]
[t2t-decoder](https://github.com/tensorflow/tensor2tensor) works normally.

**Comment by vince62s** [comment]
Similar issue here, it also raises an error on the server side:
```
2018-03-14 15:00:23.635301: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:651] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: transformer/attention_bias_lower_triangle/attention_bias_local/ones = Fill[T=DT_FLOAT, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](transformer/attention_bias_lower_triangle/attention_bias_local/ones/packed, transformer/ones/Const). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: transformer/attention_bias_lower_triangle/attention_bias_local/ones = Fill[T=DT_FLOAT, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](transformer/attention_bias_lower_triangle/attention_bias_local/ones/packed, transformer/ones/Const)]]
```

**Comment by vince62s** [comment]
Okay, I figured it out.
TF serving release is only 1.5.0
So you need to be in TF 1.5.0 when exporting the model
and still in TF 1.5.0 when serving

this thing is not going to be easy at all .....

**Comment by yudianer** [comment]
Thank you @vince62s , Let me try it again.
Where did you find the "TF serving release is only 1.5.0"?

**Comment by vince62s** [comment]
https://github.com/tensorflow/serving/releases

**Comment by yudianer** [comment]
Thank you @vince62s , and only python 2.7 is supported!
