### ISSUE TITLE
How to do decoding for classification task

### ISSUE THREAD

**Issue by dixiematt8** [tensorflow/tensor2tensor#651]
Can you some tell me what is the mistake in this? I get error in decoding
This is my errror

```
INFO:tensorflow:Restoring parameters from ./t2t_train/sentiment_imdb/transformer_encoder-transformer_small/model.ckpt-1000
INFO:tensorflow:Inference results INPUT: Goodbye world
Traceback (most recent call last):
  File "/home/mdixie/.conda/envs/py35/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/mdixie/.conda/envs/py35/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/bin/t2t_decoder.py", line 114, in main
    decode(estimator, hp, decode_hp)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/bin/t2t_decoder.py", line 85, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/utils/decoding.py", line 287, in decode_from_file
    None, inputs_vocab, targets_vocab)
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/utils/decoding.py", line 92, in log_decode_results
    decoded_outputs = targets_vocab.decode(_save_until_eos(outputs, is_image))
  File "/home/mdixie/.conda/envs/py35/lib/python3.5/site-packages/tensor2tensor/data_generators/text_encoder.py", line 213, in decode
    return self._class_labels[label_id]


TypeError: 'method' object is not subscriptable

```

This is my script

```
PROBLEM=sentiment_imdb
MODEL=transformer_encoder
HPARAMS=transformer_small

DATA_DIR=./t2t_data
TMP_DIR=./tmp/t2t_datagen
TRAIN_DIR=./t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM

# Train
# *  If you run out of memory, add --hparams='batch_size=1024'.
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --train_steps=1000 \
  --output_dir=$TRAIN_DIR

# # Decode

DECODE_FILE=$DATA_DIR/decode_this.txt
echo "Hello world" >> $DECODE_FILE
echo "Goodbye world" >> $DECODE_FILE
#echo -e 'Hallo Welt\nAuf Wiedersehen Welt' > ref-translation.de

BEAM_SIZE=1
#ALPHA=0.6

t2t-decoder \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --decode_hparams="beam_size=$BEAM_SIZE" \
  --decode_from_file=$DECODE_FILE \
  --decode_to_file=translation.en
```

**Comment by dixiematt8** [comment]
it will be fixed in the next release!
