### ISSUE TITLE
*bug* The --dbgprofile flag is not working

### ISSUE THREAD

**Issue by lucb** [tensorflow/tensor2tensor#659]
### Description

The flag --dbgprofile produces an error and can't be used.

The error message is the following:
> AttributeError: 'module' object has no attribute 'hooks'

### *TensorFlow* and *tensor2tensor* versions

Python 2.7.12

tensor2tensor==1.5.5
tensorflow-gpu==1.5.0
tensorflow-tensorboard==1.5.0

Docker image is gcr.io/tensorflow/tensorflow:1.5.0-gpu with the addition of tensor2tensor

### In case of bug report: Steps to reproduce the problem
```
t2t-trainer --dbgprofile \
--problems=algorithmic_reverse_binary40_test \
--data_dir=/tmp/t2t-data \
--model=transformer \
--hparams_set=transformer_tiny \
--train_steps=5 --eval_steps=5 \
--output_dir=/tmp/t2t-train
```
### In case of bug report: Error log

```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:schedule=continuous_train_and_eval
[2018-03-21 14:29:37,991] schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
[2018-03-21 14:29:37,991] worker_gpu=1
INFO:tensorflow:sync=False
[2018-03-21 14:29:37,991] sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
[2018-03-21 14:29:37,991] Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
[2018-03-21 14:29:37,991] datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
[2018-03-21 14:29:37,991] caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
[2018-03-21 14:29:37,992] ps_devices: ['gpu:0']
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 20, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fa61eb227d0>, '_keep_checkpoint_every_n_hours': 10000, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': 1234, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 1000, '_environment': 'local', '_master': '', '_model_dir': '/tmp/t2t-train', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7fa61a551ed0>, '_save_summary_steps': 100}
[2018-03-21 14:29:37,992] Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 20, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fa61eb227d0>, '_keep_checkpoint_every_n_hours': 10000, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': 1234, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 1000, '_environment': 'local', '_master': '', '_model_dir': '/tmp/t2t-train', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7fa61a551ed0>, '_save_summary_steps': 100}
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7fa61eb24758>) includes params argument, but params are not passed to Estimator.
[2018-03-21 14:29:37,992] Estimator's model_fn (<function wrapping_model_fn at 0x7fa61eb24758>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:ValidationMonitor only works with --schedule=train_and_evaluate
[2018-03-21 14:29:37,992] ValidationMonitor only works with --schedule=train_and_evaluate
INFO:tensorflow:Using ProfilerHook
[2018-03-21 14:29:37,992] Using ProfilerHook
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 334, in main
    exp = exp_fn(create_run_config(hparams), hparams)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 332, in experiment_fn
    return create_experiment(run_config, hparams, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 312, in create_experiment
    early_stopping_kwargs=early_stopping_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 212, in create_hooks
    train_monitors.append(tf.contrib.hooks.ProfilerHook(**defaults))
AttributeError: 'module' object has no attribute 'hooks'

```

**Comment by rsepassi** [comment]
Thanks, looks like the location has moved in recent TF releases. Will be fixed in the next release.
