### ISSUE TITLE
*bug* t2t-bleu failing to evaluate the translation output.

### ISSUE THREAD

**Issue by shantipriyap** [tensorflow/tensor2tensor#706]
### Description
t2t-bleu failing to evaluate my translation output. Although same is working with sacrebleu.

### *TensorFlow* and *tensor2tensor* versions
tensor2tensor==1.5.6
tensorboard==1.6.0
tensorflow==1.6.0
Python 3.5.4

### Error log
(py3.5.4-env)parida@dll2:~/spec_work_parida/nmt/nmt-hindi/playground/s.tensor2tensor.413b461f.20180124-1602/tensor2tensor/tensor2tensor/bin$ ./t2t-bleu --translation=/home/parida/spec_work_parida/nmt/nmt-hindi/playground/s.tensor2tensor.413b461f.20180124-1602/tensor2tensor/t2t_data/translation.hi --reference=/home/parida/spec_work_parida/temp/t2t_dataden/valid.32k.hi
Traceback (most recent call last):
  File "./t2t-bleu", line 17, in <module>
    tf.app.run()
  File "/lnet/spec/work/people/parida/python-venv/py3.5.4-env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./t2t-bleu", line 12, in main
    t2t_bleu.main(argv)
  File "/lnet/spec/work/people/parida/nmt/nmt-hindi/playground/s.tensor2tensor.413b461f.20180124-1602/tensor2tensor/tensor2tensor/bin/tensor2tensor/bin/t2t_bleu.py", line 102, in main
    case_sensitive=False)
  File "/lnet/spec/work/people/parida/nmt/nmt-hindi/playground/s.tensor2tensor.413b461f.20180124-1602/tensor2tensor/tensor2tensor/bin/tensor2tensor/utils/bleu_hook.py", line 197, in bleu_wrapper
    ref_lines = open(ref_filename).read().splitlines()
  File "/lnet/spec/work/people/parida/python-venv/py3.5.4-env/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)

**Comment by martinpopel** [comment]
In my [original implementation](https://github.com/tensorflow/tensor2tensor/pull/436/files#diff-618723e3f9693cff94901980b1388f67R191) I had `open(ref_filename, 'rt', encoding='utf-8').read().splitlines()`, but someone from Google deleted the `encoding='utf-8'` so they can use it easily with Python 2 (although they should rather use `codecs.open` or `io.open` for [backporting encoding](https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2) to Python 2).
So currently, if run under Python 3, the encoding depends on your locale (see below). Either set it properly to use utf8 (e.g. with `export LANG=en_US.UTF-8` or LC_ALL), or send a PR with adds the `encoding='utf-8'` parameter to open in a Python2-friendly way.
```bash
$ LANG=en_US python3 -c 'import locale;print(locale.getpreferredencoding())'
ANSI_X3.4-1968
$ LANG=en_US.UTF-8 python3 -c 'import locale;print(locale.getpreferredencoding())'
UTF-8
```

**Comment by shantipriyap** [comment]
Thanks Martin. I have send a PR as per suggestion. Can you please help to verify if the changes are fine.
