### ISSUE TITLE
Master error when running distributed training

### ISSUE THREAD

**Issue by fengrussell** [tensorflow/tensor2tensor#745]
I tried to use shake_shake model run distributed training. I have 1 ps and 2 masters, every server has no gpu.
The master0 script is:
```
TF_CONFIG='{"environment": "cloud", "cluster": {"ps": ["192.168.100.1:2222"], "master": ["192.168.100.2:2222", "192.168.100.3:2222"]}, "task": {"index": 0, "type": "master"}}' t2t-trainer --master=grpc://192.168.100.2:2222 --ps_replicas=1 --worker_replicas=2 --worker_gpu=1 --worker_id=0 --worker_job='/job:master' --ps_gpu=1 --schedule=train --problems=image_mnist --model=shake_shake --hparams_set=shakeshake_small --data_dir=~/t2t_data --output_dir=~/t2t_train/mnist 
```
The master0_out is:
```
2018-04-25 07:36:28.720551: I tensorflow/core/distributed_runtime/master_session.cc:1024] Start master session 7ba9e821f08066d2 with config: gpu_options { per_process_gpu_memory_fraction: 1 } allow_soft_placement: true graph_options { optimizer_options { } }
Traceback (most recent call last):
  File "/home/russell/miniconda2/bin/t2t-trainer", line 16, in <module>
    tf.app.run()
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/russell/miniconda2/bin/t2t-trainer", line 12, in main
    t2t_trainer.main(argv)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 335, in main
    execute_schedule(exp)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 285, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 388, in train
    saving_listeners=self._saving_listeners)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 868, in _call_train
    saving_listeners=saving_listeners)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 888, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 795, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 518, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 981, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 986, in _create_session
    return self._sess_creator.create_session()
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 675, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 446, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot colocate nodes 'shake_shake/parallel_0_5/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/AssignSub' and 'shake_shake/body/L1/layer_0/final_path_bn/moving_variance: Cannot merge devices with incompatible jobs: '/job:master/task:0' and '/job:ps/task:0/device:GPU:0'
	 [[Node: shake_shake/parallel_0_5/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/AssignSub = AssignSub[T=DT_FLOAT, _class=["loc:@Identity_37", "loc:@shake_shake/body/L1/layer_0/final_path_bn/moving_variance"], use_locking=false, _device="/job:master/task:0"](shake_shake/body/L1/layer_0/final_path_bn/moving_variance, shake_shake/parallel_0_5/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/Mul)]]

Caused by op u'shake_shake/parallel_0_5/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/AssignSub', defined at:
  File "/home/russell/miniconda2/bin/t2t-trainer", line 16, in <module>
    tf.app.run()
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/russell/miniconda2/bin/t2t-trainer", line 12, in main
    t2t_trainer.main(argv)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 335, in main
    execute_schedule(exp)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 285, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 388, in train
    saving_listeners=self._saving_listeners)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 868, in _call_train
    saving_listeners=saving_listeners)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 812, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 793, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 788, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 839, in estimator_model_fn
    logits, losses_dict = model(features)  # pylint: disable=not-callable
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 137, in call
    sharded_logits, losses = self.model_fn_sharded(sharded_features)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 171, in model_fn_sharded
    sharded_logits, sharded_losses = dp(self.model_fn, datashard_to_features)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/utils/expert_utils.py", line 254, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 193, in model_fn
    body_out = self.body(transformed_features)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/models/shake_shake.py", line 151, in body
    x = shake_shake_layer(x, 16 * k, n, 1, hparams)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/models/shake_shake.py", line 125, in shake_shake_layer
    x = shake_shake_block(x, output_filters, curr_stride, hparams)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/models/shake_shake.py", line 106, in shake_shake_block
    res = shake_shake_skip_connection(x, output_filters, stride, is_training)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensor2tensor/models/shake_shake.py", line 53, in shake_shake_skip_connection
    final_path, training=is_training, name="final_path_bn")
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 777, in batch_normalization
    return layer.apply(inputs, training=training)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 809, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 508, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 420, in _fused_batch_norm
    variance, one_minus_decay)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 372, in _assign_moving_average
    return state_ops.assign_sub(variable, update_delta, name=scope)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 219, in assign_sub
    return ref.assign_sub(value)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 629, in assign_sub
    return state_ops.assign_sub(self._variable, delta, use_locking=use_locking)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 218, in assign_sub
    ref, value, use_locking=use_locking, name=name)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 139, in assign_sub
    "AssignSub", ref=ref, value=value, use_locking=use_locking, name=name)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/russell/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot colocate nodes 'shake_shake/parallel_0_5/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/AssignSub' and 'shake_shake/body/L1/layer_0/final_path_bn/moving_variance: Cannot merge devices with incompatible jobs: '/job:master/task:0' and '/job:ps/task:0/device:GPU:0'
	 [[Node: shake_shake/parallel_0_5/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/AssignSub = AssignSub[T=DT_FLOAT, _class=["loc:@Identity_37", "loc:@shake_shake/body/L1/layer_0/final_path_bn/moving_variance"], use_locking=false, _device="/job:master/task:0"](shake_shake/body/L1/layer_0/final_path_bn/moving_variance, shake_shake/parallel_0_5/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/Mul)]]
```
Could someone give some advice?
Thanks.

**Comment by gangliao** [comment]
I have the same problem with distributed training.

```bash
export TF_CONFIG='{"cluster": {"ps": ["10.129.27.82:2231"], "master": ["10.129.27.82:2222"], "worker": ["10.129.27.82:2223"]}, "task": {"index": 0, "type": "worker"}, "environment": "cloud"}'
 t2t-trainer --generate_data --data_dir=~/t2t_data --output_dir=~/t2t_train/mnist \
                  --problem=image_mnist --model=shake_shake --hparams_set=shake_shake_quick \
                  --train_steps=1000 --eval_steps=100 \
                  --master=grpc://10.129.27.82:2223 \
                  --worker_replicas=2 --worker_gpu=0 --worker_id=1 --ps_replicas=1 --ps_gpu=0 --schedule=train
```


```bash
InvalidArgumentError (see above for traceback): Cannot colocate nodes 'shake_shake/parallel_0_4/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/AssignSub' and 'shake_shake/body/L1/layer_0/final_path_bn/moving_variance: Cannot merge devices with incompatible jobs: '/job:localhost/task:0' and '/job:ps/task:0'
	 [[Node: shake_shake/parallel_0_4/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/AssignSub = AssignSub[T=DT_FLOAT, _class=["loc:@Identity_37", "loc:@shake_shake/body/L1/layer_0/final_path_bn/moving_variance"], use_locking=false, _device="/job:localhost/task:0"](shake_shake/body/L1/layer_0/final_path_bn/moving_variance, shake_shake/parallel_0_4/shake_shake/body/L1/layer_0/final_path_bn/AssignMovingAvg_1/Mul)]]
```

**Comment by changlan** [comment]
Same problem here. Any update?

**Comment by fengrussell** [comment]
I modified the source of tensor, now it supports horovod, [git link](https://github.com/fengrussell/tensor2tensor-hvd) here.
