### ISSUE TITLE
Install version 1.5.0

### ISSUE THREAD

**Issue by shahawi** [tensorflow/tensor2tensor#764]
Hi, 
I am having problems with g2p seq2seq with the current version of tensor2tensor can I manually install version 1.5.0
Thanks.

**Comment by datkpa** [comment]
t2t-trainer --data_dir=~/t2t/data --output_dir=~/t2t/train/transformer_v2 --problems=summarize_cnn_dailymail32k --model=transformer --hparams_set= transformer_prepend --hparams batch_size=4096 --train_steps=100000 --eval_steps=100 --worker_gpu=2 --keep_checkpoint_max 10

**Comment by datkpa** [comment]
Trur

**Comment by shahawi** [comment]
Thanks ill try it

**Comment by stefan-it** [comment]
Hm, I'm not sure what the exact problem is, but you can manually install a specific version with `pip`, e.g:

```bash
pip install tensor2tensor==1.5.0
```

**Comment by shahawi** [comment]
@datkpa 
this is my log

```
(tensorflow) hosni@hosni-Inspiron-3521:~/g2p-seq2seq$ t2t-trainer --data_dir=/t2t/train/transformer_v2 --problems=summarize_cnn_dailymail32k --model=transformer --hparams_set= transformer_prepend --hparams batch_size=4096 --train_steps=100000 --eval_steps=100 --worker_gpu=2 --keep_checkpoint_max 10
Skipped importing 1 data_generators modules.
Traceback (most recent call last):
  File "/home/hosni/tensorflow/bin/t2t-trainer", line 23, in <module>
    from tensor2tensor.bin import t2t_trainer
  File "/home/hosni/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 27, in <module>
    from tensor2tensor import problems as problems_lib  # pylint: disable=unused-import
  File "/home/hosni/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/problems.py", line 26, in <module>
    from tensor2tensor.data_generators import all_problems  # pylint: disable=unused-import
  File "/home/hosni/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/all_problems.py", line 93, in <module>
    _handle_errors(_errors)
  File "/home/hosni/tensorflow/local/lib/python2.7/site-packages/tensor2tensor/data_generators/all_problems.py", line 82, in _handle_errors
    raise err
ImportError: cannot import name _errors
(tensorflow) hosni@hosni-Ins`p`iron-3521:~/g2p-seq2seq$ 

```

**Comment by 520jefferson** [comment]
@shahawi  have you sloved the problem?  (ImportError: cannot import name _errors)
