### ISSUE TITLE
*bug* t2t-decoder: ValueError with `r_transformer` model

### ISSUE THREAD

**Issue by stefan-it** [tensorflow/tensor2tensor#767]
### Description

I trained a model for the `translate_envi_iwslt32k` problem using the following command:

```bash
t2t-trainer --data_dir=t2t_data --problem=translate_envi_iwslt32k \
--model=r_transformer --hparams_set=r_transformer_base \
--output_dir=t2t_output --hparams='batch_size=1024'
```

Training completed without any errors (and great results).

### *TensorFlow* and *tensor2tensor* versions

```bash
tf-nightly-gpu==1.9.0.dev20180430
tensor2tensor 6cea4c460585ce835d8bfa87f7191e29dd4de9e2 (currently latest master)
```

### In case of bug report: Steps to reproduce the problem

Then decoding was done with the following command:

```bash
t2t-decoder --data_dir=t2t_data --problem=translate_envi_iwslt32k \
--model=r_transformer --decode_hparams="beam_size=4,alpha=0.6"  \
--decode_from_file=tst2013.en --decode_to_file=system.output  \
--hparams_set=r_transformer_base --output_dir=t2t_output/
```

### In case of bug report: Error log

The `t2t-decoder` outputs the following error message:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/t2t-decoder", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/bin/t2t_decoder.py", line 190, in main
    decode(estimator, hp, decode_hp)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/bin/t2t_decoder.py", line 93, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/utils/decoding.py", line 263, in decode_from_file
    for result in result_iter:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 500, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 828, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/utils/t2t_model.py", line 921, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/utils/t2t_model.py", line 965, in estimator_model_fn
    return model.estimator_spec_predict(features, use_tpu=use_tpu)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/utils/t2t_model.py", line 1097, in estimator_spec_predict
    use_tpu=use_tpu)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/utils/t2t_model.py", line 560, in infer
    top_beams, alpha)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/models/transformer.py", line 249, in _beam_decode
    features, decode_length, beam_size, top_beams, alpha)
  File "/mnt/tensor2tensor-largebatch/tensor2tensor/models/transformer.py", line 310, in _fast_decode
    features=features)
ValueError: too many values to unpack (expected 2)
```

**Comment by martinpopel** [comment]
Just for the record: I tried `HPARAMS=r_transformer_big` on en-cs translation and it worked OK even with `t2t-decoder`. However, the BLEU results were about the same as `transformer_big`.

**Comment by stefan-it** [comment]
The latest `1.6.2` shows another error message:

```bash
2018-05-08 09:58:46.117449: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure at save_restore_v2_ops.cc:184: Not found: Key r_transformer/r_transformer/body/decoder/layer_prepostprocess/layer_norm/layer_norm_bias not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1742, in restore
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 334, in get_tensor
    status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/t2t-decoder", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t_decoder.py", line 190, in main
    decode(estimator, hp, decode_hp)
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t_decoder.py", line 93, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/utils/decoding.py", line 264, in decode_from_file
    for result in result_iter:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 515, in predict
    hooks=all_hooks) as mon_sess:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 826, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 549, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1012, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1017, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 706, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 477, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/session_manager.py", line 277, in prepare_session
    config=config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/session_manager.py", line 191, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1746, in restore
    six.reraise(exception_type, exception_value, exception_traceback)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1734, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key r_transformer/r_transformer/body/decoder/layer_prepostprocess/layer_norm/layer_norm_bias not found in checkpoint
         [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
         [[Node: save/RestoreV2_1/_55 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_62_save/RestoreV2_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2_1', defined at:
  File "/usr/local/bin/t2t-decoder", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t_decoder.py", line 190, in main
    decode(estimator, hp, decode_hp)
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/bin/t2t_decoder.py", line 93, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/mnt/tensor2tensor-6cea4c4/tensor2tensor/utils/decoding.py", line 264, in decode_from_file
    for result in result_iter:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 515, in predict
    hooks=all_hooks) as mon_sess:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 826, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 549, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1012, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1017, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 706, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 468, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 838, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1266, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1278, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1315, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 757, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 453, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 400, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 814, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3408, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key r_transformer/r_transformer/body/decoder/layer_prepostprocess/layer_norm/layer_norm_bias not found in checkpoint
         [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
         [[Node: save/RestoreV2_1/_55 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_62_save/RestoreV2_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

**Comment by stefan-it** [comment]
Decoding works now with 2135da9, so I'm closing here :)

**Comment by MostafaDehghani** [comment]
Just wanted to point out here that r_transformer_base has about 25 million parameters and transformer_base has around 64 million parameters, so in terms of the capacity of the model r_transformer_big (~65 million parameters) would be comparable to transformer_base. 
We changed the name of hparams_sets to avoid the confusion in [this PR](https://github.com/tensorflow/tensor2tensor/pull/837).
