### ISSUE TITLE
*bug* ImportError: cannot import name _errors

### ISSUE THREAD

**Issue by mehmedes** [tensorflow/tensor2tensor#768]
### *TensorFlow* and *tensor2tensor* versions

```
tensor2tensor==1.6.1
tensorboard==1.8.0
tensorflow==1.6.0
tensorflow-gpu==1.8.0
tensorflow-serving-api==1.5.0
tensorflow-tensorboard==1.5.0
```

### In case of bug report: Error log

```
Skipped importing 1 data_generators modules.
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 4, in <module>
    __import__('pkg_resources').run_script('tensor2tensor==1.6.1', 't2t-trainer')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.6.1-py2.7.egg/EGG-INFO/scripts/t2t-trainer", line 23, in <module>
    from tensor2tensor.bin import t2t_trainer
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.6.1-py2.7.egg/tensor2tensor/bin/t2t_trainer.py", line 27, in <module>
    from tensor2tensor import problems as problems_lib  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.6.1-py2.7.egg/tensor2tensor/problems.py", line 26, in <module>
    from tensor2tensor.data_generators import all_problems  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.6.1-py2.7.egg/tensor2tensor/data_generators/all_problems.py", line 93, in <module>
    _handle_errors(_errors)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor-1.6.1-py2.7.egg/tensor2tensor/data_generators/all_problems.py", line 82, in _handle_errors
    raise err
ImportError: cannot import name _errors
```

> …

**Comment by lukaszkaiser** [comment]
Can you try again on 1.6.2? Is it still a problem?

**Comment by mehmedes** [comment]
Great. Thank you! Everything's fine with 1.6.2.

**Comment by mehmedes** [comment]
@lukaszkaiser I'm sorry for re-opening.
It works when using python3 but the same error still occurs with python2.
