### ISSUE TITLE
 *help*   TypeError: Expected int32 passed to parameter 'y' of op 'Equal', got 0.0 of type 'float' instead

### ISSUE THREAD

**Issue by nimaous** [tensorflow/tensor2tensor#803]
Hi. During decoding phase I got the following error: 

 TensorFlow 1.6
 tensor2tensor 1.5.7 
```
Traceback (most recent call last):
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1036, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 433, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 344, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 0.0 of type 'float' instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sopran/rafiee/py3/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/sopran/rafiee/py3/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/bin/t2t_decoder.py", line 188, in main
    decode(estimator, hp, decode_hp)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/bin/t2t_decoder.py", line 101, in decode
    dataset_split="test" if FLAGS.eval_use_test_set else None)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/decoding.py", line 160, in decode_from_dataset
    for num_predictions, prediction in enumerate(predictions):
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 479, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 793, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 889, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 934, in estimator_model_fn
    return model.estimator_spec_predict(features)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 1057, in estimator_spec_predict
    decode_length=decode_hparams.extra_length)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 540, in infer
    top_beams, alpha)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 293, in _beam_decode
    features, decode_length, beam_size, top_beams, alpha)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 363, in _fast_decode
    inputs, features["target_space_id"], hparams, orig_inp, features=features, template_flag=False)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/expert_utils.py", line 254, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 99, in encode
    orig_inp, target_space, hparams, features=features))
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 649, in transformer_prepare_encoder
    encoder_padding = common_attention.embedding_to_padding(encoder_input)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/expert_utils.py", line 85, in decorated
    return f(*args, **kwargs)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/layers/common_attention.py", line 690, in embedding_to_padding
    return tf.to_float(tf.equal(emb_sum, 0.0))
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1489, in equal
    "Equal", x=x, y=y, name=name)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 519, in _apply_op_helper
    repr(values), type(values).__name__))
TypeError: Expected int32 passed to parameter 'y' of op 'Equal', got 0.0 of type 'float' instead.
```

> …

**Comment by lukaszkaiser** [comment]
Strange. Could you try changing 0.0 to just 0 in this line:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/common_attention.py#L777

Does that help?

**Comment by nimaous** [comment]
I changed it but I am getting a new error

```
Traceback (most recent call last):
  File "/sopran/rafiee/py3/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/sopran/rafiee/py3/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/bin/t2t_decoder.py", line 188, in main
    decode(estimator, hp, decode_hp)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/bin/t2t_decoder.py", line 101, in decode
    dataset_split="test" if FLAGS.eval_use_test_set else None)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/decoding.py", line 160, in decode_from_dataset
    for num_predictions, prediction in enumerate(predictions):
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 479, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 793, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 889, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 934, in estimator_model_fn
    return model.estimator_spec_predict(features)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 1057, in estimator_spec_predict
    decode_length=decode_hparams.extra_length)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 540, in infer
    top_beams, alpha)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 294, in _beam_decode
    features, decode_length, beam_size, top_beams, alpha)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 365, in _fast_decode
    inputs, features["target_space_id"], hparams, orig_inp, features=features, template_flag=False)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/expert_utils.py", line 254, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 99, in encode
    orig_inp, target_space, hparams, features=features))
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 664, in transformer_prepare_encoder
    encoder_input += emb_target_space
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/ops/math_ops.py", line 925, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 946, in convert_to_tensor
    as_ref=False)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1036, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 879, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("transformer/body/parallel_0/body/Reshape_2:0", shape=(1, 1, 1), dtype=float32, device=/device:GPU:0)'
```
