### ISSUE TITLE
*help*  ValueError: Variable transformer/body/target_space_embedding/kernel already exists, disallowed.

### ISSUE THREAD

**Issue by nimaous** [tensorflow/tensor2tensor#808]
Hi. Im using decoding from file. and I am getting below error 
```
Traceback (most recent call last):
  File "/sopran/rafiee/py3/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/sopran/rafiee/py3/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/bin/t2t_decoder.py", line 188, in main
    decode(estimator, hp, decode_hp)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/bin/t2t_decoder.py", line 90, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/decoding.py", line 271, in decode_from_file
    for result in result_iter:
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 479, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 793, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 889, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 934, in estimator_model_fn
    return model.estimator_spec_predict(features)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 1057, in estimator_spec_predict
    decode_length=decode_hparams.extra_length)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/t2t_model.py", line 540, in infer
    top_beams, alpha)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 296, in _beam_decode
    features, decode_length, beam_size, top_beams, alpha)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 369, in _fast_decode
    template, features["target_space_id"], hparams, orig_inp, features=features,  template_flag=True)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 101, in encode
    orig_inp, target_space, hparams, features=features))
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 664, in transformer_prepare_encoder
    target_space, 32, ishape_static[-1], name="target_space_embedding")
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/layers/common_layers.py", line 310, in embedding
    embedding_var = tf.get_variable("kernel", [vocab_size, dense_size])
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 1297, in get_variable
    constraint=constraint)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 1093, in get_variable
    constraint=constraint)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 439, in get_variable
    constraint=constraint)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 408, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 747, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable transformer/body/target_space_embedding/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/utils/expert_utils.py", line 208, in daisy_chain_getter
    var = getter(name, *args, **kwargs)
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/layers/common_layers.py", line 310, in embedding
    embedding_var = tf.get_variable("kernel", [vocab_size, dense_size])
  File "/sopran/rafiee/py3/lib/python3.4/site-packages/tensor2tensor/models/transformer.py", line 664, in transformer_prepare_encoder
    target_space, 32, ishape_static[-1], name="target_space_embedding")
```
> …

*TensorFlow 1.6* 
 *tensor2tensor 1.5.7*

**Comment by nimaous** [comment]
I changed below line (309)  in common_layers.py file 
`with tf.variable_scope(
      name, default_name="embedding", values=[x], reuse=reuse, dtype=dtype):      `
which get `None` as value for argument reuse 
 to 
`with tf.variable_scope(
      name, default_name="embedding", values=[x], reuse=tf.AUTO_REUSE, dtype=dtype):  `

the error is solved now but Im not sure if I did the right thing or not.

**Comment by rsepassi** [comment]
What problem are you running on?

**Comment by nimaous** [comment]
Oh sorry, I fixed it but forgot to close the issue. it was my own defined problem. I am using two different encoders in transformer model and the error was due to scop name for each encoder.

**Comment by Noahsark** [comment]
@nimaous 
Hi, I met the same problem and look for help. Could you please clarify your code with the solution?

**Comment by nimaous** [comment]
@Noahsark  Hi.  I did a couple of code changes in transformer model so I think it's better to tell about the problem and model you are using and also maybe a log of your error.
