### ISSUE TITLE
MNIST doesn't work on Python 3 with transformer

### ISSUE THREAD

**Issue by schani** [tensorflow/tensor2tensor#83]
Sometimes strings are used when `bytes` are required, such as in the `image/format` values in image generators (in `data_generators/image.py`):

```
            "image/format": ["png"],
```

I fixed this by changing `to_example` in `data_generators/generator_utils.py` to

```
def to_example(dictionary):
  """Helper: build tf.Example from (string -> int/float/str list) dictionary."""
  features = {}
  for (k, v) in six.iteritems(dictionary):
    if not v:
      raise ValueError("Empty generated field: %s", str((k, v)))
    if isinstance(v[0], six.integer_types):
      features[k] = tf.train.Feature(int64_list=tf.train.Int64List(value=v))
    elif isinstance(v[0], float):
      features[k] = tf.train.Feature(float_list=tf.train.FloatList(value=v))
    elif isinstance(v[0], six.string_types):
      v = [bytes(x, 'utf-8') for x in v]
      features[k] = tf.train.Feature(bytes_list=tf.train.BytesList(value=v))
    elif isinstance(v[0], bytes):
      features[k] = tf.train.Feature(bytes_list=tf.train.BytesList(value=v))
    else:
      raise ValueError("Value for %s is neither an int nor a float; v: %s type: %s" %
                       (k, str(v[0]), str(type(v[0]))))
  return tf.train.Example(features=tf.train.Features(feature=features))
```

I'm not sure whether this is correct for Python 2, but please let me know and I'll send a PR.

In addition I had to change this line in the `image_generator`:

```
            "image/class/label": [int(label)],
```

The `label` was a `tf.int64`, which wasn't accepted.

After these changes I could generate the data, but training on `transformer_base` resulted in this:

```
2017-07-02 01:32:27.132046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2017-07-02 01:32:27.132060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2017-07-02 01:32:27.132068: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 56a6:00:00.0)
INFO:tensorflow:Restoring parameters from /data/t2t-test/t2t_train/image_mnist_test/transformer-transformer_base/model.ckpt-0
2017-07-02 01:32:30.897953: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1392 get requests, put_count=1200 evicted_count=1000 eviction_rate=0.833333 and unsatisfied allocation rate=0.928161
2017-07-02 01:32:30.898018: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
2017-07-02 01:32:36.467609: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Tried to explicitly squeeze dimension 2 but dimension was not 1: 28
         [[Node: body/model/parallel_0/body/Squeeze = Squeeze[T=DT_FLOAT, squeeze_dims=[2], _device="/job:localhost/replica:0/task:0/gpu:0"](symbol_modality_256_512/parallel_0/symbol_modality_256_512/shared/mul_1)]]
2017-07-02 01:32:36.752074: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Tried to explicitly squeeze dimension 2 but dimension was not 1: 28
         [[Node: body/model/parallel_0/body/Squeeze = Squeeze[T=DT_FLOAT, squeeze_dims=[2], _device="/job:localhost/replica:0/task:0/gpu:0"](symbol_modality_256_512/parallel_0/symbol_modality_256_512/shared/mul_1)]]
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tried to explicitly squeeze dimension 2 but dimension was not 1: 28
         [[Node: body/model/parallel_0/body/Squeeze = Squeeze[T=DT_FLOAT, squeeze_dims=[2], _device="/job:localhost/replica:0/task:0/gpu:0"](symbol_modality_256_512/parallel_0/symbol_modality_256_512/shared/mul_1)]]
         [[Node: body/model/parallel_0/body/decoder/layer_0/decoder_self_attention/dot_product_attention/Max/_4349 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_10279_body/model/parallel_0/body/decoder/layer_0/decoder_self_attention/dot_product_attention/Max", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/bin/t2t-trainer", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 246, in run
    run_locally(exp_fn(output_dir))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 536, in run_locally
    exp.train_and_evaluate()
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1007, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tried to explicitly squeeze dimension 2 but dimension was not 1: 28
         [[Node: body/model/parallel_0/body/Squeeze = Squeeze[T=DT_FLOAT, squeeze_dims=[2], _device="/job:localhost/replica:0/task:0/gpu:0"](symbol_modality_256_512/parallel_0/symbol_modality_256_512/shared/mul_1)]]
         [[Node: body/model/parallel_0/body/decoder/layer_0/decoder_self_attention/dot_product_attention/Max/_4349 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_10279_body/model/parallel_0/body/decoder/layer_0/decoder_self_attention/dot_product_attention/Max", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'body/model/parallel_0/body/Squeeze', defined at:
  File "/home/ubuntu/tensorflow/bin/t2t-trainer", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 246, in run
    run_locally(exp_fn(output_dir))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 536, in run_locally
    exp.train_and_evaluate()
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 495, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 275, in train
    hooks=self._train_monitors + extra_hooks)   
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 665, in _call_train
    monitors=hooks)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 955, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1162, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 431, in model_fn
    len(hparams.problems) - 1)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 750, in _cond_on_index
    return fn(cur_idx)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 412, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 415, in model_fn
    transformed_features)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 464, in model_fn_body_sharded
    datashard_to_features)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/expert_utils.py", line 294, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "/home/ubuntu/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 40, in fn_with_timing
    res = fn(*args, **kwargs)
  File "/home/ubuntu/tensor2tensor/tensor2tensor/models/transformer.py", line 51, in model_fn_body
    inputs = tf.squeeze(inputs, 2)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 2281, in squeeze
    return gen_array_ops._squeeze(input, axis, name)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3329, in _squeeze
    squeeze_dims=squeeze_dims, name=name)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Tried to explicitly squeeze dimension 2 but dimension was not 1: 28
         [[Node: body/model/parallel_0/body/Squeeze = Squeeze[T=DT_FLOAT, squeeze_dims=[2], _device="/job:localhost/replica:0/task:0/gpu:0"](symbol_modality_256_512/parallel_0/symbol_modality_256_512/shared/mul_1)]]
         [[Node: body/model/parallel_0/body/decoder/layer_0/decoder_self_attention/dot_product_attention/Max/_4349 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_10279_body/model/parallel_0/body/decoder/layer_0/decoder_self_attention/dot_product_attention/Max", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by lukaszkaiser** [comment]
It would be great if you could send a PR, yes! I checked and it seems to be fine with python2.

Transformer currently only works on Nx1 tensors, such as text, it's not an image model (yet). But try `--model=xception`, that should work fine.

Looking forward to your PR!

**Comment by schani** [comment]
#116

**Comment by lukaszkaiser** [comment]
Thanks, merged.
