### ISSUE TITLE
KeyError when trying to use transformer_moe for language modelling

### ISSUE THREAD

**Issue by maremun** [tensorflow/tensor2tensor#830]
I’m using T2T for language modeling with TensorFlow 1.7 and Tensor2Tensor 1.6.3.
I'm applying the `transformer_moe` model to train the `languagemodel_ptb10k` problem.
For `HPARAMS`, I tried using `transformer_moe_prepend_8k`, `transformer_moe_8k`, `transformer_moe_8k_lm`, but none of them worked.  Is the transformer_moe model available for language modeling? Am I missing something? Or are there some other settings?

The traceback:
> Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 353, in main
    execute_schedule(exp)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 302, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/framework/experimental.py", line 64, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 773, in continuous_train_and_eval
    saving_listeners=self._saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 876, in _call_train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 821, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 680, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 772, in _call_input_fn
    return input_fn(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 662, in estimator_input_fn
    dataset_kwargs=dataset_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 754, in input_fn
    dataset = self.dataset(**dataset_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 571, in dataset
    _load_records_and_preprocess, sloppy=is_training, cycle_length=8))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 960, in apply
    dataset = transformation_func(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 76, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/readers.py", line 163, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 488, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/readers.py", line 151, in tf_map_func
    dataset = map_func(nested_args)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 554, in _load_records_and_preprocess
    dataset = self.preprocess(dataset, mode, hparams)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 348, in preprocess
    _preprocess, sloppy=is_training, cycle_length=8))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 960, in apply
    dataset = transformation_func(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 76, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/readers.py", line 163, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 488, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/readers.py", line 151, in tf_map_func
    dataset = map_func(nested_args)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 340, in _preprocess
    examples = self.preprocess_example(example, mode, hparams)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 313, in preprocess_example
    return preprocess_example_common(example, hparams, mode)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/data_generators/problem.py", line 116, in preprocess_example_common
    example["inputs"] = example["inputs"][:hparams.max_input_seq_length]
KeyError: 'inputs'

**Comment by shengyushen** [comment]
I met the same problem at the same place.
What I run is transformer_moe and lm1b benchmark
