### ISSUE TITLE
*bug* EOS token expected on Text2ClassProblem labels

### ISSUE THREAD

**Issue by friesel** [tensorflow/tensor2tensor#844]
### Description

I created a Text2ClassProblem including 7 labels. When I execute t2t-decoder, it crashes as soon as the output is label id 1. I researched a bit and in decoding.py it is running through **_save_until_eos**, where id 1 is removed. But why is this function called on label ids, when id 0 and 1 are allowed?
This is also part of the description for Text2ClassProblem: The label should be an int in [0, self.num_classes)

I used:
- model: transformer
- hparams_set: transformer_base_single_gpu
- vocab: 32k subwords

### Environment information

OS: Ubuntu 16.04

$ pip freeze | grep tensor
tensor2tensor==1.6.2
tensorboard==1.7.0
tensorflow-gpu==1.7.0

$ python -V
Python 2.7.12

# Steps to reproduce:
Create a Text2ClassProblem and assign label ids 0-6.
t2t-datagen
t2t-trainer
t2t-decoder
(then it should crash)

# Error logs:
Traceback (most recent call last):
  File "/home/***/.local/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/***/.local/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/home/***/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 190, in main
    decode(estimator, hp, decode_hp)
  File "/home/***/.local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 104, in decode
    dataset_split="test" if FLAGS.eval_use_test_set else None)
  File "/home/***/.local/lib/python2.7/site-packages/tensor2tensor/utils/decoding.py", line 204, in decode_from_dataset
    log_targets=decode_hp.log_targets)
  File "/home/***/.local/lib/python2.7/site-packages/tensor2tensor/utils/decoding.py", line 94, in log_decode_results
    decoded_outputs = targets_vocab.decode(_save_until_eos(outputs, is_image))
  File "/home/***/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 230, in decode
    return self._class_labels[label_id]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by rsepassi** [comment]
That is indeed a bug. `decoding.py` needs to check the target modality and only `_save_until_eos` if it's `SymbolModality`.

**Comment by friesel** [comment]
There is another symptom when I use `t2t-exporter` to export a `Text2ClassProblem`, the tensorflow_model_server prints an error, when requesting an inference. Maybe this is related to this issue?

# Steps to reproduce:
t2t-exporter
tensorflow_model_server
t2t-query-server

# Error logs:
Traceback (most recent call last):
  File "/home/***/dev/git/prinvision/nets/test_doc_to_language.py", line 22, in <module>
    outputs = service.process(inputs)
  File "/home/***/dev/git/prinvision/nets/public_service_api_v3.py", line 50, in process
    outputs = serving_utils.predict([input_string], self.problem, self.request_fn)
  File "/home/***/.local/lib/python2.7/site-packages/tensor2tensor/serving/serving_utils.py", line 118, in predict
    predictions = request_fn(examples)
  File "/home/***/.local/lib/python2.7/site-packages/tensor2tensor/serving/serving_utils.py", line 75, in _make_grpc_request
    response = stub.Predict(request, timeout_secs)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="Feature: targets (data type: int64) is required but could not be found.
	 [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_INT64, DT_INT64], dense_keys=["batch_prediction_key", "targets"], dense_shapes=[[1], [1]], num_sparse=1, sparse_keys=["inputs"], sparse_types=[DT_INT64]](arg0, ParseSingleExample/Reshape, ParseSingleExample/Const)]]
	 [[Node: DatasetToSingleElement = DatasetToSingleElement[output_shapes=[[?,1], [?,?,1,1], [?,1,1,1]], output_types=[DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MapDataset_4)]]")

**Comment by fciannel** [comment]
I got the same issue on the vanilla imdb sentiment problem when decoding:

Traceback (most recent call last):
  File "/home/***/bin/t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/home/***/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/***/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/home/***/lib/python3.5/site-packages/tensor2tensor/bin/t2t_decoder.py", line 190, in main
    decode(estimator, hp, decode_hp)
  File "/home/***/lib/python3.5/site-packages/tensor2tensor/bin/t2t_decoder.py", line 93, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "/home/***/lib/python3.5/site-packages/tensor2tensor/utils/decoding.py", line 290, in decode_from_file
    None, inputs_vocab, targets_vocab)
  File "/home/***/lib/python3.5/site-packages/tensor2tensor/utils/decoding.py", line 93, in log_decode_results
    decoded_outputs = targets_vocab.decode(_save_until_eos(outputs, is_image))
  File "/home/***/lib/python3.5/site-packages/tensor2tensor/data_generators/text_encoder.py", line 227, in decode
    return self._class_labels[label_id]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by yanboliang** [comment]
@friesel @rsepassi @fciannel I sent a [PR](#866) to fix this bug, wish it can help. Thanks.

**Comment by ShahNewazKhan** [comment]
I had the same error with the imdb sentiment problem, I implemented the changes to `/utils/decoding.py` as per @yanboliang 's fix and the issue was resolved :D
