### ISSUE TITLE
ModuleNotFoundError: No module named 'oauth2client'

### ISSUE THREAD

**Issue by activatedgeek** [tensorflow/tensor2tensor#854]
### Description

The requirements are missing `oauth2client` as a dependency. `pip install tensor2tensor` does not install it, nor it has been specified in `setup.py`.

### Environment information

```
OS: macOS 10.13

$ pip freeze | grep tensor
tensor2tensor==1.6.3
tensorboard==1.8.0
tensorflow==1.8.0

$ python -V
Python 3.6.5
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
1. `pip install tensor2tensor`
2. `t2t-trainer ...` (on any problem)
```

```
# Error logs:
Traceback (most recent call last):
  File "/Workspace/venv3/lib/python3.6/site-packages/tensor2tensor/bin/t2t_trainer.py", line 28, in <module>
    from tensor2tensor.utils import cloud_mlengine
  File "/Workspace/venv3/lib/python3.6/site-packages/tensor2tensor/utils/cloud_mlengine.py", line 24, in <module>
    from oauth2client.client import GoogleCredentials
ModuleNotFoundError: No module named 'oauth2client'
```

### Potential Fix

```
$ pip install oauth2client
```

**Comment by martinpopel** [comment]
Few more details:
[setup.py](https://github.com/tensorflow/tensor2tensor/blob/f76d5ea8f2b90d5ec7fd1c4a5a6fe1bd6d9c95cf/setup.py#L39) requires [google-api-python-client](https://pypi.org/project/google-api-python-client/), which depended on [oauth2client](https://pypi.org/project/oauth2client/) in past.
However, [oauth2client](https://pypi.org/project/oauth2client/) is now deprecated (substituted by [google-auth](https://pypi.org/project/google-auth/)) and [google-api-python-client](https://pypi.org/project/google-api-python-client/) does not depend on it anymore (it requires `google-auth, uritemplate, google-auth-httplib2, httplib2, six`).
Thus, I think the code in `tensor2tensor/utils/cloud_mlengine.py` should be updated to use only the non-deprecated API from `google-api-python-client`.

**Comment by texasmichelle** [comment]
I also ran into this error and would like to see a fix since it impacts uses of tensor2tensor that have no references to CMLE.

**Comment by hpulfc** [comment]
Perfect !
