### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'session_config'

### ISSUE THREAD

**Issue by minfengUCAS** [tensorflow/tensor2tensor#94]
Traceback (most recent call last):
  File "/home/minfeng.zhan/anaconda2/bin/t2t-trainer", line 83, in <module>
    tf.app.run()
  File "/home/minfeng.zhan/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/minfeng.zhan/anaconda2/bin/t2t-trainer", line 79, in main
    schedule=FLAGS.schedule)
  File "/home/minfeng.zhan/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 246, in run
    run_locally(exp_fn(output_dir))
  File "/home/minfeng.zhan/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 131, in experiment_fn
    eval_steps=eval_steps)
  File "/home/minfeng.zhan/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 143, in create_experiment
    model_name=model_name)
  File "/home/minfeng.zhan/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 180, in create_experiment_components
    keep_checkpoint_max=FLAGS.keep_checkpoint_max))
TypeError: __init__() got an unexpected keyword argument 'session_config'

I had run the t2t-datagen successfully.  When I run the t2t-trainer, the error occured. How can I fix this problem?

**Comment by stefan-it** [comment]
Are you using `tensorflow` in version *>=1.2*?

**Comment by minfengUCAS** [comment]
Thinks, I have fixed the problem by upgrading the tensorflow!

**Comment by lukaszkaiser** [comment]
Thanks @stefan-it for the solution!
