### ISSUE TITLE
t2t-trainer eval_early_stopping crashed at GetAccumulator() with KeyError 'run0'

### ISSUE THREAD

**Issue by LiweiPeng** [tensorflow/tensor2tensor#957]
### Description
With t2t 1.6.6, tensorflow 1.8.0, I ran cifar100 with eval early stopping. The cmd failed quickly with crash at tensorboard/backend/event_processing/event_multiplexer.py, GetAccumulator() with KeyError 'run0'

### Environment information

```
OS: CentOS 7.4 x64

$ pip freeze | grep tensor
tensor2tensor==1.6.6
tensorboard==1.8.0
tensorflow==1.8.0

$ python -V
Python 2.7.5
```

### For bugs: reproduction and error logs

```
t2t-trainer --generate_data --tmp_dir=./tmp --data_dir=./cifar-100-python --output_dir=./cifar-out --problem=image_cifar100 --model=resnet --hparams_set=resnet_18 --hparams=learning_rate=0.001 --worker_gpu=1 --eval_early_stopping_steps=10 --schedule=train --train_steps=3000 --eval_steps=100
```

```
# Error logs:

INFO:tensorflow:Generating data for image_cifar100
INFO:tensorflow:Not downloading, file already found: ./tmp/cifar-100-python.tar.gz
INFO:tensorflow:Not downloading, file already found: ./tmp/cifar-100-python.tar.gz
2018-07-26 13:48:31.403947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:04:00.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2018-07-26 13:48:31.590744: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-26 13:48:31.591518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 1 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:84:00.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2018-07-26 13:48:31.591578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1
2018-07-26 13:48:32.201392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-26 13:48:32.201453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 
2018-07-26 13:48:32.201463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N N 
2018-07-26 13:48:32.201469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   N N 
2018-07-26 13:48:32.202163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15137 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:04:00.0, compute capability: 6.0)
2018-07-26 13:48:32.380463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15137 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:84:00.0, compute capability: 6.0)
INFO:tensorflow:Generating case 0.
INFO:tensorflow:Generated 50000 Examples
2018-07-26 13:48:58.058549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1
2018-07-26 13:48:58.058660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-26 13:48:58.058672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 
2018-07-26 13:48:58.058679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N N 
2018-07-26 13:48:58.058685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   N N 
2018-07-26 13:48:58.058947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15137 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:04:00.0, compute capability: 6.0)
2018-07-26 13:48:58.059052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15137 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:84:00.0, compute capability: 6.0)
INFO:tensorflow:Generating case 0.
INFO:tensorflow:Generated 10000 Examples
INFO:tensorflow:Shuffling data...
INFO:tensorflow:Data shuffled.
INFO:tensorflow:Overriding hparams in resnet_18 with learning_rate=0.001
WARNING:tensorflow:From /usr/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py:165: __init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:schedule=train
INFO:tensorflow:worker_gpu=1
INFO:tensorflow:sync=False
INFO:tensorflow:datashard_devices: ['/job:localhost']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 20, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0xb2d5190>, '_keep_checkpoint_every_n_hours': 10000, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': None, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_train_distribute': None, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 1000, '_environment': 'local', '_master': '', '_model_dir': './cifar-out', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0xb2d51d0>, '_save_summary_steps': 100}
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0xaaecf50>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using EarlyStoppingHook
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multplexer doing initialization load for {'run0': './cifar-out/eval_continuous/'}
INFO:tensorflow:Constructing EventAccumulator for ./cifar-out/eval_continuous/
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:Reading data files from ./cifar-100-python/image_cifar100-train*
INFO:tensorflow:partition: 0 num_data_files: 10
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Setting T2TModel mode to 'train'
INFO:tensorflow:Using variable initializer: normal_unit_scaling
INFO:tensorflow:Transforming feature 'inputs' with image_modality.bottom
INFO:tensorflow:Transforming 'targets' with class_label_modality_100_64.targets_bottom
INFO:tensorflow:Building model body
INFO:tensorflow:Transforming body output with class_label_modality_100_64.top
WARNING:tensorflow:From /usr/lib/python2.7/site-packages/tensor2tensor/layers/modalities.py:703: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:Applying exp learning rate warmup for 100 steps
INFO:tensorflow:Applying learning rate decay: cosine.
INFO:tensorflow:Base learning rate: 0.001000
INFO:tensorflow:Applying weight decay, decay_rate: 0.00010
INFO:tensorflow:Trainable Variables Total size: 11231140
INFO:tensorflow:Using optimizer Momentum
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-07-26 13:49:08.290671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1
2018-07-26 13:49:08.290789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-26 13:49:08.290802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 
2018-07-26 13:49:08.290809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N N 
2018-07-26 13:49:08.290815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   N N 
2018-07-26 13:49:08.291089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15137 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:04:00.0, compute capability: 6.0)
2018-07-26 13:49:08.291227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15137 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:84:00.0, compute capability: 6.0)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into ./cifar-out/model.ckpt.
INFO:tensorflow:Beginning EventMultiplexer.Reload()
WARNING:tensorflow:Deleting accumulator 'run0'
INFO:tensorflow:Finished with EventMultiplexer.Reload()
Traceback (most recent call last):
  File "/usr/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 359, in main
    execute_schedule(exp)
  File "/usr/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 306, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/usr/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 303, in train
    max_steps=self._train_spec.max_steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 859, in _train_model_default
    saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1059, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1043, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1199, in run
    run_metadata=run_metadata))
  File "/usr/lib/python2.7/site-packages/tensor2tensor/utils/metrics_hook.py", line 81, in after_run
    metrics = self._collect_metrics()
  File "/usr/lib/python2.7/site-packages/tensor2tensor/utils/metrics_hook.py", line 95, in _collect_metrics
    accum = self._event_multiplexer.GetAccumulator(self._RUN_NAME % i)
  File "/usr/lib/python2.7/site-packages/tensorboard/backend/event_processing/event_multiplexer.py", line 482, in GetAccumulator
    return self._accumulators[run]
KeyError: 'run0'

```

**Comment by msaffarm** [comment]
I get the same error while using --schedule=train
Here's the configuration: ()
```
# Ubuntu 18.04
# Cuda 9.0 with cudnn 7.0

#conda list | grep tensor*
tensor2tensor             1.9.0                     <pip>
tensorboard               1.10.0                    <pip>
tensorflow-gpu            1.10.1                    <pip>

#python -V
Python 3.5.5

#nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.67                 Driver Version: 390.67                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   63C    P8     5W /  N/A |    524MiB /  6075MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```
To replicate the problem run:
```
t2t-trainer \
  --generate_data \
  --data_dir=~/t2t_data \
  --output_dir=~/t2t_train/mnist \
  --problem=image_mnist \
  --model=shake_shake \
  --hparams_set=shake_shake_quick \
  --train_steps=1000 \
  --eval_steps=100 \
  --schedule=train \
  --eval_early_stopping_steps=100
```
I get the same error as above issue:
```
INFO:tensorflow:Beginning EventMultiplexer.Reload()
WARNING:tensorflow:Deleting accumulator 'run0'
INFO:tensorflow:Finished with EventMultiplexer.Reload()
Traceback (most recent call last):
  File "/home/mansour/anaconda3/envs/t2t/bin/t2t-trainer", line 33, in <module>
    tf.app.run()
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/mansour/anaconda3/envs/t2t/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 355, in main
    execute_schedule(exp)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 321, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensor2tensor/utils/trainer_lib.py", line 345, in train
    max_steps=self._train_spec.max_steps)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1173, in _train_model_default
    saving_listeners)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/home/mansour/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1215, in run
    run_metadata=run_metadata))
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensor2tensor/utils/metrics_hook.py", line 81, in after_run
    metrics = self._collect_metrics()
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensor2tensor/utils/metrics_hook.py", line 95, in _collect_metrics
    accum = self._event_multiplexer.GetAccumulator(self._RUN_NAME % i)
  File "/home/mansour/anaconda3/envs/t2t/lib/python3.5/site-packages/tensorboard/backend/event_processing/event_multiplexer.py", line 482, in GetAccumulator
    return self._accumulators[run]
KeyError: 'run0'

```
It seems the problem is related to tensorboard backend. But I couldn't fix it! Any help is much appreciated since early stopping is crucial for DL!!
