### ISSUE TITLE
Timeseries problems on TPU throw exception "unexpected keyword argument 'drop_remainder'"

### ISSUE THREAD

**Issue by me-sh** [tensorflow/tensor2tensor#962]
Hello,
When training on both timeseries problems, timeseries_toy_problem and timeseries_synthetic_data_series10_samples100k, I get an exception, unexpected keyword argument 'drop_remainder'.  Any tips? 
Thanks!

update: the following change in problem.py seems to solve the problem in this case:
dataset.batch(batch_size, drop_remainder=True) -> dataset = dataset.batch(batch_size).  However, I am not sure what's the functionality of drop_remainder and whether omitting it is ok here.
...

### Environment information

```
OS: Debian GNU/Linux 9.4 (stretch) on Google Cloud

$ pip freeze | grep tensor
-e git+https://github.com/tensorflow/tensor2tensor.git@814c4a13e1b03e3db444b31be2e6337c02c11bc7#egg=tensor2tensor
tensorboard==1.8.0
tensorflow==1.8.0

$ python -V
Python 2.7.13
```
# Steps to reproduce:

t2t-datagen --problem=timeseries_synthetic_data_series10_samples100k --data_dir=$DATA_DIR --tmp_dir=$TMP_DIR
               
t2t-trainer \
  --model=transformer \
  --hparams_set=transformer_tpu \
  --data_dir=$DATA_DIR \
  --problem=timeseries_synthetic_data_series10_samples100k \
  --train_steps=1 \
  --eval_steps=1 \
  --output_dir=$OUT_DIR \
  --use_tpu=True \
  --master=$TPU_MASTER

```

```
# Error logs:
INFO:tensorflow:Found TPU system:
INFO:tensorflow:*** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:CPU:0, CPU, -1)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:XLA_GPU:0, XLA_GPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:0, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:1, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:2, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:3, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:4, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:5, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:6, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:7, TPU, 17179869184)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 17179869184)
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:num_partitions = 1 partition_id = 0
INFO:tensorflow:Reading data files from gs://elec_transformer_bucket/TS/data/timeseries_synthetic_data_series10_samples100k-train*
INFO:tensorflow:partition: 0 num_data_files: 9
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/meshx/tfrc_scripts/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/meshx/tfrc_scripts/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/meshx/tfrc_scripts/tensor2tensor/tensor2tensor/bin/t2t_trainer.py", line 368, in main
    execute_schedule(exp)
  File "/home/meshx/tfrc_scripts/tensor2tensor/tensor2tensor/bin/t2t_trainer.py", line 315, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/meshx/tfrc_scripts/tensor2tensor/tensor2tensor/utils/trainer_lib.py", line 305, in continuous_train_and_eval
    self._eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 650, in run_local
    hooks=train_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2025, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 992, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1055, in _invoke_input_fn_and_record_structure
    host_device, host_id))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 687, in generate_per_host_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1976, in _input_fn
    return input_fn(**kwargs)
  File "/home/meshx/tfrc_scripts/tensor2tensor/tensor2tensor/data_generators/problem.py", line 733, in estimator_input_fn
    dataset_kwargs=dataset_kwargs)
  File "/home/meshx/tfrc_scripts/tensor2tensor/tensor2tensor/data_generators/problem.py", line 865, in input_fn
    dataset = dataset.batch(batch_size, drop_remainder=True)
TypeError: batch() got an unexpected keyword argument 'drop_remainder'
```

**Comment by ppzqh** [comment]
Hi Meir Meshulam. I am using tensor2tensor to build a transformer network for time series prediction. But I encounter some problems while training and cannot fix it after searching a lot of tutorials. I wonder if you have successfully train your network and could you please help me with my problems. 

There lists my training log:

> I0722 16:13:18.533865 140442886694656 session_manager.py:502] Done running local_init_op.
> I0722 16:13:21.954446 140442886694656 basic_session_run_hooks.py:606] Saving checkpoints for 0 into ./models/model.ckpt.
> 2019-07-22 16:13:25.741894: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0

The problem:
My program paused at this position, it was not processing anything but just paused here and didn't exit. 

I will be appreciate if you can help me figure out the answer to this problem. Thank you!

**Comment by ppzqh** [comment]
Hi Meir Meshulam. I am using tensor2tensor to build a transformer network for time series prediction. But I encounter some problems while training and cannot fix it after searching a lot of tutorials. I wonder if you have successfully train your network and could you please help me with my problems. 

There lists my training log:

> I0722 16:13:18.533865 140442886694656 session_manager.py:502] Done running local_init_op.
> I0722 16:13:21.954446 140442886694656 basic_session_run_hooks.py:606] Saving checkpoints for 0 into ./models/model.ckpt.
> 2019-07-22 16:13:25.741894: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0

The problem:
My program paused at this position, it was not processing anything but just paused here and didn't exit. 

I will be appreciated if you can help me figure out the answer to this problem. Thank you!

**Comment by me-sh** [comment]
fix merged
