### ISSUE TITLE
module 'tensor2tensor.bin.t2t_trainer' has no attribute 'main'

### ISSUE THREAD

**Issue by rogerrabbit222** [tensorflow/tensor2tensor#966]
In trying to run the simple examples setup (cloud-poetry or the code snippet below), I am getting errors where module 'tensor2tensor.bin.t2t_trainer' has no attribute 'main' or AttributeError: module 'tensor2tensor.bin.t2t_datagen' has no attribute 'main'

An example is simply running this code:

t2t-trainer \
  --generate_data \
  --data_dir=~/t2t_data \
  --output_dir=~/t2t_train/mnist \
  --problem=image_mnist \
  --model=shake_shake \
  --hparams_set=shake_shake_quick \
  --train_steps=1000 \
  --eval_steps=100 

Thoughts?
...

### Environment information

```
OS: Ubuntu 16

$ pip freeze | grep tensor
tensor2tensor==1.6.6
tensorboard==1.9.0
tensorflow==1.9.0

$ python -V
Python 3.6.6 :: Anaconda, Inc.
```

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
AttributeError: module 'tensor2tensor.bin.t2t_trainer' has no attribute 'main'...
```

**Comment by rogerrabbit222** [comment]
uninstalled and re-pipped tensor2tensor seems to have resolved this issue
