### ISSUE TITLE
when I run the given test example with my dataset, I got the following error, could you help me figure out the reasson

### ISSUE THREAD

**Issue by lqfarmer** [tensorflow/tensor2tensor#98]
[@nmyjs_176_104 tensor2tensor]# sh -x test.sh 
+ PROBLEM=wmt_ende_tokens_32k
+ MODEL=transformer
+ HPARAMS=transformer_big_single_gpu
+ DATA_BASE=/search/odin/liuqi/tensor2tensor/data
+ DATA_DIR=/search/odin/liuqi/tensor2tensor/data/t2t_data
+ TMP_DIR=/tmp/t2t_datagen
+ TRAIN_DIR=/search/odin/liuqi/tensor2tensor/data/t2t_train/wmt_ende_tokens_32k/transformer-transformer_big_single_gpu
+ DECODE_FILE=/search/odin/liuqi/tensor2tensor/data/t2t_data/decode_this.txt
+ BEAM_SIZE=6
+ ALPHA=0.6
+ t2t-trainer --data_dir=/search/odin/liuqi/tensor2tensor/data/t2t_data --problems=wmt_ende_tokens_32k --model=transformer --hparams_set=transformer_big_single_gpu --output_dir=/search/odin/liuqi/tensor2tensor/data/t2t_train/wmt_ende_tokens_32k/transformer-transformer_big_single_gpu --train_steps=0 --eval_steps=0 --worker_gpu=1 --decode_batch_size=10 --decode_beam_size=6 --decode_alpha=0.6 --decode_from_file=/search/odin/liuqi/tensor2tensor/data/t2t_data/decode_this.txt
INFO:tensorflow:Creating experiment, storing model files in /search/odin/liuqi/tensor2tensor/data/t2t_train/wmt_ende_tokens_32k/transformer-transformer_big_single_gpu
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': '/search/odin/liuqi/tensor2tensor/data/t2t_train/wmt_ende_tokens_32k/transformer-transformer_big_single_gpu', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x4eaaa10>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_session_config': allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
}
INFO:tensorflow:Performing Decoding from a file.
INFO:tensorflow:Getting sorted inputs
INFO:tensorflow: batch 101
INFO:tensorflow:Deocding batch 0
Traceback (most recent call last):
  File "/usr/bin/t2t-trainer", line 5, in <module>
    pkg_resources.run_script('tensor2tensor==1.0.9', 't2t-trainer')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensor2tensor-1.0.9-py2.7.egg/EGG-INFO/scripts/t2t-trainer", line 83, in <module>
    
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/lib/python2.7/site-packages/tensor2tensor-1.0.9-py2.7.egg/EGG-INFO/scripts/t2t-trainer", line 79, in main
    
  File "build/bdist.linux-x86_64/egg/tensor2tensor/utils/trainer_utils.py", line 246, in run
  File "build/bdist.linux-x86_64/egg/tensor2tensor/utils/trainer_utils.py", line 543, in run_locally
  File "build/bdist.linux-x86_64/egg/tensor2tensor/utils/trainer_utils.py", line 647, in decode_from_file
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 590, in predict
    as_iterable=as_iterable)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 883, in _infer_model
    features = self._get_features_from_input_fn(input_fn)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 863, in _get_features_from_input_fn
    result = input_fn()
  File "build/bdist.linux-x86_64/egg/tensor2tensor/utils/trainer_utils.py", line 727, in _decode_batch_input_fn
  File "build/bdist.linux-x86_64/egg/tensor2tensor/data_generators/text_encoder.py", line 223, in encode
  File "build/bdist.linux-x86_64/egg/tensor2tensor/data_generators/text_encoder.py", line 251, in _tokens_to_subtokens
  File "build/bdist.linux-x86_64/egg/tensor2tensor/data_generators/text_encoder.py", line 295, in _escaped_token_to_subtokens
AssertionError

**Comment by lukaszkaiser** [comment]
This is hopefully corrected in 1.0.11. please give it a try. I'm closing for now, please reopen if you still see the issue.

**Comment by lqfarmer** [comment]
@lukaszkaiser . It seems not helpful after update tensor2tensor to version 1.0.11. The same problem appear again.

**Comment by tobyyouup** [comment]
@lukaszkaiser  @lqfarmer   My tensor2tensor version is 1.0.12, I also encounter this problem. But it works ok when I use old tensor2tensor version 1.0.9.   So I check the code difference, it's due to the assert of line 295 in file tensor2tensor/data_generators/text_encoder.py, There is no subtoken for special tokens like (one's, it's). I change it back to 1.0.9 and it works normally now!

**Comment by lukaszkaiser** [comment]
Hmm, did you re-generate the vocabulary with the newer tensor2tensor? I think it'd be a good idea to grab 1.0.13 and re-generate the whole data from scratch. It doesn't take that long (except for the download, but you might already have it in $TMP), and it should (hopefully) work all ok. Can you check and let us know? If it still fails, can you paste the sequence of commands you run? Thanks!

**Comment by lqfarmer** [comment]
Thank you, It works.

**Comment by lukaszkaiser** [comment]
Thanks!
