### ISSUE TITLE
tensorflow_model_server not responding correctly

### ISSUE THREAD

**Issue by kockahonza** [tensorflow/tensor2tensor#990]
### Description
I have trained the translate_encs_wmt32k_rev problem and now am trying to use the tensorflow_model_server to serve it. I have installed it locally and I also am using the docker image but both have the same results. I am trying to use gPRC and REST APIs but neither of them work.

I start the server this way with docker
```
nvidia-docker run -p 8500:8500 -p 8501:8501 -v $TRAIN_DIR/export/Servo:/models/my_model -e MODEL_NAME=my_model -t tensorflow/serving:latest-gpu
```

and this way without it
```
./tensorflow_model_server --port=8080 --model_name=my_model --model_base_path=$TRAIN_DIR/export/Servo
```

when I run t2t-query I get this
```
honza@honza-xps ~/W/U/E/t/encs> t2t-query-server --server=localhost:8500 --servable_name=my_model --problem=$PROBLEM --data_dir=$DATA_DIR --inputs_once="ahoj"
Traceback (most recent call last):
  File "/usr/bin/t2t-query-server", line 16, in <module>
    tf.app.run()
  File "/usr/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/bin/t2t-query-server", line 12, in main
    query.main(argv)
  File "/usr/lib/python3.7/site-packages/tensor2tensor/serving/query.py", line 88, in main
    outputs = serving_utils.predict([inputs], problem, request_fn)
  File "/usr/lib/python3.7/site-packages/tensor2tensor/serving/serving_utils.py", line 114, in predict
    predictions = request_fn(examples)
  File "/usr/lib/python3.7/site-packages/tensor2tensor/serving/serving_utils.py", line 71, in _make_grpc_request
    response = stub.Predict(request, timeout_secs)
  File "/usr/lib/python3.7/site-packages/grpc/_channel.py", line 514, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/lib/python3.7/site-packages/grpc/_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/add, transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/concat)]]
	 [[Node: transformer/while/body/parallel_0/body/decoder/layer_4/ffn/conv1/Tensordot/Shape/_1127 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5346_...rdot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopConstantFolding/transformer/while/body/parallel_0/body/decoder/laye...TRUNCATED"
	debug_error_string = "{"created":"@1534190158.516842292","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1095,"grpc_message":"Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero\n\t [[Node: transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/add, transformer/body/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/concat)]]\n\t [[Node: transformer/while/body/parallel_0/body/decoder/layer_4/ffn/conv1/Tensordot/Shape/_1127 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5346_...rdot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopConstantFolding/transformer/while/body/parallel_0/body/decoder/laye...TRUNCATED","grpc_status":3}"
>
```

and when I use curl to access the REST API I get this
```
honza@honza-xps ~> curl -d '{"instances": [{"input": "Ahoj"}]}' -X POST http://localhost:8501/v1/models/my_model:predict
{ "error": "Could not parse example input, value: \'Ahoj\'\n\t [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_INT64], dense_keys=[\"batch_prediction_key\"], dense_shapes=[[1]], num_sparse=2, sparse_keys=[\"inputs\", \"targets\"], sparse_types=[DT_INT64, DT_INT64]](arg0, ParseSingleExample/Reshape)]]\n\t [[Node: DatasetToSingleElement = DatasetToSingleElement[output_shapes=[[?,1], [?,?,1,1], [?,?,1,1]], output_types=[DT_INT32, DT_INT32, DT_INT32], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](MapDataset_4)]]\n\t [[Node: transformer/while/body/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/output_transform/Tensordot/GatherV2/_807 = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_3723_...t/GatherV2\", tensor_type=DT_INT32, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"](^_clooptransformer/while/symbol_modality_32888_512/parallel_0/symbol_modality_32888_512/shared/Squeeze/_410)]]" }⏎                                                                             
```

Also when I look at the server logs when I use t2t-query nothing show up on there while with curl it shows a error. This is the whole log and the last line is the one that appears after each curl execution.
```
2018-08-13 20:04:59.124197: I tensorflow_serving/model_servers/main.cc:157] Building single TensorFlow model file config:  model_name: my_model model_base_path: /models/my_model
2018-08-13 20:04:59.124561: I tensorflow_serving/model_servers/server_core.cc:462] Adding/updating models.
2018-08-13 20:04:59.124602: I tensorflow_serving/model_servers/server_core.cc:517]  (Re-)adding model: my_model
2018-08-13 20:04:59.225195: I tensorflow_serving/core/basic_manager.cc:739] Successfully reserved resources to load servable {name: my_model version: 1534129049}
2018-08-13 20:04:59.225268: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: my_model version: 1534129049}
2018-08-13 20:04:59.225310: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: my_model version: 1534129049}
2018-08-13 20:04:59.225367: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /models/my_model/1534129049
2018-08-13 20:04:59.225407: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/my_model/1534129049
2018-08-13 20:04:59.701749: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2018-08-13 20:04:59.766195: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-13 20:05:00.144263: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-13 20:05:00.145509: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.90GiB
2018-08-13 20:05:00.145555: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-08-13 20:05:00.422697: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-13 20:05:00.422727: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-08-13 20:05:00.422751: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-08-13 20:05:00.423054: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3629 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-13 20:05:00.609687: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:113] Restoring SavedModel bundle.
2018-08-13 20:05:00.847616: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:148] Running LegacyInitOp on SavedModel bundle.
2018-08-13 20:05:00.939754: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:233] SavedModel load for tags { serve }; Status: success. Took 1714341 microseconds.
2018-08-13 20:05:00.939811: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:83] No warmup data file found at /models/my_model/1534129049/assets.extra/tf_serving_warmup_requests
2018-08-13 20:05:00.939935: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: my_model version: 1534129049}
2018-08-13 20:05:00.941520: I tensorflow_serving/model_servers/main.cc:327] Running ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2018-08-13 20:05:00.942502: I tensorflow_serving/model_servers/main.cc:337] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 235] RAW: Entering the event loop ...
2018-08-13 20:05:20.740251: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: 'Ahoj'
2018-08-13 20:07:07.921231: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: 'Ahoj'
2018-08-13 20:07:10.157668: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: 'Ahoj'
2018-08-13 20:07:13.500175: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: 'Ahoj'
2018-08-13 20:07:13.776296: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: 'Ahoj'
2018-08-13 20:07:14.115015: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: 'Ahoj'
2018-08-13 20:07:14.350318: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: 'Ahoj'
```

### Environment information

```
OS: Arch linux

$ pip freeze | grep tensor
tensor2tensor==1.7.0
tensorboard==1.9.0
tensorflow==1.9.0
tensorflow-serving-api==1.10.0

$ python -V
Python 3.7.0
```

**Comment by rsepassi** [comment]
When query the model directly (without `t2t-query-server`) you must provide a serialized tf.train.Example that looks the same as what would be on disk during training, not an input string ("ahoj").

The query server does this for you. However, it is meant only as an example and may need to be modified to work for your Problem. Likely what is happening is that there is a missing feature (for example, even though the "label" will be unused during prediction, the model still expects it because it expects something identical to what's on disk). See `serving_utils._make_example` and add other required features with dummy values.

This [commit](https://github.com/tensorflow/tensor2tensor/commit/1747148b6f7e02a22af514799cb0b43e74facabc) should automatically fill in the other required features with dummy values, but you still may need to modify the querying in other ways if that doesn't fix your problem.
